<?php
/** Connection-local temporary tables: no real accounts, jobs, messages or subscriptions change. */
if(PHP_SAPI!=='cli'||getenv('FCC_LOCAL')!=='1')exit(1);
define('ALTUMCODE',66);define('DEBUG',0);define('MYSQL_DEBUG',0);define('LOGGING',1);define('CACHE',0);require dirname(__DIR__).'/app/init.php';
set_exception_handler(function($e){fwrite(STDERR,get_class($e).': '.$e->getMessage().' at line '.$e->getLine().PHP_EOL);exit(1);});
if(DATABASE_NAME!=='fcc_partner_local'||DATABASE_SERVER!=='db')exit(1);
$tables=['links','domains','users_biolinks','fcc_business_presentations','fcc_business_shares','users','fcc_partner_rollout_control','fcc_partner_rollout_access','fcc_partner_rollout_audit','fcc_partner_journey_cycles','fcc_partner_journey_steps'];
foreach($tables as $t){$ddl=database()->query("SHOW CREATE TABLE `$t`")->fetch_row()[1];$ddl=implode("\n",array_filter(explode("\n",$ddl),fn($line)=>!str_starts_with(ltrim($line),'CONSTRAINT ')));$ddl=preg_replace('/,\n\)/',"\n)",$ddl);if(!database()->query(str_replace('CREATE TABLE','CREATE TEMPORARY TABLE',$ddl)))throw new RuntimeException(database()->error);}
fcc_partner_query('INSERT INTO fcc_partner_rollout_control(id,managed,revision,updated_at) VALUES(1,0,1,UTC_TIMESTAMP())');
$checks=[];$ok=function($v,$label)use(&$checks){if(!$v)throw new RuntimeException($label);$checks[]=$label;};
$reject=function($fn,$label)use($ok){try{$fn();$blocked=false;}catch(InvalidArgumentException $e){$blocked=true;}$ok($blocked,$label);};
$add=function($id,$email,$name,$type=0,$status=1,$fbo=''){
 fcc_partner_query('INSERT INTO users(user_id,email,name,type,status,preferences,plan_id,plan_settings,plan_expiration_date,referral_key,referred_by,payment_subscription_id,payment_processor,extra) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$id,$email,$name,$type,$status,json_encode(['meta'=>['foreverId'=>$fbo,'fcc_core_progress'=>8,'fcc_core_completed'=>true]]),'5','{"ai_growth_plan_is_enabled":true}','2099-01-01 00:00:00','ref'.$id,1,'sub_qa_'.$id,'stripe','{}']);
};
$add(1,'admin@example.test','Admin',1);$add(2,'belosa.flp@gmail.com','Stjepan',0,1,'385-123456789');$add(3,'stjepan@belosa.info','Stjepan drugi',0,1,'385123456789');$add(4,'snjezana@example.test','Snježana',0,1,'385123456789');$add(5,'other@example.test','Stjepan Beloša',0,1,'385999999999');$add(6,'blocked@example.test','Blokirani admin',1,2);$add(7,'inactive-child@example.test','Neaktivan',0,2,'385123456789');
$plan=fcc_rollout_seed_plan(fcc_rollout_users());$ok(array_column($plan['accounts'],'user_id')===[1,2,3,4],'Initial accounts use exact emails, matching Forever ID and active admins');
$ok($plan['ready'],'Verified production email spelling resolves initial accounts');
putenv('FCC_PARTNER_SEED_EXCLUDE_EMAILS=snjezana@example.test,admin@example.test');
$ok(array_column(fcc_rollout_seed_plan(fcc_rollout_users())['accounts'],'user_id')===[1,2,3],'Explicit initial exclusion wins over shared Forever ID without revoking admin access');
putenv('FCC_PARTNER_SEED_EXCLUDE_EMAILS');
$ok(!in_array(5,array_column($plan['accounts'],'user_id'),true),'Same name and referral ancestry do not grant access');
$duplicated=fcc_rollout_users();$duplicated[]=$duplicated[1];$ok(!fcc_rollout_seed_plan($duplicated)['ready'],'Ambiguous seed email blocks initialization');
$ok(!fcc_rollout_seed_plan(fcc_rollout_users(),['missing@example.test'])['ready'],'Missing explicit account blocks initialization');
$payload=function($action,$ids=[]) {$p=fcc_rollout_preview($action,$ids);return ['action'=>$action,'ids'=>$p['ids'],'extra'=>[],'revision'=>(int)fcc_rollout_control()['revision'],'fingerprint'=>$p['fingerprint'],'request_key'=>bin2hex(random_bytes(16)),'confirmation'=>'POTVRDI'];};
$identity=function(){return hash('sha256',json_encode(fcc_partner_rows('SELECT * FROM users ORDER BY user_id')));};$before=$identity();
fcc_partner_query("INSERT INTO links(link_id,user_id,type,url,settings,is_enabled,datetime) VALUES(902,2,'biolink','stable-card','{}',1,UTC_TIMESTAMP())");
fcc_partner_query('INSERT INTO users_biolinks(user_id,biolink_id) VALUES(2,902)');
fcc_partner_query("INSERT INTO fcc_business_presentations(id,user_id,link_id,created_at,updated_at) VALUES(1,2,902,UTC_TIMESTAMP(),UTC_TIMESTAMP())");
$publicToken=str_repeat('a',64);fcc_partner_query("INSERT INTO fcc_business_shares(id,presentation_id,user_id,public_token,request_key,presentation_version,created_at) VALUES(1,1,2,?,'fixture',1,UTC_TIMESTAMP())",[$publicToken]);
$input=$payload('initial');$reject(fn()=>fcc_rollout_change(5,$input),'Member cannot grant access');
$ok(fcc_rollout_change(1,$input)===4,'Admin initializes reviewed seed');$ok(fcc_rollout_change(1,$input)===4,'Replayed admin request is idempotent');
$ok(fcc_partner_enabled(2)&&fcc_partner_enabled(4)&&!fcc_partner_enabled(5)&&!fcc_partner_enabled(6),'Selected accounts use new workspace, others stay on old');
$ok(!fcc_partner_enabled(0),'Guest never inherits administrator access');
\Altum\Authentication::$user_id=0;$ok(fcc_events_enabled(),'Public calendar stays available without a logged in member');
$ok(fcc_business_enabled(2)&&fcc_webinar_enabled(2)&&!fcc_business_enabled(5)&&!fcc_webinar_enabled(5),'Managed rollout replaces hidden module pilot lists');
putenv('FCC_PARTNER_ENABLED=0');$ok(!fcc_partner_enabled(2),'Master kill switch wins');putenv('FCC_PARTNER_ENABLED=1');
$stale=$payload('grant',[5]);fcc_rollout_change(1,$payload('grant',[2]));$reject(fn()=>fcc_rollout_change(1,$stale),'Concurrent admin changes require a new review');
$bad=$payload('grant',[5]);$bad['fingerprint']=str_repeat('0',64);$reject(fn()=>fcc_rollout_change(1,$bad),'Changed target snapshot cannot be applied');
$reject(fn()=>fcc_rollout_change(1,array_replace($payload('grant',[5]),['confirmation'=>''])),'Confirmation required for batch mutation');
$reject(fn()=>fcc_rollout_preview('revoke',[1]),'Admin cannot remove inherent admin access');
fcc_partner_query('INSERT INTO fcc_partner_journey_cycles(user_id,catalog_version,policy_version,started_at) VALUES(2,?,?,UTC_TIMESTAMP())',[FCC_JP_VERSION,'old-policy']);$old=(int)database()->insert_id;
fcc_partner_query("INSERT INTO fcc_partner_journey_steps(user_id,cycle_id,position,content_json,opened_at) VALUES(2,?,1,'{}',UTC_TIMESTAMP())",[$old]);
fcc_rollout_enter(2);$cycle=fcc_j90_cycle(2);$ok((int)$cycle['id']!==$old&&fcc_partner_one('SELECT status FROM fcc_partner_journey_cycles WHERE id=?',[$old])['status']==='archived','First entry creates new cycle and archives old history');
$ok((int)fcc_partner_one('SELECT COUNT(*) n FROM fcc_partner_journey_steps WHERE cycle_id=?',[(int)$cycle['id']])['n']===0,'New education starts from the beginning');
$ok((int)fcc_partner_one('SELECT COUNT(*) n FROM fcc_partner_journey_steps WHERE cycle_id=?',[$old])['n']===1,'Prior education records stay intact');
fcc_rollout_enter(2);$ok((int)fcc_j90_cycle(2)['id']===(int)$cycle['id'],'Repeated page load does not reset education');
fcc_rollout_change(1,$payload('revoke',[2]));$ok(!fcc_partner_enabled(2)&&fcc_rollout_public_owner(2),'Revoking workspace keeps public ownership');
$ok(fcc_webinar_pro(2,true)&&!fcc_webinar_pro(2),'Published invitations retain paid validation while editor access is removed');
$ok(fcc_webinar_standard_enabled(2,true)&&!fcc_webinar_standard_enabled(2),'Standard public invitations retain access after workspace withdrawal');
$public=fcc_business_public($publicToken);$ok($public&&$public['available']&&$public['owner']['uid']===2&&str_ends_with($public['owner']['profile'],'/stable-card'),'Published business LP retains the same card, referral owner and URL after access withdrawal');
$ok(!fcc_business_pro(2),'Published page access does not restore presentation editing');
fcc_rollout_change(1,$payload('grant',[2]));fcc_rollout_enter(2);$ok((int)fcc_j90_cycle(2)['id']===(int)$cycle['id'],'Re-enrollment resumes the same new curriculum');
$ok($before===$identity(),'Identity, passwords, preferences, referrals, plan and subscription fields unchanged');
$all=$payload('all');$add(8,'future@example.test','New user');$reject(fn()=>fcc_rollout_change(1,$all),'New registration invalidates stale all-users preview');
fcc_rollout_change(1,$payload('all'));$ok(fcc_partner_enabled(5)&&fcc_partner_enabled(8),'Reviewed all-users batch includes current active accounts');$add(9,'later@example.test','Later');$ok(fcc_partner_enabled(9),'Future active accounts receive the same new workspace');
$ok(fcc_rollout_all_enabled(),'All-users activation is a persistent audited policy');
$add(10,'pending@example.test','Pending',0,0);$ok(!fcc_partner_enabled(10),'Pending accounts remain outside the workspace');
fcc_partner_query('UPDATE users SET status=1 WHERE user_id=10');$ok(fcc_partner_enabled(10),'Approval gives future collaborators access automatically');
$ok(!fcc_partner_enabled(6)&&!fcc_partner_enabled(7),'Global activation cannot bypass disabled account status');
$unchanged=$identity();
fcc_partner_query('INSERT INTO fcc_partner_journey_cycles(user_id,catalog_version,policy_version,started_at) VALUES(9,?,?,UTC_TIMESTAMP())',[FCC_JP_V7_VERSION,'existing-policy']);$existing=(int)database()->insert_id;
fcc_partner_query("INSERT INTO fcc_partner_journey_steps(user_id,cycle_id,position,content_json,opened_at) VALUES(9,?,1,'{\"draft\":\"keep\"}',UTC_TIMESTAMP())",[$existing]);
$progressBefore=fcc_partner_rows('SELECT * FROM fcc_partner_journey_steps WHERE user_id=9');
fcc_rollout_enter(9);fcc_rollout_enter(9);
$ok((int)fcc_j90_cycle(9)['id']===$existing&&fcc_j90_cycle(9)['status']==='active','Global first entry resumes the existing curriculum');
$ok($progressBefore===fcc_partner_rows('SELECT * FROM fcc_partner_journey_steps WHERE user_id=9'),'Global activation preserves completed work and drafts exactly');
$ok((int)fcc_partner_one('SELECT education_cycle_id FROM fcc_partner_rollout_access WHERE user_id=9')['education_cycle_id']===$existing,'Existing progress is linked to the new workspace');
fcc_rollout_enter(10);$new=fcc_j90_cycle(10);fcc_rollout_enter(10);
$ok($new&&$new['catalog_version']===FCC_JP_VERSION&&(int)fcc_j90_cycle(10)['id']===(int)$new['id'],'New collaborators get one current education cycle');
$ok($unchanged===$identity(),'Global entry does not alter identity, plans, subscriptions or preferences');
fcc_rollout_change(1,$payload('revoke',[9]));$ok(!fcc_partner_enabled(9)&&fcc_rollout_public_owner(9),'Explicit emergency withdrawal overrides the global policy and preserves published pages');
fcc_rollout_change(1,$payload('grant',[9]));fcc_rollout_enter(9);$ok((int)fcc_j90_cycle(9)['id']===$existing,'Restoring access never resets progress');
putenv('FCC_PARTNER_ENABLED=0');$ok(!fcc_partner_enabled(10),'Master switch also overrides global activation');putenv('FCC_PARTNER_ENABLED=1');
fcc_partner_query('UPDATE users SET status=2 WHERE user_id=2');$ok(!fcc_rollout_public_owner(2),'Suspended owner cannot retain public access');
$ok((int)fcc_partner_one('SELECT COUNT(*) n FROM fcc_partner_rollout_audit')['n']===7,'Every committed batch has one audit record');
echo json_encode(['status'=>'PASS','checks'=>$checks],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE).PHP_EOL;
