<?php defined('ALTUMCODE') || die();
$t=$data->team; $p=$t['profile']; $subject=$p?(int)$p['user_id']:$uid;
$outreach=$p&&$subject!==(int)($t['shared_primary']['user_id']??$uid)?fcc_team_outreach_page($uid,$subject):null;
if($outreach&&($message=fcc_cc_outreach_message($uid,$subject,(int)($_GET['cc_event']??0))))$outreach['templates']['checkin']=$message;
\Altum\Event::add_content('<link rel="stylesheet" href="'.ASSETS_FULL_URL.'css/fcc-team.css?v='.filemtime(ASSETS_PATH.'css/fcc-team.css').'">','fcc_styles');
?>
<div class="ft-header"><div><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('LJUDI I ZAJEDNIČKI NAPREDAK'), ENT_QUOTES, 'UTF-8') ?></span><h1><?= $p?$h($p['name']):fcc_t('Moj tim') ?></h1><p class="fp-lead"><?= $p?fcc_t('Napredak, rezultati i vaš sljedeći dogovor.'):fcc_t('Tvoja linija, podrška i mali uspjesi na jednom mjestu.') ?></p></div><div class="fp-filter-row"><a class="fp-button fp-button-outline" href="<?= url('partner') ?>"><?= htmlspecialchars(fcc_t('Moj današnji korak'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-link" href="<?= url('partner/share?type=webinar') ?>"><?= htmlspecialchars(fcc_t('Pozovi na webinar →'), ENT_QUOTES, 'UTF-8') ?></a></div></div>
<?php if(!$t['ready']): ?><section class="fp-panel"><p><?= htmlspecialchars(fcc_t('Timsko povezivanje još nije uključeno.'), ENT_QUOTES, 'UTF-8') ?></p></section><?php return; endif ?>
<?php if($t['shared_primary']): ?><div class="ft-shared-account"><strong><?= htmlspecialchars(fcc_t('Zajednička struktura'), ENT_QUOTES, 'UTF-8') ?></strong><span><?= htmlspecialchars(fcc_t('Pregled dijeliš s glavnim računom'), ENT_QUOTES, 'UTF-8') ?> <?= $h($t['shared_primary']['name']) ?><?= htmlspecialchars(fcc_t('. Suradnicima se prikazuju njegovi kontaktni podaci.'), ENT_QUOTES, 'UTF-8') ?></span></div><?php endif ?>
<?php if($p): ?><a class="fp-link" href="<?= url('partner/team') ?>"><?= htmlspecialchars(fcc_t('← Moj tim'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?>
<?php $sponsor=$p?$p['sponsor']:$t['sponsor']; $firstManager=$p?$p['first_manager']:$t['first_manager']; ?>
<div class="ft-intro">
 <?php if($p || $sponsor): ?>
 <section class="ft-sponsor">
  <?php if($p): ?>
   <span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('KONTAKT S TVOJIM SURADNIKOM'), ENT_QUOTES, 'UTF-8') ?></span><h2><?= $h($p['name']) ?></h2><p><?= htmlspecialchars(fcc_t('Jedan osobni razgovor može biti koristan sljedeći korak.'), ENT_QUOTES, 'UTF-8') ?></p>
   <?php if($p['phone']): ?><a class="ft-phone" href="tel:<?= $h($p['phone']) ?>"><?= $h($p['phone']) ?></a><div class="fp-filter-row"><a class="fp-button fp-button-light" href="<?= url('partner/team'.($p?'?member='.$subject:'').'#team-work') ?>"><?= htmlspecialchars(fcc_t('Napiši WhatsApp poruku'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-link" aria-label="<?= $h(fcc_t('Nazovi ').$p['name']) ?>" href="tel:<?= $h($p['phone']) ?>"><?= htmlspecialchars(fcc_t('Nazovi'), ENT_QUOTES, 'UTF-8') ?></a></div><?php else: ?><p><?= htmlspecialchars(fcc_t('Poslovni broj još nije dostupan. Poruku možeš pripremiti i kopirati za osobno javljanje.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button fp-button-light" href="<?= url('partner/team'.($p?'?member='.$subject:'').'#team-work') ?>"><?= htmlspecialchars(fcc_t('Pripremi poruku'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?>
  <?php elseif($sponsor): ?>
   <?php $supportPeople=[[$sponsor,$sponsor['is_manager']?fcc_t('IZRAVNI SPONZOR I PRVI MENADŽER'):fcc_t('IZRAVNI SPONZOR')]];
   if($firstManager&&$firstManager['user_id']!==$sponsor['user_id']) $supportPeople[]=[$firstManager,fcc_t('PRVI MENADŽER U LINIJI')];
   foreach($supportPeople as [$person,$role]): ?>
   <div class="ft-support-person">
    <span class="fp-eyebrow"><?= $h($role) ?></span>
    <h2><?= $h($person['name']) ?></h2><p><?= $person['is_manager']?fcc_t('Podrška za razvoj i zajednički rad'):fcc_t('Podrška za tvoj sljedeći korak') ?></p>
    <?php if($person['phone']): $message=fcc_t('Bok! Trebam pomoć oko svojeg sljedećeg koraka u FCC-u. Možemo li dogovoriti kratak razgovor?'); ?>
    <a class="ft-phone" href="tel:<?= $h($person['phone']) ?>"><?= $h($person['phone']) ?></a>
    <div class="fp-filter-row"><a class="fp-button fp-button-light" target="_blank" rel="noopener" aria-label="<?= $h(fcc_t('Otvori WhatsApp za ').$person['name']) ?>" href="https://wa.me/<?= $h(preg_replace('/\D/','',$person['phone'])) ?>?text=<?= rawurlencode($message) ?>"><?= htmlspecialchars(fcc_t('Otvori WhatsApp'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-link" aria-label="<?= $h(fcc_t('Nazovi ').$person['name']) ?>" href="tel:<?= $h($person['phone']) ?>"><?= htmlspecialchars(fcc_t('Nazovi'), ENT_QUOTES, 'UTF-8') ?></a></div>
    <?php else: ?><p><?= htmlspecialchars(fcc_t('Poslovni telefon još nije dostupan. Pomoć možete dogovoriti u rubrici Zajednički rad.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
   </div>
   <?php endforeach ?>
   <?php if(!$firstManager&&!$sponsor['is_manager']): ?><p class="ft-manager-pending"><?= htmlspecialchars(fcc_t('Prvi menadžer prikazat će se nakon potvrde ostatka tvoje linije.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
   <?php if(!$p): ?><a class="fp-link" href="<?= url('partner/team'.($p?'?member='.$subject:'').'#team-work') ?>"><?= htmlspecialchars(fcc_t('Zatraži pomoć →'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?>
  <?php endif ?>
 </section>
 <?php endif ?>
 <section class="fp-panel ft-info">
  <?php if($p): ?><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('INFORMATIVNI PROFIL'), ENT_QUOTES, 'UTF-8') ?></span><h2><?= $h($p['name']) ?></h2><p><?= htmlspecialchars(fcc_t('Forever ID:'), ENT_QUOTES, 'UTF-8') ?> <?= $h($p['fbo_id']) ?></p><?php if($sponsor): ?><p><?= htmlspecialchars(fcc_t('Izravni sponzor:'), ENT_QUOTES, 'UTF-8') ?> <strong><?= $h($sponsor['name']) ?></strong><?php if($firstManager&&$firstManager['user_id']!==$sponsor['user_id']): ?><br><?= htmlspecialchars(fcc_t('Prvi menadžer:'), ENT_QUOTES, 'UTF-8') ?> <?= $h($firstManager['name']) ?><?php endif ?></p><?php endif ?><p><?= htmlspecialchars(fcc_t('Prikaz obuhvaća napredak i zbirne rezultate. Zajednički dogovori dostupni su njihovim sudionicima.'), ENT_QUOTES, 'UTF-8') ?></p>
  <?php else: ?><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('TVOJA LINIJA'), ENT_QUOTES, 'UTF-8') ?></span><h2><?= (int)$t['total'] ?> <?= $t['total']===1?fcc_t('suradnik u pregledu'):fcc_t('suradnika u pregledu') ?></h2><p><?= $t['full_structure']?fcc_t('Vidiš cijelu povezanu strukturu, uključujući menadžere i njihove grane.'):fcc_t('Vidiš svoju povezanu liniju do prvog menadžera.') ?> <?= htmlspecialchars(fcc_t('Zajednički Forever ID prikazuje se jednom. Obavijesti o uspjesima ostaju vezane uz izravnog sponzora.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-link" href="<?= url('partner/notifications') ?>"><?= htmlspecialchars(fcc_t('Obavijesti i postavke →'), ENT_QUOTES, 'UTF-8') ?></a>
  <?php endif ?>
 </section>
</div>
<?php if($p): $m=$p['metrics']; ?>

<div class="ft-metrics">
 <?php foreach([[fcc_t('Završeni koraci'),$m['steps']],[fcc_t('Potvrđena slanja'),$m['sent']],[fcc_t('Kvalificirani klikovi'),$m['clicks']],[fcc_t('Potvrđene prijave'),$m['verified_registrations']]] as [$label,$count]): ?><div><span><?= $h($label) ?></span><strong><?= (int)$count ?></strong><small><?= htmlspecialchars(fcc_t('Posljednjih'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$m['days'] ?> <?= htmlspecialchars(fcc_t('dana'), ENT_QUOTES, 'UTF-8') ?></small></div><?php endforeach ?>
</div>
<section class="fp-panel"><div class="fp-section-title"><h2><?= htmlspecialchars(fcc_t('Napredak u programu Moj put'), ENT_QUOTES, 'UTF-8') ?></h2><strong><?= (int)$m['progress'] ?> <?= htmlspecialchars('/ 90 koraka', ENT_QUOTES, 'UTF-8') ?></strong></div><progress class="ft-progress" value="<?= min(90,(int)$m['progress']) ?>" max="90" aria-label="<?= htmlspecialchars(fcc_t('Završeni koraci'), ENT_QUOTES, 'UTF-8') ?>"></progress><p><?= $m['cycle_status']==='not_started'?fcc_t('Program još nije započet.'):($m['paused_until']>=fcc_partner_today()?'Pauza do '.$h($m['paused_until']):fcc_t('Napredak u trenutačnom ciklusu.')) ?></p>
 <?php if(count($m['account_progress'])>1): ?><div class="ft-account-progress"><?php foreach($m['account_progress'] as $account): ?><p><?= $h($account['name']) ?>: <?= (int)$account['progress'] ?> <?= htmlspecialchars('/ 90 koraka', ENT_QUOTES, 'UTF-8') ?></p><?php endforeach ?></div><small><?= htmlspecialchars(fcc_t('Koraci programa pripadaju pojedinom računu. Statistike slanja i prijava obuhvaćaju potvrđene zajedničke račune.'), ENT_QUOTES, 'UTF-8') ?></small><?php endif ?></section>
<?php if($m['cc']&&!$m['cc']['stale']&&$m['cc']['personal_delta']!==null): ?><p class="fp-muted"><?= $h(fcc_cc_t('delta',['{cc}'=>fcc_cc_number($m['cc']['personal_delta'],true)])) ?></p><?php endif ?>
<section class="fp-panel ft-cc-panel"><div class="fp-section-title"><h2><?= htmlspecialchars(fcc_t('Bodovi iz FLP360'), ENT_QUOTES, 'UTF-8') ?></h2><?php if($m['cc']): ?><span class="ft-status"><?= $h(substr($m['cc']['period_month'],0,7)) ?></span><?php endif ?></div>
 <?php if($m['cc']): ?><div class="ft-cc-values"><?php foreach(fcc_localize_copy(['personal_cc'=>fcc_t('Osobni CC'),'total_cc'=>fcc_t('Ukupni CC'),'total_active_cc'=>fcc_t('Aktivni CC')]) as $field=>$label): ?><div><span><?= $h($label) ?></span><strong><?= $m['cc'][$field]===null?fcc_t('Nema podatka'):$h(number_format($m['cc'][$field],3,',','.')) ?></strong></div><?php endforeach ?></div><p class="fp-muted"><?= htmlspecialchars(fcc_t('Sinkronizirano'), ENT_QUOTES, 'UTF-8') ?> <?= $h($m['cc']['updated_at']) ?> <?= htmlspecialchars(fcc_t('UTC.'), ENT_QUOTES, 'UTF-8') ?> <?= $m['cc']['stale']?fcc_t('Stariji podatak, provjeri nakon sljedeće sinkronizacije.'):'' ?></p><?php else: ?><p><?= htmlspecialchars(fcc_t('CC podatak još nije dostupan iz sinkronizacije.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?><small class="ft-source-note"><?= htmlspecialchars(fcc_t('CC vrijedi za navedeni Forever ID i mjesec. Ne potvrđuje kupnju preko određene FCC poveznice. Ukupni CC različitih dubina mogu se preklapati.'), ENT_QUOTES, 'UTF-8') ?></small></section>
<section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Poveznice i pozivi'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Pripremljeno:'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$m['prepared'] ?><?= htmlspecialchars(fcc_t('. Slanja koja je potvrdio suradnik:'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$m['sent'] ?><?= htmlspecialchars(fcc_t('. Zaprimljene prijave:'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$m['registrations'] ?><?= htmlspecialchars(fcc_t(', od toga potvrđen email:'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$m['verified_registrations'] ?>.</p>
 <?php if(!$p['links']): ?><p class="fp-muted"><?= htmlspecialchars(fcc_t('Još nema zabilježenih poziva za prikaz.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
 <?php foreach($p['links'] as $link): ?><div class="ft-link-row"><div><strong><?= $h($link['title']) ?></strong><small><?= $link['kind']==='business'?fcc_t('Prezentacija'):fcc_t('Webinar') ?> · <?= $h($link['prepared_at']) ?> <?= htmlspecialchars(fcc_t('UTC ·'), ENT_QUOTES, 'UTF-8') ?> <?= $link['sent_at']?fcc_t('Slanje je potvrdio suradnik'):fcc_t('Poziv je pripremljen') ?></small></div><span><?= (int)$link['registrations'] ?> <?= $link['kind']==='business'?'upita':'prijava' ?></span></div><?php endforeach ?>
 <small class="ft-source-note"><?= htmlspecialchars(fcc_t('Prikazano je do 20 najnovijih poziva i prezentacija. Otvaranje WhatsAppa nije potvrda slanja. Prijava ne potvrđuje dolazak na webinar.'), ENT_QUOTES, 'UTF-8') ?></small></section>
<?php else: ?>
<section class="fp-panel ft-roster">
 <div class="fp-section-title"><h2><?= htmlspecialchars(fcc_t('Suradnici u tvojoj liniji'), ENT_QUOTES, 'UTF-8') ?></h2><span><?= (int)$t['total'] ?></span></div>
 <form method="get" class="ft-filters"><input type="hidden" name="cc_filter" value="<?= $h($_GET['cc_filter']??'') ?>"><label><?= htmlspecialchars(fcc_t('Pronađi suradnika'), ENT_QUOTES, 'UTF-8') ?><input type="search" name="q" value="<?= $h($t['search']) ?>" placeholder="<?= htmlspecialchars(fcc_t('Ime ili Forever ID'), ENT_QUOTES, 'UTF-8') ?>"></label><label><?= htmlspecialchars(fcc_t('Dubina'), ENT_QUOTES, 'UTF-8') ?><select name="depth" data-is-not-custom-select><option value="0"><?= htmlspecialchars(fcc_t('Cijela dopuštena linija'), ENT_QUOTES, 'UTF-8') ?></option><?php for($i=1;$i<=10;$i++): ?><option value="<?= $i ?>" <?= $t['depth']===$i?'selected':'' ?>><?= $i===1?fcc_t('Izravni suradnici'):fcc_t('Dubina ').$i ?></option><?php endfor ?></select></label><label><?= htmlspecialchars(fcc_t('Razdoblje'), ENT_QUOTES, 'UTF-8') ?><select name="days" data-is-not-custom-select><?php foreach([7,30] as $d): ?><option value="<?= $d ?>" <?= $t['days']===$d?'selected':'' ?>><?= $d ?> <?= htmlspecialchars(fcc_t('dana'), ENT_QUOTES, 'UTF-8') ?></option><?php endforeach ?></select></label><button class="fp-button"><?= htmlspecialchars(fcc_t('Prikaži'), ENT_QUOTES, 'UTF-8') ?></button></form>
 <?php if(!$t['members']): ?><div class="ft-empty"><h3><?= $t['search']?fcc_t('Nema rezultata za ovu pretragu.'):fcc_t('Tvoj tim čeka prvo povezivanje.') ?></h3><p><?= htmlspecialchars(fcc_t('Nakon potvrde sponzora povezani suradnici i njihov napredak pojavit će se ovdje.'), ENT_QUOTES, 'UTF-8') ?></p></div><?php endif ?>
 <div class="fp-filter-row ft-quick-filters"><?php foreach([''=>'filter_all','growth'=>'filter_growth','active'=>'filter_active','rank'=>'filter_rank'] as $value=>$label): ?><a class="fp-button fp-button-outline" <?= ($_GET['cc_filter']??'')===$value?'aria-current="page"':'' ?> href="<?= url('partner/team?'.http_build_query(['q'=>$t['search'],'depth'=>$t['depth'],'days'=>$t['days'],'cc_filter'=>$value])) ?>"><?= $h(fcc_cc_t($label)) ?></a><?php endforeach ?></div>
 <?php if($t['members']): ?><div class="ft-roster-head" aria-hidden="true"><span><?= $h(fcc_t('Suradnik')) ?></span><span><?= $h(fcc_t('Aktivnost')) ?></span><span><?= $h(fcc_t('CC bodovi')) ?></span></div><?php endif ?>
 <div class="ft-member-list">
 <?php foreach($t['members'] as $member): $m=$member['metrics']; $memberCc=$m['cc']; ?>
  <a class="ft-member" href="<?= url('partner/team?member='.(int)$member['user_id'].'&days='.$t['days']) ?>">
   <div class="ft-person"><span class="fp-contact-initial" aria-hidden="true"><?= $h(mb_substr($member['name'],0,1)) ?></span><div>
    <h3><?= $h($member['name']) ?></h3>
    <small><?= $member['depth']===1?fcc_t('Izravni suradnik'):fcc_t('Dubina ').(int)$member['depth'] ?> · <?= $member['manager']?fcc_t('Menadžer · '):'' ?><?= $h(fcc_t('Sponzor:')) ?> <?= $h($member['sponsor_name']) ?></small>
    <small class="ft-member-identity"><?= $h($member['fbo_id']) ?><?= count($member['account_ids'])>1?fcc_t(' · Zajednički račun'):'' ?></small>
   </div></div>
   <div class="ft-member-numbers">
    <span><b><?= (int)$m['progress'] ?>/90</b><?= $h(fcc_t('koraka')) ?></span>
    <span><b><?= (int)$m['sent'] ?></b><?= $h(fcc_t('slanja')) ?></span>
    <span><b><?= (int)$m['clicks'] ?></b><?= $h(fcc_t('klikova')) ?></span>
    <span><b><?= (int)$m['verified_registrations'] ?></b><?= $h(fcc_t('prijava')) ?></span>
   </div>
   <div class="ft-member-cc">
    <?php if($memberCc): ?>
     <div class="ft-cc-pair"><span><?= $h(fcc_t('Osobni CC')) ?><b><?= $memberCc['personal_cc']===null?fcc_t('Nema podatka'):$h(number_format($memberCc['personal_cc'],3,',','.')) ?></b></span><span><?= $h(fcc_t('Ukupni CC')) ?><b><?= $memberCc['total_cc']===null?fcc_t('Nema podatka'):$h(number_format($memberCc['total_cc'],3,',','.')) ?></b></span></div>
     <div class="ft-cc-state">
      <small><?= $h(substr($memberCc['period_month'],0,7)) ?><?= $memberCc['stale']?fcc_t(' · Stariji podatak'):'' ?></small>
      <?php if(!$memberCc['stale']&&!empty($memberCc['is_4cc_active'])): ?><small class="ft-cc-active"><?= $h(fcc_cc_t('activity')) ?> ✓</small><?php endif ?>
      <?php if(!$memberCc['stale']&&$memberCc['personal_delta']!==null): ?><small class="ft-cc-delta"><?= $h(fcc_cc_t('delta',['{cc}'=>fcc_cc_number($memberCc['personal_delta'],true)])) ?></small><?php endif ?>
     </div>
    <?php else: ?><span class="ft-cc-unavailable"><?= $h(fcc_t('CC još nije dostupan')) ?></span><?php endif ?>
   </div>
   <span class="ft-member-arrow" aria-hidden="true">→</span>
  </a>
 <?php endforeach ?>
 </div>
 <div class="fp-filter-row"><?php if($t['page']>1): ?><a class="fp-link" href="<?= url('partner/team?'.http_build_query(['q'=>$t['search'],'depth'=>$t['depth'],'days'=>$t['days'],'cc_filter'=>$_GET['cc_filter']??'','page'=>$t['page']-1])) ?>"><?= htmlspecialchars(fcc_t('← Prethodni'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?><?php if($t['page']*20<$t['total']): ?><a class="fp-link" href="<?= url('partner/team?'.http_build_query(['q'=>$t['search'],'depth'=>$t['depth'],'days'=>$t['days'],'cc_filter'=>$_GET['cc_filter']??'','page'=>$t['page']+1])) ?>"><?= htmlspecialchars(fcc_t('Sljedeći →'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?></div>
</section>
<?php endif ?>
<section class="fp-panel" id="team-work"><div class="fp-section-title"><h2><?= $p?fcc_t('Podrška i osobno javljanje'):fcc_t('Zajednički rad') ?></h2><span class="fp-muted"><?= htmlspecialchars(fcc_t('Razgovor, jedan korak i nastavak'), ENT_QUOTES, 'UTF-8') ?></span></div>
 <?php if($outreach)require THEME_PATH.'views/partner/team-outreach.php'; ?>
 <?php if(!$p)require THEME_PATH.'views/partner/team-outreach-due.php'; ?>
 <?php if(!$p&&$t['work_inbox']): ?><div class="ft-work-inbox"><h3><?= htmlspecialchars(fcc_t('Suradnici čekaju zajednički korak'), ENT_QUOTES, 'UTF-8') ?></h3><?php foreach($t['work_inbox'] as $incoming): ?><a class="ft-member" href="<?= url('partner/team?member='.(int)$incoming['member_user_id'].'#team-work') ?>"><div><strong><?= $h($incoming['member_name']) ?></strong><p><?= $h($incoming['title']) ?></p><small><?= $incoming['due_date']?fcc_t('Sljedeće javljanje: ').$h($incoming['due_date']):fcc_t('Dogovorite termin') ?></small></div><span aria-hidden="true">→</span></a><?php endforeach ?></div><?php endif ?>
 <?php if($subject!==$uid||$t['upline']): ?>
 <details <?= !$p&&!$t['work']?'open':'' ?>><summary><?= htmlspecialchars(fcc_t('Novi dogovor ili zahtjev za pomoć'), ENT_QUOTES, 'UTF-8') ?></summary><form method="post" class="fp-form ft-work-form"><?= $token ?><input type="hidden" name="action" value="team_work"><input type="hidden" name="team_operation" value="create"><input type="hidden" name="member_id" value="<?= $subject ?>"><?= $request ?>
 <label><?= htmlspecialchars(fcc_t('Tema'), ENT_QUOTES, 'UTF-8') ?><input name="title" maxlength="180" required placeholder="<?= htmlspecialchars(fcc_t('Npr. priprema prvog poziva na webinar'), ENT_QUOTES, 'UTF-8') ?>"></label>
 <div class="fp-form-grid"><label><?= htmlspecialchars(fcc_t('Sljedeće javljanje'), ENT_QUOTES, 'UTF-8') ?><input name="due_date" type="date"></label>
 <?php if($subject===$uid): ?><label><?= htmlspecialchars(fcc_t('S kim želiš raditi?'), ENT_QUOTES, 'UTF-8') ?><select name="collaborator_id" data-is-not-custom-select><?php foreach($t['upline'] as $person): ?><option value="<?= (int)$person['user_id'] ?>"><?= $h($person['name']) ?></option><?php endforeach ?></select></label><?php else: ?><p><?= htmlspecialchars(fcc_t('Dogovor između tebe i suradnika'), ENT_QUOTES, 'UTF-8') ?> <?= $h($p['name']) ?>.</p><?php endif ?></div>
 <input type="hidden" name="assignee_id" value="<?= $subject ?>"><button class="fp-button"><?= htmlspecialchars(fcc_t('Spremi dogovor'), ENT_QUOTES, 'UTF-8') ?></button></form></details>
 <?php else: ?><p><?= htmlspecialchars(fcc_t('Nakon povezivanja sponzora ovdje možeš zatražiti pomoć i dogovoriti sljedeći korak.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
 <?php foreach($t['work'] as $work): ?>
 <article class="ft-work"><div class="fp-section-title"><h3><?= $h($work['title']) ?></h3><span class="ft-status"><?= ['open'=>'Otvoreno','in_progress'=>fcc_t('U tijeku'),'done'=>fcc_t('Dovršeno')][$work['status']] ?></span></div><p><?= $h($work['collaborator_name']) ?> <?= htmlspecialchars(fcc_t('· Odgovorna osoba:'), ENT_QUOTES, 'UTF-8') ?> <?= $h($work['assignee_name']) ?><?php if($work['due_date']): ?> · <?= $h($work['due_date']) ?><?php endif ?></p>
 <details><summary><?= htmlspecialchars(fcc_t('Dogovor i bilješke'), ENT_QUOTES, 'UTF-8') ?></summary><form method="post" class="ft-filters"><?= $token ?><input type="hidden" name="action" value="team_work"><input type="hidden" name="team_operation" value="update"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><input type="hidden" name="version" value="<?= (int)$work['version'] ?>"><input type="hidden" name="request_key" value="<?= bin2hex(random_bytes(16)) ?>">
 <label><?= htmlspecialchars(fcc_t('Status'), ENT_QUOTES, 'UTF-8') ?><select name="status" data-is-not-custom-select><?php foreach(fcc_localize_copy(['open'=>'Otvoreno','in_progress'=>fcc_t('U tijeku'),'done'=>fcc_t('Dovršeno')]) as $value=>$label): ?><option value="<?= $value ?>" <?= $value===$work['status']?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label><label><?= htmlspecialchars(fcc_t('Datum'), ENT_QUOTES, 'UTF-8') ?><input type="date" name="due_date" value="<?= $h($work['due_date']??'') ?>"></label><label><?= htmlspecialchars(fcc_t('Odgovorna osoba'), ENT_QUOTES, 'UTF-8') ?><select name="assignee_id" data-is-not-custom-select><option value="<?= (int)$work['member_user_id'] ?>" <?= $work['assignee_user_id']===$work['member_user_id']?'selected':'' ?>><?= htmlspecialchars(fcc_t('Suradnik'), ENT_QUOTES, 'UTF-8') ?></option><option value="<?= (int)$work['collaborator_user_id'] ?>" <?= $work['assignee_user_id']===$work['collaborator_user_id']?'selected':'' ?>><?= $h($work['collaborator_name']) ?></option></select></label><button class="fp-button fp-button-outline"><?= htmlspecialchars(fcc_t('Spremi'), ENT_QUOTES, 'UTF-8') ?></button></form>
 <?php if($work['shared_contact']): ?><div class="ft-shared"><strong><?= htmlspecialchars(fcc_t('Kontakt podijeljen za ovaj dogovor'), ENT_QUOTES, 'UTF-8') ?></strong><p><?= $h($work['shared_contact']['name']) ?> · <?= $h($work['shared_contact']['phone']) ?> · <?= $h($work['shared_contact']['email']) ?></p></div><?php endif ?>
 <?php if((int)$work['member_user_id']===$uid): ?><form method="post" class="fp-form"><?= $token ?><input type="hidden" name="action" value="team_work"><input type="hidden" name="team_operation" value="contact"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><input type="hidden" name="version" value="<?= (int)$work['version'] ?>"><input type="hidden" name="request_key" value="<?= bin2hex(random_bytes(16)) ?>"><label><?= htmlspecialchars(fcc_t('Podijeli ime i kontaktne podatke za ovaj dogovor'), ENT_QUOTES, 'UTF-8') ?><select name="contact_id" data-is-not-custom-select><option value="0"><?= htmlspecialchars(fcc_t('Bez podijeljenog kontakta'), ENT_QUOTES, 'UTF-8') ?></option><?php foreach(fcc_partner_rows("SELECT id,name FROM fcc_partner_contacts WHERE user_id=? AND contact_permission<>'do_not_contact' ORDER BY name",[$uid]) as $contact): ?><option value="<?= (int)$contact['id'] ?>" <?= (int)$work['shared_contact_id']===(int)$contact['id']?'selected':'' ?>><?= $h($contact['name']) ?></option><?php endforeach ?></select></label><button class="fp-button fp-button-outline"><?= htmlspecialchars(fcc_t('Spremi dijeljenje'), ENT_QUOTES, 'UTF-8') ?></button></form><?php endif ?>
 <?php foreach($work['notes'] as $note): ?><div class="ft-note"><small><?= $h($note['name']) ?> · <?= $h($note['created_at']) ?> <?= htmlspecialchars(fcc_t('UTC'), ENT_QUOTES, 'UTF-8') ?></small><p><?= nl2br($h($note['body'])) ?></p></div><?php endforeach ?>
 <form method="post" class="fp-form"><?= $token ?><input type="hidden" name="action" value="team_work"><input type="hidden" name="team_operation" value="note"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><input type="hidden" name="request_key" value="<?= bin2hex(random_bytes(16)) ?>"><label><?= htmlspecialchars(fcc_t('Zajednička bilješka'), ENT_QUOTES, 'UTF-8') ?><textarea name="body" rows="2" maxlength="1500" required placeholder="<?= htmlspecialchars(fcc_t('Što ste dogovorili i koji je sljedeći korak?'), ENT_QUOTES, 'UTF-8') ?>"></textarea></label><button class="fp-button fp-button-outline"><?= htmlspecialchars(fcc_t('Dodaj bilješku'), ENT_QUOTES, 'UTF-8') ?></button></form></details>
 </article><?php endforeach ?>
</section>
<?php if(!$p&&$t['contact']): ?><details class="fp-panel"><summary><?= htmlspecialchars(fcc_t('Moj poslovni kontakt za suradnike'), ENT_QUOTES, 'UTF-8') ?></summary><form method="post" class="fp-form"><?= $token ?><input type="hidden" name="action" value="team_contact"><input type="hidden" name="team_version" value="<?= (int)$t['contact']['version'] ?>"><label><?= htmlspecialchars(fcc_t('Telefon'), ENT_QUOTES, 'UTF-8') ?><input type="tel" name="team_phone" value="<?= $h($t['contact']['phone']) ?>" placeholder="+385…" maxlength="30"></label><label class="fp-check-label"><input type="checkbox" name="team_contact_confirmed" value="1" <?= $t['contact']['contact_confirmed']?'checked':'' ?>> <?= htmlspecialchars(fcc_t('Dopuštam prikaz ovog poslovnog telefona povezanim suradnicima'), ENT_QUOTES, 'UTF-8') ?></label><button class="fp-button"><?= htmlspecialchars(fcc_t('Spremi kontakt'), ENT_QUOTES, 'UTF-8') ?></button></form></details><?php endif ?>
