<?php
require dirname(__DIR__).'/local/sponsor-team-fixtures.php';
$r=[];$checks=[];
$ok=function($v,$label)use(&$checks){if(!$v)throw new RuntimeException($label);$checks[]=$label;};
$reject=function($fn,$label)use($ok){try{$fn();}catch(InvalidArgumentException $e){$ok(true,$label);return;}throw new RuntimeException($label);};
try {
 $r=fcc_team_qa_create();$actor=$r['sponsor'];$member=$r['member'];
 fcc_team_qa_assign($member,$actor,false,['team_phone'=>'+385990000002','team_contact_confirmed'=>1]);
 $target=fcc_team_outreach_target($actor,$member);$ok($target['phone']==='+385990000002','Recipient is the selected member, not their sponsor');
 $base=['member_id'=>$member,'request_key'=>bin2hex(random_bytes(16)),'purpose'=>'checkin','message'=>"Bok čćžđš! & + ? <tekst>\n\nhttps://forevercard.club/vip-edukacija",'due_date'=>fcc_partner_today(),'contact_stamp'=>$target['contact_stamp']];
 $call=function($op,$row=null,$extra=[])use($actor,$base){return fcc_team_outreach_mutate($actor,array_merge($base,$row?['draft_id'=>$row['id'],'version'=>$row['version'],'message'=>$row['message']]:[],['operation'=>$op],$extra));};
 $saved=$call('save')['draft'];$ok(!$saved['opened_at']&&!$saved['sent_self_reported_at'],'Preparation has no send or open claim');
 $same=$call('save')['draft'];$ok($same['id']===$saved['id'],'Retry does not create duplicate draft');$saved=$same;
 $reject(fn()=>$call('confirm',$saved),'Cannot confirm a draft that was never opened');
 $reject(fn()=>$call('open',$saved,['contact_stamp'=>'wrong']),'Stale recipient phone is rejected');
 $opened=$call('open',$saved);parse_str(parse_url($opened['whatsapp_url'],PHP_URL_QUERY),$query);
 $ok(parse_url($opened['whatsapp_url'],PHP_URL_PATH)==='/385990000002'&&$query['text']===$base['message'],'WhatsApp preserves complete Unicode text, newlines and URL for the correct phone');
 $row=$opened['draft'];$ok($row['opened_at']&&!$row['sent_self_reported_at'],'WhatsApp opening is not reported as sent');
 $ok(count(fcc_team_outreach_history($actor,0,true))===1,'Opening with chosen date produces own due reminder');
 $context=fcc_team_outreach_context($actor);$ok(!$context['recent'][0]['sent_self_reported_at']&&$context['recent'][0]['whatsapp_opened_at'],'Coach sees opening without claiming delivery');
 $ok(!str_contains(json_encode($context),'+385'),'Coach context excludes telephone numbers');
 $ok(fcc_team_outreach_history($r['manager'],$member)===[],'Another ancestor cannot read personal outreach');
 $edit=$call('save',$row,['message'=>'Drugi tekst'])['draft'];
 $ok(!$edit['opened_at']&&$edit['id']!==$row['id'],'Editing an opened message creates a new unopen draft');
 $old=fcc_partner_one('SELECT message,opened_at FROM fcc_team_outreach WHERE id=?',[$row['id']]);$ok($old['message']===$base['message']&&$old['opened_at'],'Original opened text and evidence stay in history');
 $reject(fn()=>$call('confirm',$edit),'Edited unopen message cannot be claimed sent');
 $row=$call('open',$edit,['message'=>'Drugi tekst'])['draft'];
 $reject(fn()=>$call('save',$edit),'Stale version cannot overwrite newer message');
 $row=$call('confirm',$row)['draft'];$ok((bool)$row['sent_self_reported_at'],'Only explicit confirmation records self-reported sending');
 $reject(fn()=>$call('save',$row,['message'=>'overwrite']),'Confirmed message remains an immutable snapshot');
 $row=$call('followup',$row,['due_date'=>date('Y-m-d',time()+86400)])['draft'];$dueIds=array_column(fcc_team_outreach_history($actor,0,true),'id');$ok(!in_array($row['id'],$dueIds),'Future reminders stay out of today');
 $row=$call('close',$row,['outcome'=>'Dogovoren pregled FCC-a'])['draft'];$ok((bool)$row['closed_at'],'Followup can be closed with sender outcome');
 $reject(fn()=>fcc_team_outreach_mutate($r['other'],$base+['operation'=>'open']),'Unrelated branch cannot contact member through team tools');
 $reject(fn()=>fcc_team_outreach_mutate($r['manager'],array_merge($base,['operation'=>'confirm','draft_id'=>$row['id'],'version'=>$row['version']])),'Forged draft ID cannot access another sender snapshot');
 $reject(fn()=>$call('save',null,['request_key'=>bin2hex(random_bytes(16)),'message'=>str_repeat('x',4001)]),'Oversized messages are rejected without truncation');
 $ai=array_merge($base,['situation'=>'Ponudi pomoć oko FCC-a','purpose'=>'fcc','request_key'=>bin2hex(random_bytes(16))]);
 $fake=function($messages)use($ok){$ctx=json_decode($messages[1]['content'],true);$ok(count($ctx['own_recent_outreach'])>0&&str_contains($ctx['outreach_meaning'],'nisu slanje'),'Composer AI receives own previous outreach with honest status semantics');return ['success'=>true,'content'=>json_encode(['guidance'=>'Ponudi jedan zajednički korak.','recipient_message'=>'Bok! Želiš li da zajedno pogledamo FCC? '.SITE_URL.'partner'])];};
 $airow=fcc_team_outreach_generate($actor,$ai,$fake)['draft'];$ok($airow['source']==='ai'&&!$airow['opened_at'],'AI stores preparation only and accepts grounded FCC link');
 $replay=fcc_team_outreach_generate($actor,$ai,fn()=>throw new RuntimeException('Unexpected second model call'))['draft'];$ok($replay['id']===$airow['id'],'AI retry returns stored recommendation without another model request');
 $reject(fn()=>fcc_team_outreach_generate($actor,array_merge($ai,['request_key'=>bin2hex(random_bytes(16))]),fn()=>['success'=>true,'content'=>json_encode(['guidance'=>'Prijedlog','recipient_message'=>'https://evil.example/'])]),'AI invented links fail closed');
 $empty=fcc_team_outreach_generate($actor,array_merge($ai,['request_key'=>bin2hex(random_bytes(16))]),fn()=>['success'=>true,'content'=>json_encode(['guidance'=>'Poštuj odluku osobe da ne želi kontakt.','recipient_message'=>''])])['draft'];$ok($empty['message']==='','Coach can recommend no message when contact is unwanted');
 $paid=fcc_partner_one('SELECT plan_settings FROM users WHERE user_id=?',[$actor]);fcc_partner_query("UPDATE users SET plan_settings='{}' WHERE user_id=?",[$actor]);
 $ok(fcc_team_outreach_history($actor)===[]&&fcc_team_outreach_context($actor)===[],'Downgrade hides outreach history and Coach context');
 $reject(fn()=>$call('open',null,['request_key'=>bin2hex(random_bytes(16))]),'Downgrade rejects stale page mutation');
 fcc_partner_query('UPDATE users SET plan_settings=? WHERE user_id=?',[$paid['plan_settings'],$actor]);
 fcc_team_qa_assign($member,$r['other']);$ok(fcc_team_outreach_history($actor)===[],'Reassignment hides former sponsor private outreach');
 $reject(fn()=>$call('open',null,['request_key'=>bin2hex(random_bytes(16))]),'Reassignment blocks stale contact actions');
 fcc_team_qa_assign($member,$actor);$ok(fcc_team_outreach_history($actor)===[],'Old private history does not reappear after relationship reconnect');
 echo json_encode(['passed'=>count($checks),'checks'=>$checks],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)."\n";
}finally{if($r){$ids=array_values($r);fcc_partner_query('DELETE FROM fcc_team_outreach WHERE actor_user_id IN ('.implode(',',$ids).')');fcc_team_qa_cleanup($ids);}}
