<?php defined('ALTUMCODE') || die();
$j=$data->journey;$j['action']=fcc_localize_copy($j['action']);$j['material']=fcc_localize_copy($j['material']);$a=$j['action'];$v=$data->journey_view;$p=$j['profile'];
if($v==='materials'){require THEME_PATH.'views/partner/journey-materials.php';return;}
if((fcc_jp_enabled((int)$this->user->user_id)&&in_array($v,['pilot','today','step','coach'],true))||(!empty($j['journey90']['pilot'])&&$v==='progress')){require THEME_PATH.'views/partner/journey-pilot.php';return;}
if(fcc_jp_enabled((int)$this->user->user_id)&&empty($j['journey90']['pilot']))echo '<section class="fp-panel"><strong>'.fcc_t('Moj put · 90 praktičnih koraka').'</strong><p>'.fcc_t('Objave, razgovori, preporuke i mentorska pomoć.').'</p><a class="fp-button" href="'.url('partner?view=pilot').'">'.fcc_t('Pregledaj novi program →').'</a></section>';
if(!empty($j['journey90'])&&in_array($v,['today','step','progress','coach'],true)){require THEME_PATH.'views/partner/journey90.php';return;}
$first=explode(' ',trim($this->user->name))[0];
?>
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-partner-journey.css?v=<?= filemtime(ASSETS_PATH.'css/fcc-partner-journey.css') ?>">
<div class="fj" data-journey>
 <header class="fj-heading"><div><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('MOJ PUT · JEDAN KORAK DNEVNO'), ENT_QUOTES, 'UTF-8') ?></span><h1><?= htmlspecialchars(fcc_t('Dobar dan,'), ENT_QUOTES, 'UTF-8') ?> <?= $h($first) ?>.</h1><p><?= htmlspecialchars(fcc_t('Uči, primijeni i nastavi svojim tempom.'), ENT_QUOTES, 'UTF-8') ?></p></div><a class="fj-goal" href="<?= url('partner?view=goal') ?>"><?= $h(fcc_partner_goals()[$p['goal']]) ?><small><?= $p['minutes'] ?> <?= htmlspecialchars(fcc_t('min ·'), ENT_QUOTES, 'UTF-8') ?> <?= $h(fcc_journey_channels()[$p['channel']]) ?> →</small></a></header>
 <nav class="fj-tabs" aria-label="<?= htmlspecialchars(fcc_t('Moj put'), ENT_QUOTES, 'UTF-8') ?>"><?php foreach(fcc_localize_copy(['today'=>'Danas','progress'=>fcc_t('Moj napredak'),'materials'=>'Materijali']) as $key=>$label): ?><a href="<?= url('partner'.($key==='today'?'':'?view='.$key)) ?>" <?= ($v===$key||($key==='today'&&in_array($v,['step','coach','review'],true)))?'aria-current="page"':'' ?>><?= $label ?></a><?php endforeach ?></nav>


 <?php if(fcc_j90_enabled((int)$this->user->user_id)&&in_array(fcc_locale(),['hr','sl','en','de','sr', 'sq', 'cnr', 'fr', 'es'],true)&&!$j['journey90']&&!$j['intro']&&!empty($j['program']['state']['can_access_education'])&&$v==='today'): ?>
 <section class="fp-panel"><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('SPREMAN JE NOVI MOJ PUT'), ENT_QUOTES, 'UTF-8') ?></span><h2><?= htmlspecialchars(fcc_t('90 praktičnih koraka, na jednom mjestu.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Počni od prvog koraka. Tvoja ranija edukacija, osvrti i savjeti ostaju sačuvani. Razine se prilagođavaju tvojoj primjeni; PRO dodaje Coacha i pripremu poruka za WhatsApp.'), ENT_QUOTES, 'UTF-8') ?></p><form method="post" class="fp-form"><?= $token.$request ?><input type="hidden" name="action" value="journey90_start"><label class="fp-check-label"><input type="checkbox" name="confirm" value="1" required> <?= htmlspecialchars(fcc_t('Želim krenuti s novim programom od prvog koraka uz sačuvanu povijest.'), ENT_QUOTES, 'UTF-8') ?></label><button class="fp-button"><?= htmlspecialchars(fcc_t('Počni mojih 90 koraka'), ENT_QUOTES, 'UTF-8') ?></button></form></section>
 <?php endif ?>
 <?php if(in_array($v,['today','step','coach'],true)): ?>
 <div class="fj-layout"><main>
 <?php if((int)($data->counts['due']??0)>0): ?><a class="fj-followup" href="<?= url('partner/contacts?filter=due') ?>"><span><?= fcc_partner_icon('people') ?> <?= htmlspecialchars(fcc_t('Dogovorena javljanja'), ENT_QUOTES, 'UTF-8') ?></span><strong><?= (int)$data->counts['due'] ?> →</strong></a><?php endif ?>
 <?php if($v==='coach'): ?><a class="fj-followup" href="<?= url('partner?view=step') ?>"><span>← <?= $h($a['title']??fcc_t('Moj današnji korak')) ?></span></a><?php else: ?>
 <section class="fj-current">
 <span class="fp-eyebrow"><?= $j['intro']?fcc_t('DOBRO DOŠAO/LA · UVOD'):(!empty($j['program']['state']['can_access_education'])?fcc_t('MOJ PUT · ').$h($a['track_label']??fcc_t('4 CORE')):fcc_t('PRIPREMI SVOJ POČETAK')) ?></span>
 <?php if($j['intro']): ?>
  <h2><?= htmlspecialchars(fcc_t('Upoznaj svoj FCC.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Tvoja početna edukacija, ovdje uz dnevni rad. Dovršeni materijali ostaju spremljeni.'), ENT_QUOTES, 'UTF-8') ?></p>
  <a class="fp-button" href="<?= url('partner?view=materials') ?>"><?= htmlspecialchars(fcc_t('Nastavi uvodnu lekciju'), ENT_QUOTES, 'UTF-8') ?> <?= fcc_partner_icon('arrow') ?></a>
 <?php elseif(empty($j['program']['state']['can_access_education'])): ?>
  <h2><?= htmlspecialchars(fcc_t('Tvoj sljedeći korak počinje ovdje.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Za 4 Core program potrebni su odobren račun, povezan Forever ID i potvrđen upis nakon najmanje 0,33 osobnih CC u kvalifikacijskom mjesecu.'), ENT_QUOTES, 'UTF-8') ?></p>
  <div class="fj-access"><?= $h(match($j['program']['state']['status']??'') {'missing_linkage','duplicate_linkage'=>fcc_t('Provjeri povezanost svojeg Forever ID-a s podrškom.'),'waiting_data','waiting_confirmation'=>fcc_t('Čekamo potvrdu podataka. To ne znači da narudžba nije napravljena.'),default=>fcc_t('Tvoj postojeći upis i napredak ostaju sačuvani.')}) ?></div>
  <a class="fp-button" href="<?= url('partner/points') ?>"><?= htmlspecialchars(fcc_t('Provjeri moj pristup →'), ENT_QUOTES, 'UTF-8') ?></a>
 <?php elseif(!$a): ?>
  <h2><?= htmlspecialchars(fcc_t('Tvoj radni prostor je spreman.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Na ovom računu trenutačno nema osobnog dnevnog zadatka. Materijali i vlastiti podaci ostaju dostupni.'), ENT_QUOTES, 'UTF-8') ?></p><?php if(\Altum\Authentication::is_admin()): ?><a class="fp-button" href="<?= url('partner/admin?journey=1') ?>"><?= htmlspecialchars(fcc_t('Pregledaj program i materijale →'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?>
 <?php elseif(!empty($a['is_daily_complete'])): ?>
  <h2><?= htmlspecialchars(fcc_t('Za danas je dovoljno.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Korak je spremljen. Sljedeći se otvara sutra, prema zagrebačkom vremenu. Dogovori i materijali ostaju pri ruci.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button" href="<?= url('partner?view=progress') ?>"><?= htmlspecialchars(fcc_t('Pogledaj svoj napredak →'), ENT_QUOTES, 'UTF-8') ?></a>
 <?php elseif(!empty($a['is_program_complete'])): ?>
  <h2><?= htmlspecialchars(fcc_t('Izgradio/la si svoj ritam.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Dovršio/la si dostupne korake ovog smjera. Nastavi primjenjivati ono što ti koristi. Proširenje na 90 zadataka i nove razine slijede nakon pregleda sadržaja.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button" href="<?= url('partner/contacts?filter=due') ?>"><?= htmlspecialchars(fcc_t('Nastavi dogovorena javljanja →'), ENT_QUOTES, 'UTF-8') ?></a>
 <?php else: ?>
  <div class="fj-step-meta"><span><?= !empty($a['is_weekly_plan'])?fcc_t('NEDJELJNI WEBINAR'):fcc_t('Korak ').(int)($a['sequence_position']??1).' / 90' ?></span><span><?= $p['minutes'] ?> <?= htmlspecialchars(fcc_t('min za rad'), ENT_QUOTES, 'UTF-8') ?></span></div>
  <h2><?= $h($a['title']??fcc_t('Nastavi svoj program')) ?></h2>
  <p><?= $h($a['instruction']??'') ?></p>
  <?php if($v!=='step'): ?><form method="post"><?= $token ?><input type="hidden" name="action" value="journey_start"><input type="hidden" name="action_key" value="<?= $h($j['key']) ?>"><button class="fp-button"><?= $j['started']?fcc_t('Nastavi današnji korak'):fcc_t('Kreni s današnjim korakom') ?> <?= fcc_partner_icon('arrow') ?></button></form><?php endif ?>
  <?php if($v==='step') require THEME_PATH.'views/partner/journey-step.php'; ?>
 <?php endif ?>
 </section><?php endif ?>
 <?php if($v==='coach') require THEME_PATH.'views/partner/journey-coach.php'; ?>
 <?php if($j['review_due']&&$v==='today'): ?><a class="fj-followup" href="<?= url('partner?view=review') ?>"><span><?= htmlspecialchars(fcc_t('Kratki osvrt na tvoj rad'), ENT_QUOTES, 'UTF-8') ?></span><strong><?= htmlspecialchars(fcc_t('2 pitanja →'), ENT_QUOTES, 'UTF-8') ?></strong></a><?php endif ?>
 <details class="fp-panel fj-personal"><summary><?= htmlspecialchars(fcc_t('Moji dogovori i bilješke'), ENT_QUOTES, 'UTF-8') ?> <span class="fp-count"><?= count($data->tasks) ?></span></summary>
 <?php foreach($data->tasks as $task): ?><form method="post" class="fp-task-row"><?= $token ?><input type="hidden" name="action" value="task_complete"><input type="hidden" name="id" value="<?= (int)$task['id'] ?>"><button class="fp-check" aria-label="Dovrši: <?= $h($task['title']) ?>"><?= fcc_partner_icon('check') ?></button><span><?= $h($task['title']) ?><small><?= $h($task['due_date']) ?></small></span></form><?php endforeach ?>
 <form method="post" class="fp-form"><?= $token.$request ?><input type="hidden" name="action" value="task_add"><label><?= htmlspecialchars(fcc_t('Što želiš zapamtiti?'), ENT_QUOTES, 'UTF-8') ?><input name="title" required maxlength="200" placeholder="<?= htmlspecialchars(fcc_t('Npr. javiti se nakon prezentacije'), ENT_QUOTES, 'UTF-8') ?>"></label><label><?= htmlspecialchars(fcc_t('Datum'), ENT_QUOTES, 'UTF-8') ?><input name="due_date" type="date" value="<?= $h($data->today) ?>" required></label><button class="fp-button fp-button-outline"><?= htmlspecialchars(fcc_t('Dodaj zadatak'), ENT_QUOTES, 'UTF-8') ?></button></form></details>
 </main><aside class="fj-aside">
 <?php if($v!=='coach'): ?><section class="fp-panel fj-coach-teaser"><span class="fp-eyebrow"><?= $j['pro']?fcc_t('TVOJ PRO COACH'):fcc_t('DODATNA POMOĆ UZ PRO') ?></span><h2><?= htmlspecialchars(fcc_t('Pripremimo korak zajedno.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= $j['pro']?fcc_t('Poruka, jednostavniji primjer ili vježba razgovora. Coach poznaje tvoj aktualni korak.'):fcc_t('Osnovni primjer je već uz zadatak. PRO dodaje osobnu pripremu poruke i pomoć za tvoju situaciju.') ?></p><a class="fp-button fp-button-outline" href="<?= url($j['pro']?'partner?view=coach':'account-plan') ?>"><?= $j['pro']?fcc_t('Pripremi sa mnom'):fcc_t('Pogledaj PRO pomoć') ?> →</a></section><?php endif ?>
 <section class="fp-panel"><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('TVOJ RAD · ZADNJIH 7 DANA'), ENT_QUOTES, 'UTF-8') ?></span><div class="fj-stats"><div><strong><?= (int)$j['stats']['completed'] ?></strong><span><?= htmlspecialchars(fcc_t('zabilježenih koraka'), ENT_QUOTES, 'UTF-8') ?></span></div><div><strong><?= (int)$j['stats']['practice'] ?></strong><span><?= htmlspecialchars(fcc_t('lakših koraka / vježbi'), ENT_QUOTES, 'UTF-8') ?></span></div></div><a class="fp-link" href="<?= url('partner?view=progress') ?>"><?= htmlspecialchars(fcc_t('Moj napredak →'), ENT_QUOTES, 'UTF-8') ?></a></section>
 <div class="fp-webinar"><span class="fp-webinar-day"><?= htmlspecialchars(fcc_t('NED'), ENT_QUOTES, 'UTF-8') ?><span>19:00</span></span><div><strong><?= htmlspecialchars(fcc_t('Webinar za nove suradnike'), ENT_QUOTES, 'UTF-8') ?></strong><small><?= htmlspecialchars('Europe/Zagreb', ENT_QUOTES, 'UTF-8') ?></small><a href="<?= url('partner/share?type=webinar') ?>"><?= htmlspecialchars(fcc_t('Podijeli poziv →'), ENT_QUOTES, 'UTF-8') ?></a></div></div>
 </aside></div>
 <?php endif ?>

 <?php if($v==='goal'): ?>
 <section class="fp-panel fj-readable"><h2><?= htmlspecialchars(fcc_t('Moj cilj i tempo'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Jedan smjer za tvoj rad. Ove postavke koristi i Coach; ne stvaraju dodatni plan.'), ENT_QUOTES, 'UTF-8') ?></p>
 <form method="post" class="fp-form"><?= $token ?><input type="hidden" name="action" value="journey_profile"><input type="hidden" name="version" value="<?= $p['version'] ?>">
 <label><?= htmlspecialchars(fcc_t('Što ti je sada najvažnije?'), ENT_QUOTES, 'UTF-8') ?><select name="goal" data-is-not-custom-select><?php foreach(fcc_partner_goals() as $k=>$label): ?><option value="<?= $k ?>" <?= $p['goal']===$k?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label>
 <div class="fp-form-grid"><label><?= htmlspecialchars(fcc_t('Vrijeme za rad'), ENT_QUOTES, 'UTF-8') ?><select name="minutes" data-is-not-custom-select><?php foreach([10,20,45] as $m): ?><option value="<?= $m ?>" <?= $p['minutes']===$m?'selected':'' ?>><?= $m ?> <?= htmlspecialchars(fcc_t('minuta'), ENT_QUOTES, 'UTF-8') ?></option><?php endforeach ?></select></label><label><?= htmlspecialchars(fcc_t('Najčešće koristim'), ENT_QUOTES, 'UTF-8') ?><select name="channel" data-is-not-custom-select><?php foreach(fcc_journey_channels() as $k=>$label): ?><option value="<?= $k ?>" <?= $p['channel']===$k?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label></div>
 <fieldset><legend><?= htmlspecialchars(fcc_t('Moj dnevni podsjetnik'), ENT_QUOTES, 'UTF-8') ?></legend><label class="fp-check-label"><input type="checkbox" name="reminders" value="1" <?= $p['reminders']?'checked':'' ?>> <?= htmlspecialchars(fcc_t('Želim jedan objedinjeni podsjetnik'), ENT_QUOTES, 'UTF-8') ?></label><div><label><?= htmlspecialchars(fcc_t('U koliko sati?'), ENT_QUOTES, 'UTF-8') ?><select name="reminder_hour" data-is-not-custom-select><?php foreach(range(8,20) as $hour): ?><option value="<?= $hour ?>" <?= $p['reminder_hour']===$hour?'selected':'' ?>><?= $hour ?>:00</option><?php endforeach ?></select></label></div><small><?= htmlspecialchars(fcc_t('Europe/Zagreb. Obavijesti o računu i naplati imaju zasebna pravila. Za push treba dopuštenje uređaja.'), ENT_QUOTES, 'UTF-8') ?></small></fieldset>
 <button class="fp-button"><?= htmlspecialchars(fcc_t('Spremi moj smjer'), ENT_QUOTES, 'UTF-8') ?></button></form><a class="fp-link" href="<?= url('partner/notifications') ?>"><?= htmlspecialchars(fcc_t('Obavijesti na uređaju →'), ENT_QUOTES, 'UTF-8') ?></a></section>
 <?php endif ?>

 <?php if($v==='materials'): require THEME_PATH.'views/partner/journey-materials.php'; endif ?>
 <?php if($v==='review'): ?>
 <section class="fp-panel fj-readable"><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('TJEDAN OD'), ENT_QUOTES, 'UTF-8') ?> <?= $h($j['week']) ?></span><h2><?= htmlspecialchars(fcc_t('Što ti pomaže napredovati?'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('U zadnjih sedam dana zabilježeno je'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$j['stats']['completed'] ?> <?= htmlspecialchars(fcc_t('koraka, od toga'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$j['stats']['practice'] ?> <?= htmlspecialchars(fcc_t('lakših koraka ili vježbi. To su tvoje prijavljene aktivnosti, ne potvrda prodaje.'), ENT_QUOTES, 'UTF-8') ?></p>
 <?php if((int)$j['stats']['completed']): $review=$j['review']??[]; ?>
 <form method="post" class="fp-form"><?= $token ?><input type="hidden" name="action" value="journey_review"><input type="hidden" name="week" value="<?= $h($j['week']) ?>"><input type="hidden" name="version" value="<?= (int)($review['version']??0) ?>">
 <label><?= htmlspecialchars(fcc_t('Što ti je pomoglo?'), ENT_QUOTES, 'UTF-8') ?><textarea name="helped" maxlength="800" required rows="3"><?= $h($data->values['helped']??$review['helped']??'') ?></textarea></label><label><?= htmlspecialchars(fcc_t('Gdje je zapelo?'), ENT_QUOTES, 'UTF-8') ?><textarea name="obstacle" maxlength="800" required rows="3"><?= $h($data->values['obstacle']??$review['obstacle']??'') ?></textarea></label><small><?= htmlspecialchars(fcc_t('Bez osobnih ili zdravstvenih podataka drugih osoba. Ako nema prepreke, napiši da ti je korak bio jasan.'), ENT_QUOTES, 'UTF-8') ?></small><button class="fp-button"><?= htmlspecialchars(fcc_t('Spremi osvrt'), ENT_QUOTES, 'UTF-8') ?></button></form>
 <?php if($j['pro']&&$review): ?><a class="fp-button fp-button-outline" href="<?= url('partner?view=coach&purpose=review') ?>"><?= htmlspecialchars(fcc_t('Zatraži jednu preporuku Coacha →'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?>
 <?php else: ?><p><?= htmlspecialchars(fcc_t('Osvrt se otvara nakon prve zabilježene aktivnosti. Sada možeš nastaviti na svom koraku.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
 <a class="fp-link" href="<?= url('partner') ?>"><?= htmlspecialchars(fcc_t('Nastavi svoj korak →'), ENT_QUOTES, 'UTF-8') ?></a></section>
 <?php endif ?>

 <?php if($v==='progress'): ?>
 <section class="fp-panel"><div class="fp-section-title"><h2><?= htmlspecialchars(fcc_t('Tvoj napredak ostaje s tobom.'), ENT_QUOTES, 'UTF-8') ?></h2><a class="fp-link" href="<?= url('partner?view=review') ?>"><?= htmlspecialchars(fcc_t('Kratki osvrt →'), ENT_QUOTES, 'UTF-8') ?></a></div>
 <p><?= htmlspecialchars(fcc_t('Program se priprema za 90 zadataka. Dostupno je 60 koraka po postojećem smjeru. Dodatni zadaci i nova pravila razina čekaju završni zajednički pregled.'), ENT_QUOTES, 'UTF-8') ?></p>
 <div class="fj-stats"><div><strong><?= (int)$j['stats']['completed'] ?></strong><span><?= htmlspecialchars('koraka / 7 dana', ENT_QUOTES, 'UTF-8') ?></span></div><div><strong><?= (int)$j['stats']['hard'] ?></strong><span><?= htmlspecialchars(fcc_t('označeno zahtjevnim'), ENT_QUOTES, 'UTF-8') ?></span></div><div><strong><?= $j['program']['state']['current_personal_cc']===null?'—':$h(number_format((float)$j['program']['state']['current_personal_cc'],3,',','.')) ?></strong><span><?= htmlspecialchars(fcc_t('osobnih CC ·'), ENT_QUOTES, 'UTF-8') ?> <?= $h($j['program']['state']['current_period']??'bez podataka') ?></span></div></div><p class="fp-muted"><?= htmlspecialchars(fcc_t('CC dolaze iz dostupnih FLP360 podataka. Nepotpun podatak nije potvrđena nula. Klikovi, vježbe i prodaje različiti su pokazatelji.'), ENT_QUOTES, 'UTF-8') ?></p>
 <div class="fp-actions"><a class="fp-button fp-button-outline" href="<?= url('fcc-results') ?>"><?= htmlspecialchars(fcc_t('Moji klikovi 15+ / 50+'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-button fp-button-outline" href="<?= url('partner/points') ?>"><?= htmlspecialchars(fcc_t('Bodovi i službeni napredak'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-button fp-button-outline" href="<?= url('partner?view=history') ?>"><?= htmlspecialchars(fcc_t('Raniji planovi i savjeti'), ENT_QUOTES, 'UTF-8') ?></a></div></section>
 <section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Moji posljednji koraci'), ENT_QUOTES, 'UTF-8') ?></h2><?php if(!$j['outcomes']): ?><p><?= htmlspecialchars(fcc_t('Ovdje će biti vidljivi tvoji spremljeni koraci.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?><?php foreach($j['outcomes'] as $o): ?><div class="fj-outcome"><span><strong><?= $h(forever_business_vip_result_type_options()[$o['result_type']]??$o['core_key']) ?></strong><small><?= $h($o['action_date']) ?> · <?= $h($o['core_key']) ?><?= $o['completion_mode']==='quick'||$o['result_type']==='training'?fcc_t(' · Lakša verzija / vježba'):'' ?></small></span><span><?= (int)$o['outcome_count'] ?></span></div><?php endforeach ?></section>
 <?php endif ?>

 <?php if($v==='history'): ?>
 <section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Ranije dovršeni zadaci i webinari'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Ovdje ostaju tvoji zapisi iz ranijeg programa i nedjeljnih susreta. Ne pribrajaju se novom nizu od 90 koraka.'), ENT_QUOTES, 'UTF-8') ?></p>
 <?php foreach($data->journey_old_steps as $old): $webinar=str_starts_with($old['action_key'],'vip26_sunday_'); ?><details class="fj-history"><summary><?= $h($old['action_date']) ?> · <?= $webinar?fcc_t('Nedjeljni webinar'):($old['sequence_position']?fcc_t('Korak ').(int)$old['sequence_position']:fcc_t('Zabilježena aktivnost')) ?></summary><p><?= $h($old['core_key']) ?> · <?= $old['result_type']==='training'||$old['completion_mode']==='quick'?fcc_t('Vježba prema ranijem pravilu'):fcc_t('Potvrđen zadatak prema ranijem pravilu') ?></p><?php if($old['note']): ?><p><?= nl2br($h($old['note'])) ?></p><?php endif ?></details><?php endforeach ?>
 <?php if(!$data->journey_old_steps): ?><p class="fp-muted"><?= htmlspecialchars(fcc_t('Još nema ranijih zapisa.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
 <?php if($data->journey_more_steps): ?><a class="fp-link" href="<?= url('partner?view=history&before_outcome='.(int)end($data->journey_old_steps)['outcome_id']) ?>"><?= htmlspecialchars(fcc_t('Stariji zadaci →'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?>
 </section>
 <section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Raniji razgovori s FCC pomoćnikom'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Sačuvani razgovori iz prethodnog prikaza. Za današnji rad otvori Coacha uz svoj korak.'), ENT_QUOTES, 'UTF-8') ?></p>
<?php foreach($data->journey_chats as $chat): ?><a class="fp-link" href="<?= url('partner?view=history&conversation='.(int)$chat['fcc_ai_conversation_id']) ?>"><?= $h($chat['datetime']) ?> <?= htmlspecialchars(fcc_t('UTC →'), ENT_QUOTES, 'UTF-8') ?></a><?php endforeach ?>
<?php if(!$data->journey_chats): ?><p class="fp-muted"><?= htmlspecialchars(fcc_t('Nema ranijih razgovora.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
<?php if($data->journey_more_chats): ?><a class="fp-link" href="<?= url('partner?view=history&history_page='.($data->journey_chat_page+1)) ?>"><?= htmlspecialchars(fcc_t('Stariji razgovori →'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?>
<?php foreach($data->journey_chat_messages as $message): ?><div class="fj-history"><strong><?= $message['role']==='user'?fcc_t('Ti'):fcc_t('FCC pomoćnik') ?></strong><p><?= nl2br($h($message['content'])) ?></p></div><?php endforeach ?></section>
 <section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Tvoji raniji planovi i osvrti'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Sačuvani su za pregled. Novi rad nastavlja se u jednoj cjelini Moj put.'), ENT_QUOTES, 'UTF-8') ?></p>
 <?php foreach($data->journey_plans as $plan): $content=json_decode($plan['content']??'{}',true)?:[]; ?><details class="fj-history"><summary><?= $h($plan['month']) ?> · <?= $h(fcc_partner_goals()[$plan['goal']]??fcc_t('Raniji plan')) ?></summary><p><?= $h($content['summary']??'') ?></p><?php foreach($content['weeks']??[] as $week): ?><h3><?= $h($week['title']??'') ?></h3><p><?= $h($week['action']??'') ?></p><small><?= $h($week['measure']??'') ?></small><?php endforeach ?><p><?= $h($content['next_step']??'') ?></p></details><?php endforeach ?>
 <?php foreach($data->journey_reviews as $review): ?><details class="fj-history"><summary><?= htmlspecialchars(fcc_t('Osvrt ·'), ENT_QUOTES, 'UTF-8') ?> <?= $h($review['week_start']) ?></summary><h3><?= htmlspecialchars(fcc_t('Što je pomoglo'), ENT_QUOTES, 'UTF-8') ?></h3><p><?= $h($review['helped']) ?></p><h3><?= htmlspecialchars(fcc_t('Što je bilo zahtjevno'), ENT_QUOTES, 'UTF-8') ?></h3><p><?= $h($review['obstacle']) ?></p></details><?php endforeach ?>
 <?php foreach(fcc_localize_copy(['leader_ai_weekly_plans'=>fcc_t('Raniji AI prijedlog'),'leader_ai_weekly_checkins'=>fcc_t('Raniji tjedni osvrt'),'leader_ai_weekly_outcomes'=>fcc_t('Raniji zabilježeni ishod')]) as $key=>$label): foreach(array_slice((array)($j['user']->preferences->$key??[]),0,50) as $old): ?><details class="fj-history"><summary><?= $label ?> · <?= $h(((array)$old)['generated_at']??((array)$old)['submitted_at']??'') ?></summary><?php $print=function($value,$depth=0)use(&$print,$h){if($depth>6)return;if(is_scalar($value)&&!is_bool($value)){echo '<p>'.$h($value).'</p>';}elseif(is_array($value)||is_object($value))foreach((array)$value as $k=>$child){if(in_array($k,['id','user_id','request_key','model'],true))continue;$print($child,$depth+1);}};$print($old); ?></details><?php endforeach; endforeach ?>
 <?php if(!$data->journey_plans&&!$data->journey_reviews): ?><p class="fp-muted"><?= htmlspecialchars(fcc_t('Novi planovi i osvrti ovdje se pojavljuju tek kada ih spremiš.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
 </section><section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Moji spremljeni savjeti'), ENT_QUOTES, 'UTF-8') ?></h2><?php if(!$data->journey_advice): ?><p><?= htmlspecialchars(fcc_t('Još nema spremljenih savjeta.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?><?php foreach($data->journey_advice as $advice): $c=json_decode($advice['content'],true)?:[]; ?><details class="fj-history"><summary><?= $h($advice['created_at']) ?> <?= htmlspecialchars(fcc_t('UTC ·'), ENT_QUOTES, 'UTF-8') ?> <?= $h(['message'=>'Poruka','reply'=>'Razgovor','simplify'=>fcc_t('Jednostavniji primjer'),'review'=>'Osvrt'][$advice['purpose']]??'Savjet') ?></summary><?php foreach(['guidance','message','next_step','question'] as $key): if(!empty($c[$key])): ?><p><?= nl2br($h($c[$key])) ?></p><?php endif; endforeach ?></details><?php endforeach ?></section>
 <?php endif ?>
</div>

