<?php
/** One pilot journey on the same web/PWA account. */
defined('ALTUMCODE') || die();
$uid=(int)$this->user->user_id;$n=$j['journey90'];$isPilot=!empty($n['pilot']);
$cycle=$n['cycle']??fcc_j90_cycle($uid);$step=$isPilot?$n['step']:null;$c=$isPilot?fcc_localize_copy($n['content']):null;
$fields=function(string $op,array $extra=[])use($token,$h,$cycle,$step){
 $html=$token;foreach($extra+['action'=>'pilot_'.$op,'catalog_version'=>FCC_JP_VERSION,'request_key'=>bin2hex(random_bytes(16)),'cycle_id'=>$cycle['id']??0,'cycle_version'=>$cycle['version']??0,'step_id'=>$step['id']??0,'draft_version'=>$step['draft_version']??0] as $k=>$value)if($value!==null)$html.='<input type="hidden" name="'.$h($k).'" value="'.$h((string)$value).'">';return $html;
};
?>
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-journey-pilot.css?v=<?= filemtime(THEME_PATH.'assets/css/fcc-journey-pilot.css') ?>">
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-journey-foundation.css?v=<?= filemtime(THEME_PATH.'assets/css/fcc-journey-foundation.css') ?>">
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-journey-warm.css?v=<?= filemtime(THEME_PATH.'assets/css/fcc-journey-warm.css') ?>">
<div class="jp-page">
<header class="jp-heading"><div><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('MOJ PUT'), ENT_QUOTES, 'UTF-8') ?></span><h1><?= $v==='progress'?fcc_t('Dogovori i napredak'):($v==='pilot'?fcc_t('Svih 90 koraka'):fcc_t('Tvoj današnji korak')) ?></h1></div>
<?php if($isPilot): ?><div class="jp-progress"><span><?= $n['completed'] ?> / 90</span><progress max="90" value="<?= $n['completed'] ?>" aria-label="<?= htmlspecialchars(fcc_t('Dovršeni koraci'), ENT_QUOTES, 'UTF-8') ?>"></progress></div><?php endif ?></header>
<nav class="jp-tabs" aria-label="<?= htmlspecialchars(fcc_t('Moj put'), ENT_QUOTES, 'UTF-8') ?>"><a href="<?= url('partner?view=step') ?>" <?= $v==='step'?'aria-current="page"':'' ?>><?= htmlspecialchars(fcc_t('Moj korak'), ENT_QUOTES, 'UTF-8') ?></a><a href="<?= url('partner?view=progress') ?>" <?= $v==='progress'?'aria-current="page"':'' ?>><?= htmlspecialchars(fcc_t('Napredak'), ENT_QUOTES, 'UTF-8') ?></a><details class="jp-nav-more"><summary><?= htmlspecialchars(fcc_t('Više'), ENT_QUOTES, 'UTF-8') ?></summary><div><a href="<?= url('partner?view=pilot') ?>"><?= htmlspecialchars(fcc_t('Pregled 90 koraka'), ENT_QUOTES, 'UTF-8') ?></a><a href="<?= url('partner?view=goal') ?>"><?= htmlspecialchars(fcc_t('Moj tempo'), ENT_QUOTES, 'UTF-8') ?></a></div></details></nav>
<?php if($isPilot&&$n['fast']): ?><p class="jp-test"><?= htmlspecialchars(fcc_t('Lokalni test · možeš proći više koraka danas.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
<?php if(!$isPilot||$v==='pilot'): ?>
<section class="fp-panel"><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('TVOJ PUT KROZ 4 CORE'), ENT_QUOTES, 'UTF-8') ?></span><h2><?= htmlspecialchars(fcc_t('Jedan jasan korak svaki dan.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Najprije pripremi svoje alate i pokreni prve razgovore. Zatim razvijaj sigurnost, brini o kupcima i nauči pomagati drugima. Svaki dan te čekaju tri jasne radnje i alat koji ti olakšava posao.'), ENT_QUOTES, 'UTF-8') ?></p>
<?php if(!$isPilot&&!$j['intro']&&!empty($j['program']['state']['can_access_education'])): ?><form method="post" class="fp-form"><?= $fields('start',['previous_cycle_id'=>$cycle['id']??0,'previous_cycle_version'=>$cycle['version']??0]) ?><label class="fp-check-label"><input type="checkbox" name="confirm" value="1" required> <?= htmlspecialchars(fcc_t('Želim početi od prvog novog koraka. Moj raniji program i zapisi ostaju u povijesti.'), ENT_QUOTES, 'UTF-8') ?></label><button class="fp-button"><?= htmlspecialchars(fcc_t('Počni svoj put →'), ENT_QUOTES, 'UTF-8') ?></button></form><?php endif ?>
<?php if(!$isPilot&&($j['intro']||empty($j['program']['state']['can_access_education']))): ?><p><?= htmlspecialchars(fcc_t('Najprije dovrši uvod i provjeri svoj pristup edukaciji. Cijeli program možeš pregledati ispod.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button fp-button-outline" href="<?= url('partner?view=materials') ?>"><?= htmlspecialchars(fcc_t('Otvori uvod i materijale →'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?>
<div class="jp-phases"><?php foreach(fcc_localize_copy(fcc_jp_catalog())['phases'] as $phase): ?><details class="jp-phase" <?= isset($_GET['day'])&&(int)$_GET['day']>=$phase['from']&&(int)$_GET['day']<=$phase['to']?'open':'' ?>><summary><span><?= htmlspecialchars(fcc_t('Koraci'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$phase['from'] ?> <?= htmlspecialchars(fcc_t('do'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$phase['to'] ?></span><strong><?= $h($phase['name']) ?></strong><small><?= $h($phase['description']) ?></small></summary><ol class="jp-catalog"><?php foreach(array_slice(fcc_localize_copy(fcc_jp_catalog())['tasks'],$phase['from']-1,15) as $t): ?><li id="journey-day-<?= (int)$t['day'] ?>"><details <?= (int)($_GET['day']??0)===(int)$t['day']?'open':'' ?>><summary><span><?= str_pad((string)$t['day'],2,'0',STR_PAD_LEFT) ?></span><strong><?= $h($t['title']) ?></strong></summary><p class="fp-muted"><?= $h($t['core_label'].' · '.$t['tool_label']) ?></p><p><?= $h($t['why']) ?></p><ol><?php foreach($t['actions'] as $x): ?><li><?= $h($x) ?></li><?php endforeach ?></ol><p><strong><?= htmlspecialchars(fcc_t('Što dobivaš ovim korakom:'), ENT_QUOTES, 'UTF-8') ?></strong> <?= $h($t['completion']) ?></p><?php if($t['communication']['example']!==''): ?><details><summary><?= htmlspecialchars(fcc_t('Primjer poruke'), ENT_QUOTES, 'UTF-8') ?></summary><p><?= nl2br($h($t['communication']['example'])) ?></p></details><?php endif ?><?php if(!empty($t['inline_coach'])): ?><p class="jw-review-coach"><strong><?= $h(fcc_t('Pomoć Coacha')) ?> · PRO</strong><br><?= $h(fcc_journey_review_coach_copy($t)['intro']) ?></p><?php endif ?><?php if(!empty($t['content_support'])): require THEME_PATH.'views/partner/journey-content-support.php'; endif ?></details></li><?php endforeach ?></ol></details><?php endforeach ?></div></section>
<?php elseif($v==='progress'): ?>
<?php $applied=count(array_filter($n['rows'],fn($r)=>$r['learning_mode']==='applied'));$opps=fcc_jp_opportunities($uid); ?>
<div class="jp-metrics"><section class="fp-panel"><strong><?= $applied ?></strong><span><?= htmlspecialchars(fcc_t('Koraka u stvarnom radu'), ENT_QUOTES, 'UTF-8') ?></span></section><section class="fp-panel"><strong><?= $n['completed']-$applied ?></strong><span><?= htmlspecialchars(fcc_t('Praktičnih vježbi'), ENT_QUOTES, 'UTF-8') ?></span></section><section class="fp-panel"><strong><?= count($opps) ?></strong><span><?= htmlspecialchars(fcc_t('Povezanih razgovora'), ENT_QUOTES, 'UTF-8') ?></span></section></div>
<section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Tvoja četiri Core područja'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Ovdje vidiš odrađene korake. Kupce, narudžbe i CC bodove pratiš zasebno.'), ENT_QUOTES, 'UTF-8') ?></p><div class="jp-core-grid"><?php foreach(fcc_localize_copy(fcc_jp_catalog())['cores'] as $key=>$label): $coreRows=array_filter($n['rows'],fn($r)=>strtolower($r['core_key'])===$key);$real=count(array_filter($coreRows,fn($r)=>$r['learning_mode']==='applied'));?><div><strong><?= $h($label) ?></strong><span><?= $real ?> <?= htmlspecialchars(fcc_t('u praksi ·'), ENT_QUOTES, 'UTF-8') ?> <?= count($coreRows)-$real ?> <?= htmlspecialchars(fcc_t('vježbi'), ENT_QUOTES, 'UTF-8') ?></span></div><?php endforeach ?></div></section>
<section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Dogovoreni nastavci'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Promjena datuma sprema se i u tvoje Kontakte. Kupnja koju navedeš ovdje ostaje tvoja potvrda, odvojena od službenog uvoza.'), ENT_QUOTES, 'UTF-8') ?></p><?php if(!$opps): ?><p class="fp-muted"><?= htmlspecialchars(fcc_t('Kad uz korak odabereš kontakt i potvrdiš razgovor ili slanje, ovdje se pojavljuje dogovor za nastavak.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
<?php foreach($opps as $o): ?><details class="jp-opportunity"><summary><?= $h($o['name']) ?> <span><?= $h(fcc_jp_statuses()[$o['status']]) ?></span></summary><form method="post" class="fp-form"><?= $fields('opportunity',['opportunity_id'=>$o['id'],'opportunity_version'=>$o['version'],'contact_version'=>$o['contact_version']]) ?><label><?= htmlspecialchars(fcc_t('Status'), ENT_QUOTES, 'UTF-8') ?><select name="status" data-is-not-custom-select><?php foreach(fcc_jp_statuses() as $key=>$label): ?><option value="<?= $key ?>" <?= $key===$o['status']?'selected':'' ?>><?= $h($label) ?></option><?php endforeach ?></select></label><label><?= htmlspecialchars(fcc_t('Dogovoreni datum'), ENT_QUOTES, 'UTF-8') ?><input name="next_followup" type="date" value="<?= $h($o['next_followup']??'') ?>" min="<?= $h(fcc_partner_today()) ?>"></label><label class="fp-check-label"><input type="checkbox" name="agreed" value="1"> <?= htmlspecialchars(fcc_t('Osoba je pristala na javljanje tog dana.'), ENT_QUOTES, 'UTF-8') ?></label><button class="fp-button"><?= htmlspecialchars(fcc_t('Spremi dogovor'), ENT_QUOTES, 'UTF-8') ?></button><a href="<?= url('partner/contacts?id='.(int)$o['contact_id']) ?>"><?= htmlspecialchars(fcc_t('Otvori kontakt →'), ENT_QUOTES, 'UTF-8') ?></a></form></details><?php endforeach ?></section>
<section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('CC i rezultat prodaje'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= $h($n['capabilities']['label']) ?></p><a class="fp-link" href="<?= url('partner/points') ?>"><?= htmlspecialchars(fcc_t('Pogledaj moje Forever podatke →'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-link" href="<?= url('fcc-results') ?>"><?= htmlspecialchars(fcc_t('Moji kvalificirani klikovi →'), ENT_QUOTES, 'UTF-8') ?></a></section>
<section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Sačuvani koraci'), ENT_QUOTES, 'UTF-8') ?></h2><?php foreach($n['rows'] as $r): $t=fcc_localize_copy(json_decode($r['content_json'],true)?:[]); ?><details class="jp-opportunity"><summary><?= (int)$r['sequence_position'] ?>. <?= $h($t['title']) ?><span><?= $r['learning_mode']==='practice'?fcc_t('Vježba'):fcc_t('Primjena · samopotvrda') ?></span></summary><p><?= $h($r['action_date']) ?></p><p><?= $h($r['note']) ?></p><p><?= $h($t['completion']) ?></p></details><?php endforeach ?>
<?php $oldCycles=fcc_partner_rows('SELECT id,catalog_version,started_at FROM fcc_partner_journey_cycles WHERE user_id=? AND id<>? ORDER BY id DESC',[$uid,(int)$cycle['id']]);foreach($oldCycles as $old): ?><details class="jp-opportunity"><summary><?= htmlspecialchars(fcc_t('Raniji program ·'), ENT_QUOTES, 'UTF-8') ?> <?= $h($old['started_at']) ?></summary><?php foreach(fcc_j90_rows($uid,(int)$old['id']) as $r): $t=fcc_localize_copy(json_decode($r['content_json'],true)?:[]); ?><p><?= (int)$r['sequence_position'] ?>. <?= $h($t['title']??$r['action_key']) ?> · <?= $h($r['action_date']) ?></p><?php endforeach ?></details><?php endforeach ?><a href="<?= url('partner?view=history') ?>"><?= htmlspecialchars(fcc_t('Ranija edukacija i AI savjeti →'), ENT_QUOTES, 'UTF-8') ?></a></section>
<?php elseif($n['pilot_finished']): ?><section class="fp-panel"><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('TVOJ PROGRAM JE ZAVRŠEN'), ENT_QUOTES, 'UTF-8') ?></span><h2><?= htmlspecialchars(fcc_t('Od prvog koraka do vlastite rutine.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Prošao/la si svih 90 koraka. Nastavi s dogovorenim javljanjima i temom koju si odabrao/la za idući tjedan. U Napretku možeš pregledati sve odrađene zadatke i područja koja želiš još uvježbati.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button" href="<?= url('partner?view=progress') ?>"><?= htmlspecialchars(fcc_t('Pogledaj moj napredak →'), ENT_QUOTES, 'UTF-8') ?></a></section>
<?php elseif(!$n['enabled']||$j['intro']||empty($j['program']['state']['can_access_education'])): ?><section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Provjerimo pristup tvom koraku.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Napredak je sačuvan. Za nastavak vrijede postojeći uvod i uvjeti pristupa edukaciji.'), ENT_QUOTES, 'UTF-8') ?></p><a href="<?= url('partner?view=materials') ?>"><?= htmlspecialchars(fcc_t('Otvori uvod i materijale →'), ENT_QUOTES, 'UTF-8') ?></a></section>
<?php elseif($n['daily_done']): ?><section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Današnji korak je spremljen.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Sljedeći redovni korak čeka sutra. Svoje dogovorene razgovore možeš nastaviti sada.'), ENT_QUOTES, 'UTF-8') ?></p><div class="fp-actions"><a class="fp-button" href="<?= url('partner?view=materials#business-learning') ?>"><?= htmlspecialchars(fcc_t('Nauči nešto uz svoj tim'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-link" href="<?= url('partner?view=progress') ?>"><?= htmlspecialchars(fcc_t('Pogledaj dogovore'), ENT_QUOTES, 'UTF-8') ?></a></div><p><?= htmlspecialchars(fcc_t('Možeš pitati Coacha ili sponzora o onome što te zanima. To je tvoj izbor, bez dodatnog obveznog zadatka.'), ENT_QUOTES, 'UTF-8') ?></p></section>
<?php elseif($n['webinar']['is_today']): ?><section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Webinar u'), ENT_QUOTES, 'UTF-8') ?> <?= $h($n['webinar']['time_label']) ?></h2><p><?= htmlspecialchars(fcc_t('Danas je prostor za učenje. Tvoj redovni korak ostaje sačuvan.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button" href="<?= url('partner/share?type=webinar') ?>"><?= htmlspecialchars(fcc_t('Detalji webinara'), ENT_QUOTES, 'UTF-8') ?></a><?php if($n['webinar']['can_record_outcome']): ?><form method="post" class="fp-form"><?= $fields('webinar',['action'=>'journey90_webinar']) ?><label><?= htmlspecialchars(fcc_t('Sudjelovanje'), ENT_QUOTES, 'UTF-8') ?><select name="learning_mode" data-is-not-custom-select><option value="applied"><?= htmlspecialchars(fcc_t('Sudjelovao/la sam'), ENT_QUOTES, 'UTF-8') ?></option><option value="practice"><?= htmlspecialchars(fcc_t('Prošao/la sam dostupan materijal'), ENT_QUOTES, 'UTF-8') ?></option></select></label><label><?= htmlspecialchars(fcc_t('Jedna korisna ideja'), ENT_QUOTES, 'UTF-8') ?><textarea name="note" required maxlength="500"></textarea></label><label><input type="checkbox" name="self_check" value="1" required> <?= htmlspecialchars(fcc_t('Potvrđujem sudjelovanje ili prolazak materijala.'), ENT_QUOTES, 'UTF-8') ?></label><button class="fp-button"><?= htmlspecialchars(fcc_t('Spremi'), ENT_QUOTES, 'UTF-8') ?></button></form><?php else: ?><p><?= htmlspecialchars(fcc_t('Potvrda se otvara nakon'), ENT_QUOTES, 'UTF-8') ?> <?= $h($n['webinar']['completion_available_at_display']) ?>.</p><?php endif ?></section>
<?php elseif($v==='coach'&&$step): require THEME_PATH.'views/partner/journey-coach.php';
else: require THEME_PATH.'views/partner/journey-pilot-step.php';
endif; ?></div>

<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-education-library.css?v=<?= filemtime(ASSETS_PATH.'css/fcc-education-library.css') ?>">
<script src="<?= ASSETS_FULL_URL ?>js/fcc-education-library.js?v=<?= filemtime(ASSETS_PATH.'js/fcc-education-library.js') ?>" defer></script>
