<?php defined('ALTUMCODE') || die();
$n=$j['journey90'];$c=$n['content'];$cycle=$n['cycle'];$step=$n['step'];$draft=$n['draft']?:[];
$fields=function(string $op)use($token,$cycle,$step){return $token.'<input type="hidden" name="action" value="journey90_'.$op.'"><input type="hidden" name="request_key" value="'.bin2hex(random_bytes(16)).'"><input type="hidden" name="cycle_id" value="'.(int)$cycle['id'].'"><input type="hidden" name="cycle_version" value="'.(int)$cycle['version'].'"><input type="hidden" name="step_id" value="'.(int)($step['id']??0).'"><input type="hidden" name="draft_version" value="'.(int)($step['draft_version']??0).'">';};
$levelNames=array_column(fcc_j90_catalog($cycle['catalog_version'])['levels'],'label','level');
?>
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-partner-journey.css?v=<?= filemtime(ASSETS_PATH.'css/fcc-partner-journey.css') ?>">
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-journey90.css?v=<?= filemtime(ASSETS_PATH.'css/fcc-journey90.css') ?>">
<div class="fj j90" data-journey90>
<header class="fj-heading"><div><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('MOJ PUT ·'), ENT_QUOTES, 'UTF-8') ?> <?= $n['completed'] ?><?= htmlspecialchars(fcc_t('/90 DOVRŠENO'), ENT_QUOTES, 'UTF-8') ?></span><h1><?= $h($n['completed']===90?fcc_t('Tvoj 4 Core ritam'):fcc_t('Dobar dan, ').explode(' ',trim($this->user->name))[0].'.') ?></h1><p><?= $h($levelNames[(int)$cycle['accepted_level']]) ?></p></div><a class="fj-goal" href="<?= url('partner?view=goal') ?>"><?= htmlspecialchars(fcc_t('Moj cilj i tempo'), ENT_QUOTES, 'UTF-8') ?> <small><?= (int)$p['minutes'] ?> <?= htmlspecialchars(fcc_t('min · Postavke →'), ENT_QUOTES, 'UTF-8') ?></small></a></header>
<nav class="fj-tabs" aria-label="<?= htmlspecialchars(fcc_t('Moj put'), ENT_QUOTES, 'UTF-8') ?>"><?php foreach(fcc_localize_copy(['today'=>'Danas','progress'=>fcc_t('Moj napredak'),'materials'=>'Materijali']) as $nav=>$label): ?><a href="<?= url('partner'.($nav==='today'?'':'?view='.$nav)) ?>" <?= $v===$nav||($nav==='today'&&in_array($v,['step','coach'],true))?'aria-current="page"':'' ?>><?= $label ?></a><?php endforeach ?></nav>
<?php if(!$n['enabled']): ?><section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Program je privremeno u pregledu.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Tvoj napredak ostaje sačuvan. Novi upisi trenutačno nisu uključeni.'), ENT_QUOTES, 'UTF-8') ?></p></section>
<?php elseif($j['intro']||empty($j['program']['state']['can_access_education'])): ?><section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Provjeri pristup edukaciji.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Tvoj ciklus i svi spremljeni koraci ostaju sačuvani.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button" href="<?= url($j['intro']?'partner?view=materials':'forever-business?classic=1') ?>"><?= htmlspecialchars(fcc_t('Nastavi provjeru'), ENT_QUOTES, 'UTF-8') ?></a></section>
<?php elseif($v==='progress'): ?>
<section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Tvoje vještine i stvarne radnje'), ENT_QUOTES, 'UTF-8') ?></h2><div class="fj-stats"><div><strong><?= $n['completed'] ?>/90</strong><span><?= htmlspecialchars(fcc_t('koraka u ovom programu'), ENT_QUOTES, 'UTF-8') ?></span></div><div><strong><?= count(array_filter($n['rows'],fn($r)=>$r['learning_mode']==='applied')) ?></strong><span><?= htmlspecialchars(fcc_t('primjena prema tvojoj potvrdi'), ENT_QUOTES, 'UTF-8') ?></span></div><div><strong><?= count(array_filter($n['rows'],fn($r)=>$r['interaction_id'])) ?></strong><span><?= htmlspecialchars('stvarnih komunikacija koje si potvrdio/la', ENT_QUOTES, 'UTF-8') ?></span></div></div><p><?= htmlspecialchars(fcc_t('Vježbe pomiču program naprijed. Primjena i stvarna komunikacija odvojeni su od kupnje, odgovora i CC bodova.'), ENT_QUOTES, 'UTF-8') ?></p>
<?php if($n['readiness']['proposed_level']): ?><form method="post" class="fp-form"><?= $fields('level') ?><input type="hidden" name="level" value="<?= $n['readiness']['proposed_level'] ?>"><h3><?= htmlspecialchars(fcc_t('Spreman/na si isprobati sljedeću razinu.'), ENT_QUOTES, 'UTF-8') ?></h3><p><?= $h($levelNames[$n['readiness']['proposed_level']]) ?><?= htmlspecialchars(fcc_t('. Promjena vrijedi od sljedećeg neotvorenog koraka.'), ENT_QUOTES, 'UTF-8') ?></p><button class="fp-button"><?= htmlspecialchars(fcc_t('Prihvati sljedeću razinu'), ENT_QUOTES, 'UTF-8') ?></button></form>
<?php elseif((int)$cycle['accepted_level']<4): $rr=$n['readiness']; ?><details class="fj-history"><summary><?= htmlspecialchars(fcc_t('Što se gleda za sljedeću razinu?'), ENT_QUOTES, 'UTF-8') ?></summary><p><?= htmlspecialchars(fcc_t('U zadnjih'), ENT_QUOTES, 'UTF-8') ?> <?= $rr['rule']['window'] ?> <?= htmlspecialchars(fcc_t('koraka:'), ENT_QUOTES, 'UTF-8') ?> <?= $rr['counts']['applied'] ?>/<?= $rr['rule']['min_applied'] ?> <?= htmlspecialchars(fcc_t('primjena,'), ENT_QUOTES, 'UTF-8') ?> <?= $rr['counts']['external'] ?>/<?= $rr['rule']['min_external'] ?> <?= htmlspecialchars(fcc_t('stvarnih komunikacija i'), ENT_QUOTES, 'UTF-8') ?> <?= $rr['counts']['cores'] ?>/<?= $rr['rule']['min_cores'] ?> <?= htmlspecialchars(fcc_t('Core područja.'), ENT_QUOTES, 'UTF-8') ?></p><p><?= htmlspecialchars(fcc_t('Ukupno je potrebno'), ENT_QUOTES, 'UTF-8') ?> <?= $rr['rule']['min_completed'] ?> <?= htmlspecialchars(fcc_t('koraka'), ENT_QUOTES, 'UTF-8') ?><?= $rr['rule']['min_advanced']?fcc_t(' i dva napredna stvarna slučaja'):'' ?><?= htmlspecialchars(fcc_t('. CC nije uvjet promjene edukacijske razine. Svih 90 koraka možeš završiti na osnovnoj razini.'), ENT_QUOTES, 'UTF-8') ?></p></details><?php endif ?>
<details class="fj-history"><summary><?= htmlspecialchars(fcc_t('CC · izvor i svježina podataka'), ENT_QUOTES, 'UTF-8') ?></summary><?php foreach($n['cc'] as $cc): ?><p><strong><?= $h(substr($cc['period'],0,7)) ?> · <?= $cc['personal_cc']===null?'—':$h(number_format($cc['personal_cc'],3,',','.')) ?> <?= htmlspecialchars(fcc_t('osobnih CC'), ENT_QUOTES, 'UTF-8') ?></strong><br><?= $h(['verified'=>'Provjereno','pending'=>fcc_t('Čeka potvrdu izvora'),'stale'=>fcc_t('Čeka osvježavanje'),'conflict'=>fcc_t('Potrebna provjera'),'unavailable'=>fcc_t('Nije dostupno')][$cc['status']]) ?> <?= htmlspecialchars(fcc_t('· Službeni 4 CC Active:'), ENT_QUOTES, 'UTF-8') ?> <?= $cc['active']===null?'nije poznato':($cc['active']?'da':'ne') ?><br><small><?= $h($cc['reason']) ?><?= $cc['checked_at']?fcc_t(' Provjera: ').$h($cc['checked_at']):'' ?></small></p><?php endforeach ?><p><?= htmlspecialchars(fcc_t('Učenje ne brišemo kad uvoz kasni ili ispravi bodove. Klikove i poruke ne pretvaramo u narudžbe ili CC.'), ENT_QUOTES, 'UTF-8') ?></p></details>
<a class="fp-link" href="<?= url('partner/points') ?>"><?= htmlspecialchars(fcc_t('Moji službeni CC podaci i vrijeme izvora →'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-link" href="<?= url('fcc-results') ?>"><?= htmlspecialchars(fcc_t('Moji klikovi 15+ / 50+ →'), ENT_QUOTES, 'UTF-8') ?></a></section>
<section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Sačuvani koraci'), ENT_QUOTES, 'UTF-8') ?></h2><?php foreach(array_reverse($n['rows']) as $row): $snap=json_decode($row['content_json'],true); ?><details class="fj-history"><summary><?= (int)$row['sequence_position'] ?>. <?= $h($snap['title']) ?> · <?= $row['learning_mode']==='practice'?fcc_t('Vježba'):fcc_t('Primjena') ?></summary><p><?= $h($row['action_date']) ?> · <?= $h($snap['core_label']) ?></p><p><?= $h($snap['variant']['criterion']) ?></p><?php if($row['note']): ?><p><?= nl2br($h($row['note'])) ?></p><?php endif ?><small><?= htmlspecialchars(fcc_t('Verzija'), ENT_QUOTES, 'UTF-8') ?> <?= $h($snap['catalog_version']) ?> <?= htmlspecialchars(fcc_t('· razina'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$snap['variant']['level'] ?></small></details><?php endforeach ?><?php $saved=fcc_partner_rows('SELECT s.position,s.content_json,s.draft_json,s.opened_at FROM fcc_partner_journey_steps s WHERE s.user_id=? AND s.draft_json IS NOT NULL ORDER BY s.id DESC LIMIT 90',[(int)$this->user->user_id]);if($saved): ?><h3><?= htmlspecialchars(fcc_t('Moje korisne poruke'), ENT_QUOTES, 'UTF-8') ?></h3><?php foreach($saved as $savedRow):$dm=json_decode($savedRow['draft_json'],true);$ct=json_decode($savedRow['content_json'],true);if(empty($dm['message']))continue; ?><details class="fj-history"><summary><?= (int)$savedRow['position'] ?>. <?= $h($ct['title']) ?></summary><p><?= $h($ct['communication']['situation']) ?></p><blockquote><?= nl2br($h($dm['message'])) ?></blockquote><small><?= $h($dm['country']??'') ?> <?= htmlspecialchars(fcc_t('· Pripremljeno'), ENT_QUOTES, 'UTF-8') ?> <?= $h($dm['prepared_at']??$savedRow['opened_at']) ?><?= htmlspecialchars(fcc_t('. Prije ponovne uporabe provjeri aktualnost i osobu kojoj pišeš.'), ENT_QUOTES, 'UTF-8') ?></small><button class="fp-button fp-button-outline" type="button" data-copy="<?= $h($dm['message']) ?>"><?= htmlspecialchars(fcc_t('Kopiraj svoju poruku'), ENT_QUOTES, 'UTF-8') ?></button></details><?php endforeach;endif ?>
<a class="fp-link" href="<?= url('partner?view=history') ?>"><?= htmlspecialchars(fcc_t('Raniji planovi, savjeti i osvrti →'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-link" href="<?= url('partner?view=review') ?>"><?= htmlspecialchars(fcc_t('Moj tjedni osvrt →'), ENT_QUOTES, 'UTF-8') ?></a></section>
<?php else: ?>
<?php if($n['due']): ?><section class="j90-priority fp-panel"><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('TVOJ DOGOVOR IMA PREDNOST'), ENT_QUOTES, 'UTF-8') ?></span><h2><?= htmlspecialchars(fcc_t('Vrijeme je za dogovoreno javljanje.'), ENT_QUOTES, 'UTF-8') ?></h2><?php foreach($n['due'] as $due): ?><a class="fp-link" href="<?= url('partner/contacts?id='.(int)$due['id']) ?>"><?= $h($due['name']) ?> · <?= $h($due['next_followup']) ?> →</a><?php endforeach ?><small><?= htmlspecialchars(fcc_t('Možeš prvo odraditi dogovor. U ovaj korak poveži ga samo ako odgovara kriteriju ispod.'), ENT_QUOTES, 'UTF-8') ?></small></section><?php endif ?>
<?php if($n['completed']===90): ?><section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Završio/la si 90 koraka.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Sačuvaj ritam koji ti odgovara: dogovorena javljanja, korisna preporuka, podrška i učenje. Tvoj napredak ostaje ovdje.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button" href="<?= url('partner/contacts?filter=due') ?>"><?= htmlspecialchars(fcc_t('Otvori svoje dogovore'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-link" href="<?= url('partner?view=progress') ?>"><?= htmlspecialchars(fcc_t('Ponovi vještinu iz svojeg pregleda →'), ENT_QUOTES, 'UTF-8') ?></a></section>
<?php elseif($n['daily_done']): ?><section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Za danas je spremljeno.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Sljedeći redovni korak otvara se sutra po zagrebačkom vremenu. Ostale dogovore možeš odraditi kad ti odgovara.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button" href="<?= url('partner?view=progress') ?>"><?= htmlspecialchars(fcc_t('Pogledaj svoj napredak'), ENT_QUOTES, 'UTF-8') ?></a></section>
<?php elseif($n['webinar']['is_today']): ?><section class="fp-panel"><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('WEBINAR ·'), ENT_QUOTES, 'UTF-8') ?> <?= $h($n['webinar']['time_label']) ?> <?= htmlspecialchars(fcc_t('· EUROPE/ZAGREB'), ENT_QUOTES, 'UTF-8') ?></span><h2><?= htmlspecialchars(fcc_t('Webinar i jedna korisna ideja.'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Pridruži se radi vlastitog učenja. Gost nije uvjet. Ovaj događaj ne preskače tvoj redovni korak'), ENT_QUOTES, 'UTF-8') ?> <?= $n['position'] ?>.</p><a class="fp-button" href="<?= url('partner/share?type=webinar') ?>"><?= htmlspecialchars(fcc_t('Otvori detalje webinara'), ENT_QUOTES, 'UTF-8') ?></a>
<?php if($n['webinar']['can_record_outcome']): ?><form method="post" class="fp-form"><?= $fields('webinar') ?><label><?= htmlspecialchars(fcc_t('Kako si sudjelovao/la?'), ENT_QUOTES, 'UTF-8') ?><select name="learning_mode" data-is-not-custom-select><option value="applied"><?= htmlspecialchars(fcc_t('Sudjelovao/la sam'), ENT_QUOTES, 'UTF-8') ?></option><option value="practice"><?= htmlspecialchars(fcc_t('Prošao/la sam dostupni materijal'), ENT_QUOTES, 'UTF-8') ?></option></select></label><label><?= htmlspecialchars(fcc_t('Jedna korisna ideja'), ENT_QUOTES, 'UTF-8') ?><textarea name="note" required maxlength="500"></textarea></label><label class="fp-check-label"><input type="checkbox" name="self_check" value="1" required> <?= htmlspecialchars(fcc_t('Potvrđujem sudjelovanje ili prolazak dostupnog materijala.'), ENT_QUOTES, 'UTF-8') ?></label><button class="fp-button"><?= htmlspecialchars(fcc_t('Spremi osvrt na webinar'), ENT_QUOTES, 'UTF-8') ?></button></form><?php else: ?><p><?= htmlspecialchars(fcc_t('Potvrda se otvara nakon'), ENT_QUOTES, 'UTF-8') ?> <?= $h($n['webinar']['completion_available_at_display']) ?><?= htmlspecialchars(fcc_t('. Otvaranje linka nije potvrda prisustva.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?></section>
<?php elseif($v==='coach'&&$step): require THEME_PATH.'views/partner/journey-coach.php';
else: ?>
<section class="fp-panel j90-current" id="journey90-step"><div class="fj-step-meta"><span><?= htmlspecialchars(fcc_t('Korak'), ENT_QUOTES, 'UTF-8') ?> <?= $n['position'] ?> / 90</span><span><?= $h($c['core_label']) ?></span></div><h2><?= $h($c['title']) ?></h2><p class="fp-muted"><?= htmlspecialchars(fcc_t('Oko'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$c['variant']['estimated_minutes']['min'] ?>–<?= (int)$c['variant']['estimated_minutes']['max'] ?> <?= htmlspecialchars(fcc_t('minuta aktivnog rada · razina'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$c['variant']['level'] ?></p>
<?php if(in_array($c['core']??'',['Retention','Development'],true))require THEME_PATH.'views/partner/team-support-guide.php'; ?>
<ol class="j90-steps"><?php foreach($c['variant']['steps'] as $text): ?><li><?= $h($text) ?></li><?php endforeach ?></ol>
<?php if(!$step): ?><form method="post" class="fp-form"><?= $fields('open') ?><?php if((int)$cycle['accepted_level']>1): ?><label><?= htmlspecialchars(fcc_t('Današnja razina'), ENT_QUOTES, 'UTF-8') ?><select name="level" data-is-not-custom-select><?php for($l=1;$l<=(int)$cycle['accepted_level'];$l++): ?><option value="<?= $l ?>" <?= $l===(int)$cycle['accepted_level']?'selected':'' ?>><?= $h($levelNames[$l]) ?></option><?php endfor ?></select></label><small><?= htmlspecialchars(fcc_t('Lakši korak ne briše tvoju prihvaćenu razinu.'), ENT_QUOTES, 'UTF-8') ?></small><?php endif ?><button class="fp-button"><?= htmlspecialchars(fcc_t('Otvori korak i svoj primjer →'), ENT_QUOTES, 'UTF-8') ?></button></form>
<?php else: ?>
<?php if(!empty($draft['message'])): ?><details class="fj-history"><summary><?= htmlspecialchars(fcc_t('Pogledaj osnovni primjer'), ENT_QUOTES, 'UTF-8') ?></summary><?php endif ?><div class="j90-example"><span class="fp-eyebrow"><?= $h($c['communication']['label']) ?></span><p class="fp-muted"><?= $h($c['communication']['situation']) ?></p><blockquote><?= nl2br($h($j['material']['example'])) ?></blockquote></div><?php if(!empty($draft['message'])): ?></details><?php endif ?>
<?php if($c['communication']['personal_experience']): ?><details class="fj-history"><summary><?= htmlspecialchars(fcc_t('Dodaj svoje iskustvo ako ga imaš'), ENT_QUOTES, 'UTF-8') ?></summary><p><?= $h($c['communication']['personal_experience']['condition']) ?></p><p><?= $h($c['communication']['personal_experience']['message']) ?></p></details><?php endif ?>
<?php if($j['material']['video_id']): ?><div class="j90-video"><iframe src="https://player.vimeo.com/video/<?= rawurlencode($j['material']['video_id']) ?>" title="<?= htmlspecialchars(fcc_t('Video uz ovaj korak'), ENT_QUOTES, 'UTF-8') ?>" allow="fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe></div><?php endif ?>
<?php $resource=fcc_j90_catalog()['resources'][$c['variant']['primary_action']]; ?>
<div class="fp-actions"><a class="fp-button fp-button-outline" href="<?= url($resource['path']) ?>"><?= $h($resource['label']) ?> →</a><?php if($j['pro']): ?><a class="fp-link" href="<?= url('partner?view=coach') ?>"><?= htmlspecialchars(fcc_t('Doradi uz moj PRO Coach →'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?></div>
<?php if($j['pro']&&$c['communication']['composer']['kind']!=='none'): ?>
<div class="j90-composer" id="journey90-message"><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('PRO · TVOJA PORUKA'), ENT_QUOTES, 'UTF-8') ?></span><h3><?= htmlspecialchars(fcc_t('Uredi poruku i otvori WhatsApp.'), ENT_QUOTES, 'UTF-8') ?></h3>
<?php $composerUserId=(int)$this->user->user_id;$composerContent=$c;$composerDraft=array_merge($draft,array_intersect_key($data->values??[],array_flip(['message','article_id','country'])));$composerFormFields=$fields('draft');$composerDemo=false;require THEME_PATH.'views/partner/journey90-composer.php'; ?>
</div>
<?php endif ?>
<?php foreach($c['help_cards'] as $help): ?><details class="fj-history"><summary><?= $h($help['title']) ?></summary><p><?= $h($help['body']) ?></p></details><?php endforeach ?>
<details class="fj-history"><summary><?= htmlspecialchars(fcc_t('Uvježbaj ovu situaciju'), ENT_QUOTES, 'UTF-8') ?></summary><p><?= $h($c['practice']['instruction']) ?></p><p><?= $h($c['practice']['criterion']) ?></p></details>
<details class="fj-history"><summary><?= htmlspecialchars(fcc_t('Zašto ovaj korak?'), ENT_QUOTES, 'UTF-8') ?></summary><p><?= $h($c['why']) ?></p><?php if($c['why_repeat_from']): ?><p><?= htmlspecialchars(fcc_t('Sada nadograđuješ korake'), ENT_QUOTES, 'UTF-8') ?> <?= implode(', ',$c['why_repeat_from']) ?> <?= htmlspecialchars(fcc_t('novom situacijom i primjenom.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?></details>
<details class="fj-history"><summary><?= htmlspecialchars(fcc_t('Danas mi treba pomoć oko druge situacije'), ENT_QUOTES, 'UTF-8') ?></summary><p><?= htmlspecialchars(fcc_t('Kupcu možeš pomoći odmah, bez čekanja kasnijeg koraka. Takvu radnju zabilježi u Kontaktima; ovaj korak potvrdi samo ako je ispunjen njegov kriterij.'), ENT_QUOTES, 'UTF-8') ?></p><div class="fp-actions"><a class="fp-link" href="<?= url('partner/contacts') ?>"><?= htmlspecialchars(fcc_t('Kontakti i dogovori →'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-link" href="<?= url($j['pro']?'partner?view=coach&purpose=reply':'partner?view=materials') ?>"><?= $j['pro']?fcc_t('Opiši situaciju Coachu'):fcc_t('Otvori materijale') ?> →</a><a class="fp-link" href="<?= url('feedback-tickets') ?>"><?= htmlspecialchars(fcc_t('Pošalji svoje pitanje Podršci →'), ENT_QUOTES, 'UTF-8') ?></a></div></details>
<?php if($n['needs_help']): ?><div class="fj-access"><strong><?= htmlspecialchars(fcc_t('Olakšajmo sljedeći pokušaj.'), ENT_QUOTES, 'UTF-8') ?></strong><p><?= htmlspecialchars(fcc_t('Posljednji koraci bili su vježbe ili su ti bili teški. Kreni od jednog prikladnog pitanja kupca ili odaberi manju situaciju. Svoj konkretan zastoj možeš poslati Podršci.'), ENT_QUOTES, 'UTF-8') ?></p><a href="<?= url('feedback-tickets') ?>"><?= htmlspecialchars(fcc_t('Zatraži pomoć →'), ENT_QUOTES, 'UTF-8') ?></a></div><?php endif ?>
<form method="post" class="fp-form j90-completion" data-j90-completion><?= $fields('complete') ?><h3><?= htmlspecialchars(fcc_t('Zabilježi što je napravljeno.'), ENT_QUOTES, 'UTF-8') ?></h3><p><strong><?= htmlspecialchars(fcc_t('Kriterij:'), ENT_QUOTES, 'UTF-8') ?></strong> <?= $h($c['variant']['criterion']) ?></p>
<label><?= htmlspecialchars(fcc_t('Kako je prošao korak?'), ENT_QUOTES, 'UTF-8') ?><select name="learning_mode" data-is-not-custom-select data-j90-mode><option value="applied"><?= htmlspecialchars(fcc_t('Primijenio/la sam u svom radu'), ENT_QUOTES, 'UTF-8') ?></option><option value="practice"><?= htmlspecialchars(fcc_t('Uvježbao/la sam na primjeru'), ENT_QUOTES, 'UTF-8') ?></option></select></label>
<label><?= htmlspecialchars(fcc_t('Što je stvarno napravljeno?'), ENT_QUOTES, 'UTF-8') ?><select name="output_status" data-is-not-custom-select data-j90-output><?php foreach($c['variant']['allowed_output_statuses'] as $status): ?><option value="<?= $status ?>"><?= $h(['prepared'=>fcc_t('Pripremljen koristan materijal'),'sent'=>fcc_t('Poruka stvarno poslana'),'performed'=>fcc_t('Razgovor ili pomoć stvarno odrađeni'),'updated'=>fcc_t('Primijenjen ispravak'),'reviewed'=>fcc_t('Provjeren i primijenjen zaključak')][$status]) ?></option><?php endforeach ?><option value="practised" hidden disabled><?= htmlspecialchars(fcc_t('Vježba bez stvarnog kontakta'), ENT_QUOTES, 'UTF-8') ?></option></select></label>
<div data-j90-evidence hidden><label class="fp-check-label"><input type="checkbox" name="contact_permission" value="1"> <?= htmlspecialchars(fcc_t('Osoba je htjela informacije ili pomoć; radnja je stvarno odrađena.'), ENT_QUOTES, 'UTF-8') ?></label><details class="fj-history"><summary><?= htmlspecialchars(fcc_t('Poveži svoj kontakt ili već zabilježenu današnju radnju'), ENT_QUOTES, 'UTF-8') ?></summary><label><?= htmlspecialchars(fcc_t('Kontakt (neobvezno)'), ENT_QUOTES, 'UTF-8') ?><select name="contact_id" data-is-not-custom-select><option value=""><?= htmlspecialchars(fcc_t('Osoba odabrana u WhatsAppu / izvan FCC kontakata'), ENT_QUOTES, 'UTF-8') ?></option><?php foreach($data->contacts as $contact):if($contact['contact_permission']==='do_not_contact')continue; ?><option value="<?= (int)$contact['id'] ?>"><?= $h($contact['name']) ?></option><?php endforeach ?></select></label><label><?= htmlspecialchars(fcc_t('Postojeća radnja (neobvezno)'), ENT_QUOTES, 'UTF-8') ?><select name="interaction_id" data-is-not-custom-select><option value=""><?= htmlspecialchars(fcc_t('Spremi novu potvrdu uz ovaj korak'), ENT_QUOTES, 'UTF-8') ?></option><?php foreach($data->journey90_activities??[] as $activity): ?><option value="<?= (int)$activity['id'] ?>"><?= $h($activity['contact_name']?:fcc_t('Bez kontakta')) ?> · <?= $h($activity['created_at']) ?> <?= htmlspecialchars(fcc_t('UTC'), ENT_QUOTES, 'UTF-8') ?></option><?php endforeach ?></select></label><small><?= htmlspecialchars(fcc_t('Izaberi samo radnju koja odgovara ovom kriteriju. Jedan zapis vrijedi za jedan korak.'), ENT_QUOTES, 'UTF-8') ?></small></details>
<?php if($c['variant']['advanced_case_eligible']): ?><label class="fp-check-label"><input type="checkbox" name="advanced_case" value="1"> <?= htmlspecialchars(fcc_t('Odrađen napredni slučaj: razumio/la sam pitanje i obrazložio/la svoj odgovor.'), ENT_QUOTES, 'UTF-8') ?></label><label class="fp-check-label"><input type="checkbox" name="source_checked" value="1"> <?= htmlspecialchars(fcc_t('Provjerio/la sam odgovor prema izvoru ili uputi.'), ENT_QUOTES, 'UTF-8') ?></label><small><?= htmlspecialchars(fcc_t('Za napredni slučaj u bilješci kratko navedi razlog odgovora i što si provjerio/la.'), ENT_QUOTES, 'UTF-8') ?></small><?php endif ?></div>
<label><?= htmlspecialchars(fcc_t('Koliko ti je bilo zahtjevno?'), ENT_QUOTES, 'UTF-8') ?><select name="difficulty" data-is-not-custom-select><option value="easy"><?= htmlspecialchars(fcc_t('Lako'), ENT_QUOTES, 'UTF-8') ?></option><option value="ok" selected><?= htmlspecialchars(fcc_t('U redu'), ENT_QUOTES, 'UTF-8') ?></option><option value="hard"><?= htmlspecialchars(fcc_t('Teško'), ENT_QUOTES, 'UTF-8') ?></option></select></label>
<details class="fj-history"><summary><?= htmlspecialchars(fcc_t('Pomozi nam prilagoditi zadatke (neobvezno)'), ENT_QUOTES, 'UTF-8') ?></summary><label><?= htmlspecialchars(fcc_t('Koliko minuta aktivnog rada?'), ENT_QUOTES, 'UTF-8') ?><input type="number" name="active_minutes" min="1" max="180" placeholder="<?= htmlspecialchars(fcc_t('Bez čekanja odgovora'), ENT_QUOTES, 'UTF-8') ?>"></label><label><?= htmlspecialchars(fcc_t('Ako si odabrao/la vježbu, zašto?'), ENT_QUOTES, 'UTF-8') ?><select name="alternative_reason" data-is-not-custom-select><option value="other"><?= htmlspecialchars(fcc_t('Ne želim navesti / drugi razlog'), ENT_QUOTES, 'UTF-8') ?></option><option value="no_opportunity"><?= htmlspecialchars(fcc_t('Trenutačno nema prikladne prilike'), ENT_QUOTES, 'UTF-8') ?></option><option value="time"><?= htmlspecialchars(fcc_t('Imam malo vremena'), ENT_QUOTES, 'UTF-8') ?></option><option value="unclear"><?= htmlspecialchars(fcc_t('Treba mi jasniji primjer'), ENT_QUOTES, 'UTF-8') ?></option></select></label></details>
<label><?= htmlspecialchars(fcc_t('Moja kratka bilješka (neobvezno)'), ENT_QUOTES, 'UTF-8') ?><textarea name="note" rows="3" maxlength="500"><?= $h($data->values['note']??$draft['note']??'') ?></textarea></label><small><?= htmlspecialchars(fcc_t('Bez privatnih ili zdravstvenih podataka drugih osoba.'), ENT_QUOTES, 'UTF-8') ?></small>
<label class="fp-check-label"><input type="checkbox" name="self_check" value="1" required> <?= htmlspecialchars(fcc_t('Ispunio/la sam kriterij odabrane primjene ili prošao/la ponuđenu vježbu.'), ENT_QUOTES, 'UTF-8') ?></label><div class="fp-actions"><button class="fp-button"><?= htmlspecialchars(fcc_t('Spremi dovršeni korak'), ENT_QUOTES, 'UTF-8') ?></button><button type="submit" name="action" value="journey90_draft" formnovalidate class="fp-button fp-button-outline"><?= htmlspecialchars(fcc_t('Sačuvaj bilješku za kasnije'), ENT_QUOTES, 'UTF-8') ?></button></div></form>
<?php endif ?></section>
<?php endif ?>
<?php endif ?>
</div><script src="<?= ASSETS_FULL_URL ?>js/fcc-journey90.js?v=<?= filemtime(ASSETS_PATH.'js/fcc-journey90.js') ?>" defer></script>
