<?php defined('ALTUMCODE') || die(); $np=$data->notification_preferences; $push_mode=fcc_partner_push_mode(); $push_ready=in_array($push_mode,['enabled','phone_pilot'],true); ?>
<p class="fp-lead"><?= htmlspecialchars(fcc_t('Poruke sustava i tvoji podsjetnici na jednom mjestu. Otvori obavijest za sljedeći korak.'), ENT_QUOTES, 'UTF-8') ?></p>
<section class="fp-panel">
 <div class="fp-section-title fp-wrap-heading"><h2><?= htmlspecialchars(fcc_t('Tvoje obavijesti'), ENT_QUOTES, 'UTF-8') ?></h2><form method="post"><?= $token ?><input type="hidden" name="action" value="notifications_read"><button class="fp-text-button"><?= htmlspecialchars(fcc_t('Označi sve pročitanim'), ENT_QUOTES, 'UTF-8') ?></button></form></div>
 <?php if(!$data->inbox): ?><p><?= htmlspecialchars(fcc_t('Još nema poruka. Nove obavijesti pojavit će se automatski.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
 <div class="fp-inbox"><?php foreach($data->inbox as $n): $n=fcc_partner_notification_display($n); ?><article class="fp-notice <?= $n['read_at']?'':'is-unread' ?>"><div><small><?= $h(fcc_push_inbox_label($n)) ?> · <?= $h((new DateTimeImmutable($n['created_at'],new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Europe/Zagreb'))->format('d. m. Y. H:i')) ?> <?= $h(fcc_push_setting_copy('timezone')) ?></small><form method="post" data-notice-open><h3><?= $token ?><input type="hidden" name="action" value="notification_open"><input type="hidden" name="id" value="<?= (int)$n['id'] ?>"><button class="fp-text-button fp-notice-title"><?= $h($n['title']) ?></button></h3></form><p><?= $h($n['body']) ?></p></div><form method="post"><?= $token ?><input type="hidden" name="action" value="notification_read"><input type="hidden" name="id" value="<?= (int)$n['id'] ?>"><button class="fp-text-button" aria-label="<?= htmlspecialchars(fcc_t('Označi pročitano'), ENT_QUOTES, 'UTF-8') ?>" <?= $n['read_at']?'disabled':'' ?>><?= $n['read_at']?fcc_t('Pročitano'):'✓' ?></button></form></article><?php endforeach ?></div>
 <?php if(count($data->inbox)===40): ?><a class="fp-link" href="<?= url('partner/notifications?before='.(int)($data->inbox?end($data->inbox)['id']:0)) ?>"><?= htmlspecialchars(fcc_t('Starije poruke →'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?>
 <?php if(\Altum\Authentication::is_admin()): ?><a class="fp-link" href="<?= url('admin/internal-notifications') ?>"><?= htmlspecialchars(fcc_t('Izvorna administratorska povijest →'), ENT_QUOTES, 'UTF-8') ?></a><?php else: ?><a class="fp-link" href="<?= url('internal-notifications') ?>"><?= htmlspecialchars(fcc_t('Izvorna FCC povijest →'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?>
</section>
<details class="fp-panel" data-partner-push open id="preferences"><summary><?= htmlspecialchars(fcc_t('Obavijesti na uređaju i moje postavke'), ENT_QUOTES, 'UTF-8') ?></summary>
 <p><?= htmlspecialchars(fcc_t('Push se uključuje samo uz tvoju dozvolu. Dnevni zadatak, osobne obveze i dogovorena javljanja imaju jedan objedinjeni podsjetnik.'), ENT_QUOTES, 'UTF-8') ?> <a href="<?= url('partner?view=goal') ?>"><?= htmlspecialchars(fcc_t('Moj dnevni podsjetnik'), ENT_QUOTES, 'UTF-8') ?></a>.</p><p><?= $h(fcc_push_setting_copy('timing')) ?></p>
 
 <form method="post" data-push-form><?= $token ?><input type="hidden" name="action" value="push_subscribe"><input type="hidden" name="subscription"><button class="fp-button" type="button" data-push-enable><?= htmlspecialchars(fcc_t('Uključi na ovom uređaju'), ENT_QUOTES, 'UTF-8') ?></button></form><p role="status" class="fp-muted"></p>
 <?php if($push_ready): ?><form method="post" class="fp-spaced"><?= $token ?><input type="hidden" name="action" value="push_test"><button class="fp-button fp-button-outline"><?= htmlspecialchars(fcc_t('Pošalji mi probnu obavijest'), ENT_QUOTES, 'UTF-8') ?></button></form><p class="fp-muted"><?= $h(fcc_push_setting_copy('test')) ?></p><?php endif ?>
 <form method="post" class="fp-form"><?= $token ?><input type="hidden" name="action" value="notification_preferences"><label class="fp-check-label"><input type="checkbox" name="push" value="1" <?= $np['push']?'checked':'' ?>> <?= htmlspecialchars(fcc_t('Dopuštam push na povezanim uređajima'), ENT_QUOTES, 'UTF-8') ?></label>
 <input type="hidden" name="sound_version" value="1"><label class="fp-check-label"><input type="checkbox" name="sound" value="1" <?= $np['sound']?'checked':'' ?>><span><?= $h(fcc_push_setting_copy('sound')) ?><small><?= $h(fcc_push_setting_copy('sound_help')) ?></small></span></label>
 <?php require THEME_PATH.'views/partner/cc-preferences.php'; ?>
 <?php foreach(fcc_partner_notification_rules() as $key=>[$title,$desc]): if(in_array($key,['cc','team'],true)||($key==='admin'&&!\Altum\Authentication::is_admin())||(fcc_journey_enabled()&&in_array($key,['followup','tasks','education'],true)))continue; ?><label class="fp-check-label"><input type="checkbox" name="categories[]" value="<?= $key ?>" <?= !empty($np['categories'][$key])?'checked':'' ?>><span><?= $h($title) ?><small><?= $h($desc) ?></small></span></label><?php endforeach ?><button class="fp-button"><?= htmlspecialchars(fcc_t('Spremi postavke'), ENT_QUOTES, 'UTF-8') ?></button></form>
 <form method="post" class="fp-spaced"><?= $token ?><input type="hidden" name="action" value="push_disable"><button class="fp-button fp-button-outline"><?= htmlspecialchars(fcc_t('Isključi push na svim mojim uređajima'), ENT_QUOTES, 'UTF-8') ?></button></form>
</details>
<section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Dogovorena javljanja i zadaci'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Otvori aktualni popis prije sljedećeg razgovora.'), ENT_QUOTES, 'UTF-8') ?></p><div class="fp-actions"><a class="fp-button fp-button-outline" href="<?= url('partner/contacts?filter=due') ?>"><?= htmlspecialchars(fcc_t('Dospjela javljanja'), ENT_QUOTES, 'UTF-8') ?></a><a class="fp-button fp-button-outline" href="<?= url('partner') ?>"><?= htmlspecialchars(fcc_t('Moj današnji popis'), ENT_QUOTES, 'UTF-8') ?></a></div></section>

