<?php
if(PHP_SAPI!=='cli')exit(1);umask(0077);
try{
 define('ALTUMCODE',66);define('DEBUG',0);define('MYSQL_DEBUG',0);define('LOGGING',1);define('CACHE',0);require '/home/forevercardclub/public_html/app/init.php';Altum\Cache::initialize();
 if(DATABASE_NAME!=='forevercardclub_database')throw new RuntimeException('Wrong database');
 $pro=0;$free=0;foreach(fcc_partner_rows('SELECT user_id FROM users WHERE status=1 ORDER BY user_id') as $u){$uid=(int)$u['user_id'];if(fcc_pro_has_access($uid))$pro=$pro?:$uid;else $free=$free?:$uid;if($pro&&$free)break;}
 if(!$pro||!$free)throw new RuntimeException('Missing access verification account');
 $blocked=false;try{fcc_top_page($free,30,'');}catch(RuntimeException $e){$blocked=$e->getMessage()==='PRO required';}if(!$blocked)throw new RuntimeException('Free access check failed');
 $current=substr(fcc_partner_today(),0,7).'-01';$previous=(new DateTimeImmutable($current))->modify('-1 month')->format('Y-m-d');$default=fcc_top_page($pro,30,'');$now=fcc_top_page($pro,30,$current);
 if($default['month']!==$current||$now['month']!==$current)throw new RuntimeException('Month selection failed');
 if(array_keys($default['cards'])!==['total_active_cc','registrations','conversations','education','consistency']||array_keys($default['weekly'])!==['education'])throw new RuntimeException('Retired metrics still present');
 $counts=[];foreach([$default,fcc_top_page($pro,30,$previous)] as $page){$source=fcc_top_dataset(30,$page['month']);foreach($page['cards'] as $cat=>$card){if($card['count']!==count($source['lists'][$cat]))throw new RuntimeException('Aggregate mismatch');if($card['visible_count']!==count(array_filter($source['lists'][$cat],fn($r)=>$r['visible'])))throw new RuntimeException('Visibility mismatch');foreach($card['rows'] as $row){if(isset($row['entity'])||isset($row['uids']))throw new RuntimeException('Identifier exposed');if(in_array($cat,['personal_cc','total_active_cc'],true)&&$row['score']!==null)throw new RuntimeException('CC amount exposed');}$counts[$page['month']][$cat]=['positive'=>$card['count'],'visible'=>$card['visible_count']];}}
 $window=fcc_top_window(30);$versionParams=fcc_top_program_versions();
 $expectedEducation=[];foreach(fcc_partner_rows("SELECT o.recorded_by_user_id user_id,COUNT(DISTINCT s.id) n FROM forever_business_daily_outcomes o JOIN fcc_partner_journey_steps s ON s.id=o.journey_step_id AND s.cycle_id=o.journey_cycle_id AND s.user_id=o.recorded_by_user_id JOIN fcc_partner_journey_cycles c ON c.id=s.cycle_id AND c.user_id=s.user_id WHERE o.status='done' AND o.outcome_type='journey90' AND c.catalog_version IN (?,?,?,?) AND s.position BETWEEN 1 AND 90 AND o.sequence_position=s.position AND JSON_VALID(s.content_json)=1 AND JSON_UNQUOTE(JSON_EXTRACT(s.content_json,'$.id'))=o.action_key AND o.created_at>=? AND o.created_at<=? GROUP BY o.recorded_by_user_id",array_merge($versionParams,[$window['from'],$window['to']])) as $r)$expectedEducation[(int)$r['user_id']]=(int)$r['n'];
 $auditDataset=fcc_top_dataset(30,$current);foreach($auditDataset['users'] as $uid=>$u){if((int)($auditDataset['scores']['education'][$uid]??0)!==(int)($expectedEducation[$uid]??0))throw new RuntimeException('Program 90 completion mismatch');if((int)($auditDataset['scores']['consistency'][$uid]??0)>30)throw new RuntimeException('Active days exceed selected window');}
 foreach($auditDataset['lists']['total_active_cc'] as $ranked){if((float)$ranked['score']<=0)throw new RuntimeException('Nonpositive CC ranked');}
 if(count($default['cards']['total_active_cc']['rows'])!==min(10,$default['cards']['total_active_cc']['visible_count']))throw new RuntimeException('CC list length mismatch');
 $profiles=[];foreach(fcc_partner_rows('SELECT user_id,visible,version FROM fcc_top_profiles') as $p)$profiles[(int)$p['user_id']]=$p;
 $source=fcc_top_dataset(30,$current);$visible=0;$savedHidden=0;$privacyHidden=0;foreach($source['lists']['total_active_cc'] as $ranked){$fbo=$source['users'][$ranked['uids'][0]]['fbo'];if((float)$ranked['score']!==(float)$source['cc'][$fbo]['total_active_cc'])throw new RuntimeException('Activity source mismatch');}
 foreach($source['users'] as $uid=>$u){$p=$profiles[$uid]??null;$expected=(!$p||(int)$p['version']===0||(bool)$p['visible'])&&!$u['private'];if($u['visible']!==$expected)throw new RuntimeException('Effective visibility mismatch');if($u['visible'])$visible++;if($u['private'])$privacyHidden++;if($p&&(int)$p['version']>0&&!$p['visible'])$savedHidden++;}
 $schemaDefault=fcc_partner_one("SELECT COLUMN_DEFAULT d FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='fcc_top_profiles' AND COLUMN_NAME='visible'")['d'];if((string)$schemaDefault!=='1')throw new RuntimeException('Schema default mismatch');
 $result=['status'=>'verified','visibility_default'=>1,'active_accounts'=>count($source['users']),'visible_accounts'=>$visible,'explicit_hidden_accounts'=>$savedHidden,'existing_privacy_hidden_accounts'=>$privacyHidden,'at_utc'=>gmdate('c'),'cc_sync'=>$source['sync'],'cc_accounts'=>$source['cc_accounts'],'only_total_active_cc_ranked'=>true,'source_metric'=>'total_active_cc','positive_only_no_padding'=>true,'program90_only'=>true,'active_days_include_program_work'=>true,'program90_completions'=>array_sum($expectedEducation),'unique_active_days'=>array_sum($auditDataset['scores']['consistency']??[]),'retired_metrics_removed'=>true,'default_month'=>$default['month'],'explicit_current_month'=>$now['month'],'free_rank_access_denied'=>$blocked,'private_cc_protected'=>true,'category_counts'=>$counts,'heartbeat'=>fcc_partner_notification_config('heartbeat'),'feature_profiles'=>(int)fcc_partner_one('SELECT COUNT(*) n FROM fcc_top_profiles')['n'],'feature_notifications'=>(int)fcc_partner_one("SELECT COUNT(*) n FROM fcc_partner_notifications WHERE event_key LIKE 'top:%'")['n']];
 file_put_contents(__DIR__.'/result.json',json_encode($result,JSON_PRETTY_PRINT));
}catch(Throwable $e){file_put_contents(__DIR__.'/result.json',json_encode(['status'=>'error','error'=>$e->getMessage()]));exit(1);}
