<?php defined('ALTUMCODE') || die();
$n=$j['journey90'];$c=$n['content'];$cycle=$n['cycle'];$step=$n['step'];$draft=$n['draft']?:[];
$fields=function(string $op)use($token,$cycle,$step){return $token.'<input type="hidden" name="action" value="journey90_'.$op.'"><input type="hidden" name="request_key" value="'.bin2hex(random_bytes(16)).'"><input type="hidden" name="cycle_id" value="'.(int)$cycle['id'].'"><input type="hidden" name="cycle_version" value="'.(int)$cycle['version'].'"><input type="hidden" name="step_id" value="'.(int)($step['id']??0).'"><input type="hidden" name="draft_version" value="'.(int)($step['draft_version']??0).'">';};
$levelNames=array_column(fcc_j90_catalog($cycle['catalog_version'])['levels'],'label','level');
?>
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-partner-journey.css?v=<?= filemtime(ASSETS_PATH.'css/fcc-partner-journey.css') ?>">
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-journey90.css?v=<?= filemtime(ASSETS_PATH.'css/fcc-journey90.css') ?>">
<div class="fj j90" data-journey90>
<header class="fj-heading"><div><span class="fp-eyebrow">MOJ PUT · <?= $n['completed'] ?>/90 DOVRŠENO</span><h1><?= $h($n['completed']===90?'Tvoj 4 Core ritam':'Dobar dan, '.explode(' ',trim($this->user->name))[0].'.') ?></h1><p><?= $h($levelNames[(int)$cycle['accepted_level']]) ?></p></div><a class="fj-goal" href="<?= url('partner?view=goal') ?>">Moj cilj i tempo <small><?= (int)$p['minutes'] ?> min · Postavke →</small></a></header>
<nav class="fj-tabs" aria-label="Moj put"><?php foreach(['today'=>'Danas','progress'=>'Moj napredak','materials'=>'Materijali'] as $nav=>$label): ?><a href="<?= url('partner'.($nav==='today'?'':'?view='.$nav)) ?>" <?= $v===$nav||($nav==='today'&&in_array($v,['step','coach'],true))?'aria-current="page"':'' ?>><?= $label ?></a><?php endforeach ?></nav>
<?php if(!$n['enabled']): ?><section class="fp-panel"><h2>Program je privremeno u pregledu.</h2><p>Tvoj napredak ostaje sačuvan. Novi upisi trenutačno nisu uključeni.</p></section>
<?php elseif($n['paused']): ?><section class="fp-panel"><h2>Nastavi kad ti odgovara.</h2><p>Pauza traje do <?= $h($p['paused_until']) ?>. Vraćaš se na isti korak, bez nadoknađivanja propuštenih dana.</p><a class="fp-button" href="<?= url('partner?view=goal') ?>">Promijeni pauzu</a></section>
<?php elseif($j['intro']||empty($j['program']['state']['can_access_education'])): ?><section class="fp-panel"><h2>Provjeri pristup edukaciji.</h2><p>Tvoj ciklus i svi spremljeni koraci ostaju sačuvani.</p><a class="fp-button" href="<?= url($j['intro']?'partner?view=materials':'forever-business?classic=1') ?>">Nastavi provjeru</a></section>
<?php elseif($v==='progress'): ?>
<section class="fp-panel"><h2>Tvoje vještine i stvarne radnje</h2><div class="fj-stats"><div><strong><?= $n['completed'] ?>/90</strong><span>koraka u ovom programu</span></div><div><strong><?= count(array_filter($n['rows'],fn($r)=>$r['learning_mode']==='applied')) ?></strong><span>primjena prema tvojoj potvrdi</span></div><div><strong><?= count(array_filter($n['rows'],fn($r)=>$r['interaction_id'])) ?></strong><span>stvarnih komunikacija koje si potvrdio/la</span></div></div><p>Vježbe pomiču program naprijed. Primjena i stvarna komunikacija odvojeni su od kupnje, odgovora i CC bodova.</p>
<?php if($n['readiness']['proposed_level']): ?><form method="post" class="fp-form"><?= $fields('level') ?><input type="hidden" name="level" value="<?= $n['readiness']['proposed_level'] ?>"><h3>Spreman/na si isprobati sljedeću razinu.</h3><p><?= $h($levelNames[$n['readiness']['proposed_level']]) ?>. Promjena vrijedi od sljedećeg neotvorenog koraka.</p><button class="fp-button">Prihvati sljedeću razinu</button></form>
<?php elseif((int)$cycle['accepted_level']<4): $rr=$n['readiness']; ?><details class="fj-history"><summary>Što se gleda za sljedeću razinu?</summary><p>U zadnjih <?= $rr['rule']['window'] ?> koraka: <?= $rr['counts']['applied'] ?>/<?= $rr['rule']['min_applied'] ?> primjena, <?= $rr['counts']['external'] ?>/<?= $rr['rule']['min_external'] ?> stvarnih komunikacija i <?= $rr['counts']['cores'] ?>/<?= $rr['rule']['min_cores'] ?> Core područja.</p><p>Ukupno je potrebno <?= $rr['rule']['min_completed'] ?> koraka<?= $rr['rule']['min_advanced']?' i dva napredna stvarna slučaja':'' ?>. CC nije uvjet promjene edukacijske razine. Svih 90 koraka možeš završiti na osnovnoj razini.</p></details><?php endif ?>
<details class="fj-history"><summary>CC · izvor i svježina podataka</summary><?php foreach($n['cc'] as $cc): ?><p><strong><?= $h(substr($cc['period'],0,7)) ?> · <?= $cc['personal_cc']===null?'—':$h(number_format($cc['personal_cc'],3,',','.')) ?> osobnih CC</strong><br><?= $h(['verified'=>'Provjereno','pending'=>'Čeka potvrdu izvora','stale'=>'Čeka osvježavanje','conflict'=>'Potrebna provjera','unavailable'=>'Nije dostupno'][$cc['status']]) ?> · Službeni 4 CC Active: <?= $cc['active']===null?'nije poznato':($cc['active']?'da':'ne') ?><br><small><?= $h($cc['reason']) ?><?= $cc['checked_at']?' Provjera: '.$h($cc['checked_at']):'' ?></small></p><?php endforeach ?><p>Učenje ne brišemo kad uvoz kasni ili ispravi bodove. Klikove i poruke ne pretvaramo u narudžbe ili CC.</p></details>
<a class="fp-link" href="<?= url('forever-business?classic=1') ?>">Moji službeni CC podaci i vrijeme izvora →</a><a class="fp-link" href="<?= url('fcc-results') ?>">Moji klikovi 15+ / 50+ →</a></section>
<section class="fp-panel"><h2>Sačuvani koraci</h2><?php foreach(array_reverse($n['rows']) as $row): $snap=json_decode($row['content_json'],true); ?><details class="fj-history"><summary><?= (int)$row['sequence_position'] ?>. <?= $h($snap['title']) ?> · <?= $row['learning_mode']==='practice'?'Vježba':'Primjena' ?></summary><p><?= $h($row['action_date']) ?> · <?= $h($snap['core_label']) ?></p><p><?= $h($snap['variant']['criterion']) ?></p><?php if($row['note']): ?><p><?= nl2br($h($row['note'])) ?></p><?php endif ?><small>Verzija <?= $h($snap['catalog_version']) ?> · razina <?= (int)$snap['variant']['level'] ?></small></details><?php endforeach ?><?php $saved=fcc_partner_rows('SELECT s.position,s.content_json,s.draft_json,s.opened_at FROM fcc_partner_journey_steps s WHERE s.user_id=? AND s.draft_json IS NOT NULL ORDER BY s.id DESC LIMIT 90',[(int)$this->user->user_id]);if($saved): ?><h3>Moje korisne poruke</h3><?php foreach($saved as $savedRow):$dm=json_decode($savedRow['draft_json'],true);$ct=json_decode($savedRow['content_json'],true);if(empty($dm['message']))continue; ?><details class="fj-history"><summary><?= (int)$savedRow['position'] ?>. <?= $h($ct['title']) ?></summary><p><?= $h($ct['communication']['situation']) ?></p><blockquote><?= nl2br($h($dm['message'])) ?></blockquote><small><?= $h($dm['country']??'') ?> · Pripremljeno <?= $h($dm['prepared_at']??$savedRow['opened_at']) ?>. Prije ponovne uporabe provjeri aktualnost i osobu kojoj pišeš.</small><button class="fp-button fp-button-outline" type="button" data-copy="<?= $h($dm['message']) ?>">Kopiraj svoju poruku</button></details><?php endforeach;endif ?>
<a class="fp-link" href="<?= url('partner?view=history') ?>">Raniji planovi, savjeti i osvrti →</a><a class="fp-link" href="<?= url('partner?view=review') ?>">Moj tjedni osvrt →</a></section>
<?php else: ?>
<?php if($n['due']): ?><section class="j90-priority fp-panel"><span class="fp-eyebrow">TVOJ DOGOVOR IMA PREDNOST</span><h2>Vrijeme je za dogovoreno javljanje.</h2><?php foreach($n['due'] as $due): ?><a class="fp-link" href="<?= url('partner/contacts?id='.(int)$due['id']) ?>"><?= $h($due['name']) ?> · <?= $h($due['next_followup']) ?> →</a><?php endforeach ?><small>Možeš prvo odraditi dogovor. U ovaj korak poveži ga samo ako odgovara kriteriju ispod.</small></section><?php endif ?>
<?php if($n['completed']===90): ?><section class="fp-panel"><h2>Završio/la si 90 koraka.</h2><p>Sačuvaj ritam koji ti odgovara: dogovorena javljanja, korisna preporuka, podrška i učenje. Tvoj napredak ostaje ovdje.</p><a class="fp-button" href="<?= url('partner/contacts?filter=due') ?>">Otvori svoje dogovore</a><a class="fp-link" href="<?= url('partner?view=progress') ?>">Ponovi vještinu iz svojeg pregleda →</a></section>
<?php elseif($n['daily_done']): ?><section class="fp-panel"><h2>Za danas je spremljeno.</h2><p>Sljedeći redovni korak otvara se sutra po zagrebačkom vremenu. Ostale dogovore možeš odraditi kad ti odgovara.</p><a class="fp-button" href="<?= url('partner?view=progress') ?>">Pogledaj svoj napredak</a></section>
<?php elseif($n['webinar']['is_today']): ?><section class="fp-panel"><span class="fp-eyebrow">WEBINAR · <?= $h($n['webinar']['time_label']) ?> · EUROPE/ZAGREB</span><h2>Webinar i jedna korisna ideja.</h2><p>Pridruži se radi vlastitog učenja. Gost nije uvjet. Ovaj događaj ne preskače tvoj redovni korak <?= $n['position'] ?>.</p><a class="fp-button" href="<?= url('partner/share?type=webinar') ?>">Otvori detalje webinara</a>
<?php if($n['webinar']['can_record_outcome']): ?><form method="post" class="fp-form"><?= $fields('webinar') ?><label>Kako si sudjelovao/la?<select name="learning_mode" data-is-not-custom-select><option value="applied">Sudjelovao/la sam</option><option value="practice">Prošao/la sam dostupni materijal</option></select></label><label>Jedna korisna ideja<textarea name="note" required maxlength="500"></textarea></label><label class="fp-check-label"><input type="checkbox" name="self_check" value="1" required> Potvrđujem sudjelovanje ili prolazak dostupnog materijala.</label><button class="fp-button">Spremi osvrt na webinar</button></form><?php else: ?><p>Potvrda se otvara nakon <?= $h($n['webinar']['completion_available_at_display']) ?>. Otvaranje linka nije potvrda prisustva.</p><?php endif ?></section>
<?php elseif($v==='coach'&&$step): require THEME_PATH.'views/partner/journey-coach.php';
else: ?>
<section class="fp-panel j90-current" id="journey90-step"><div class="fj-step-meta"><span>Korak <?= $n['position'] ?> / 90</span><span><?= $h($c['core_label']) ?></span></div><h2><?= $h($c['title']) ?></h2><p class="fp-muted">Oko <?= (int)$c['variant']['estimated_minutes']['min'] ?>–<?= (int)$c['variant']['estimated_minutes']['max'] ?> minuta aktivnog rada · razina <?= (int)$c['variant']['level'] ?></p>
<?php if(in_array($c['core']??'',['Retention','Development'],true))require THEME_PATH.'views/partner/team-support-guide.php'; ?>
<ol class="j90-steps"><?php foreach($c['variant']['steps'] as $text): ?><li><?= $h($text) ?></li><?php endforeach ?></ol>
<?php if(!$step): ?><form method="post" class="fp-form"><?= $fields('open') ?><?php if((int)$cycle['accepted_level']>1): ?><label>Današnja razina<select name="level" data-is-not-custom-select><?php for($l=1;$l<=(int)$cycle['accepted_level'];$l++): ?><option value="<?= $l ?>" <?= $l===(int)$cycle['accepted_level']?'selected':'' ?>><?= $h($levelNames[$l]) ?></option><?php endfor ?></select></label><small>Lakši korak ne briše tvoju prihvaćenu razinu.</small><?php endif ?><button class="fp-button">Otvori korak i svoj primjer →</button></form>
<?php else: ?>
<?php if(!empty($draft['message'])): ?><details class="fj-history"><summary>Pogledaj osnovni primjer</summary><?php endif ?><div class="j90-example"><span class="fp-eyebrow"><?= $h($c['communication']['label']) ?></span><p class="fp-muted"><?= $h($c['communication']['situation']) ?></p><blockquote><?= nl2br($h($j['material']['example'])) ?></blockquote></div><?php if(!empty($draft['message'])): ?></details><?php endif ?>
<?php if($c['communication']['personal_experience']): ?><details class="fj-history"><summary>Dodaj svoje iskustvo ako ga imaš</summary><p><?= $h($c['communication']['personal_experience']['condition']) ?></p><p><?= $h($c['communication']['personal_experience']['message']) ?></p></details><?php endif ?>
<?php if($j['material']['video_id']): ?><div class="j90-video"><iframe src="https://player.vimeo.com/video/<?= rawurlencode($j['material']['video_id']) ?>" title="Video uz ovaj korak" allow="fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe></div><?php endif ?>
<?php $resource=fcc_j90_catalog()['resources'][$c['variant']['primary_action']]; ?>
<div class="fp-actions"><a class="fp-button fp-button-outline" href="<?= url($resource['path']) ?>"><?= $h($resource['label']) ?> →</a><?php if($j['pro']): ?><a class="fp-link" href="<?= url('partner?view=coach') ?>">Doradi uz moj PRO Coach →</a><?php endif ?></div>
<?php if($j['pro']&&$c['communication']['composer']['kind']!=='none'): ?>
<div class="j90-composer" id="journey90-message"><span class="fp-eyebrow">PRO · TVOJA PORUKA</span><h3>Uredi poruku i otvori WhatsApp.</h3>
<?php $composerUserId=(int)$this->user->user_id;$composerContent=$c;$composerDraft=array_merge($draft,array_intersect_key($data->values??[],array_flip(['message','article_id','country'])));$composerFormFields=$fields('draft');$composerDemo=false;require THEME_PATH.'views/partner/journey90-composer.php'; ?>
</div>
<?php endif ?>
<?php foreach($c['help_cards'] as $help): ?><details class="fj-history"><summary><?= $h($help['title']) ?></summary><p><?= $h($help['body']) ?></p></details><?php endforeach ?>
<details class="fj-history"><summary>Uvježbaj ovu situaciju</summary><p><?= $h($c['practice']['instruction']) ?></p><p><?= $h($c['practice']['criterion']) ?></p></details>
<details class="fj-history"><summary>Zašto ovaj korak?</summary><p><?= $h($c['why']) ?></p><?php if($c['why_repeat_from']): ?><p>Sada nadograđuješ korake <?= implode(', ',$c['why_repeat_from']) ?> novom situacijom i primjenom.</p><?php endif ?></details>
<details class="fj-history"><summary>Danas mi treba pomoć oko druge situacije</summary><p>Kupcu možeš pomoći odmah, bez čekanja kasnijeg koraka. Takvu radnju zabilježi u Kontaktima; ovaj korak potvrdi samo ako je ispunjen njegov kriterij.</p><div class="fp-actions"><a class="fp-link" href="<?= url('partner/contacts') ?>">Kontakti i dogovori →</a><a class="fp-link" href="<?= url($j['pro']?'partner?view=coach&purpose=reply':'partner?view=materials') ?>"><?= $j['pro']?'Opiši situaciju Coachu':'Otvori materijale' ?> →</a><a class="fp-link" href="<?= url('feedback-tickets') ?>">Pošalji svoje pitanje Podršci →</a></div></details>
<?php if($n['needs_help']): ?><div class="fj-access"><strong>Olakšajmo sljedeći pokušaj.</strong><p>Posljednji koraci bili su vježbe ili su ti bili teški. Kreni od jednog prikladnog pitanja kupca ili odaberi manju situaciju. Svoj konkretan zastoj možeš poslati Podršci.</p><a href="<?= url('feedback-tickets') ?>">Zatraži pomoć →</a></div><?php endif ?>
<form method="post" class="fp-form j90-completion" data-j90-completion><?= $fields('complete') ?><h3>Zabilježi što je napravljeno.</h3><p><strong>Kriterij:</strong> <?= $h($c['variant']['criterion']) ?></p>
<label>Kako je prošao korak?<select name="learning_mode" data-is-not-custom-select data-j90-mode><option value="applied">Primijenio/la sam u svom radu</option><option value="practice">Uvježbao/la sam na primjeru</option></select></label>
<label>Što je stvarno napravljeno?<select name="output_status" data-is-not-custom-select data-j90-output><?php foreach($c['variant']['allowed_output_statuses'] as $status): ?><option value="<?= $status ?>"><?= $h(['prepared'=>'Pripremljen koristan materijal','sent'=>'Poruka stvarno poslana','performed'=>'Razgovor ili pomoć stvarno odrađeni','updated'=>'Primijenjen ispravak','reviewed'=>'Provjeren i primijenjen zaključak'][$status]) ?></option><?php endforeach ?><option value="practised" hidden disabled>Vježba bez stvarnog kontakta</option></select></label>
<div data-j90-evidence hidden><label class="fp-check-label"><input type="checkbox" name="contact_permission" value="1"> Osoba je htjela informacije ili pomoć; radnja je stvarno odrađena.</label><details class="fj-history"><summary>Poveži svoj kontakt ili već zabilježenu današnju radnju</summary><label>Kontakt (neobvezno)<select name="contact_id" data-is-not-custom-select><option value="">Osoba odabrana u WhatsAppu / izvan FCC kontakata</option><?php foreach($data->contacts as $contact):if($contact['contact_permission']==='do_not_contact')continue; ?><option value="<?= (int)$contact['id'] ?>"><?= $h($contact['name']) ?></option><?php endforeach ?></select></label><label>Postojeća radnja (neobvezno)<select name="interaction_id" data-is-not-custom-select><option value="">Spremi novu potvrdu uz ovaj korak</option><?php foreach($data->journey90_activities??[] as $activity): ?><option value="<?= (int)$activity['id'] ?>"><?= $h($activity['contact_name']?:'Bez kontakta') ?> · <?= $h($activity['created_at']) ?> UTC</option><?php endforeach ?></select></label><small>Izaberi samo radnju koja odgovara ovom kriteriju. Jedan zapis vrijedi za jedan korak.</small></details>
<?php if($c['variant']['advanced_case_eligible']): ?><label class="fp-check-label"><input type="checkbox" name="advanced_case" value="1"> Odrađen napredni slučaj: razumio/la sam pitanje i obrazložio/la svoj odgovor.</label><label class="fp-check-label"><input type="checkbox" name="source_checked" value="1"> Provjerio/la sam odgovor prema izvoru ili uputi.</label><small>Za napredni slučaj u bilješci kratko navedi razlog odgovora i što si provjerio/la.</small><?php endif ?></div>
<label>Koliko ti je bilo zahtjevno?<select name="difficulty" data-is-not-custom-select><option value="easy">Lako</option><option value="ok" selected>U redu</option><option value="hard">Teško</option></select></label>
<details class="fj-history"><summary>Pomozi nam prilagoditi zadatke (neobvezno)</summary><label>Koliko minuta aktivnog rada?<input type="number" name="active_minutes" min="1" max="180" placeholder="Bez čekanja odgovora"></label><label>Ako si odabrao/la vježbu, zašto?<select name="alternative_reason" data-is-not-custom-select><option value="other">Ne želim navesti / drugi razlog</option><option value="no_opportunity">Trenutačno nema prikladne prilike</option><option value="time">Imam malo vremena</option><option value="unclear">Treba mi jasniji primjer</option></select></label></details>
<label>Moja kratka bilješka (neobvezno)<textarea name="note" rows="3" maxlength="500"><?= $h($data->values['note']??$draft['note']??'') ?></textarea></label><small>Bez privatnih ili zdravstvenih podataka drugih osoba.</small>
<label class="fp-check-label"><input type="checkbox" name="self_check" value="1" required> Ispunio/la sam kriterij odabrane primjene ili prošao/la ponuđenu vježbu.</label><div class="fp-actions"><button class="fp-button">Spremi dovršeni korak</button><button type="submit" name="action" value="journey90_draft" formnovalidate class="fp-button fp-button-outline">Sačuvaj bilješku za kasnije</button></div></form>
<?php endif ?></section>
<?php endif ?>
<?php endif ?>
</div><script src="<?= ASSETS_FULL_URL ?>js/fcc-journey90.js?v=<?= filemtime(ASSETS_PATH.'js/fcc-journey90.js') ?>" defer></script>
