<?php defined('ALTUMCODE') || die();
$t=$data->team; $p=$t['profile']; $subject=$p?(int)$p['user_id']:$uid;
$outreach=$p&&$subject!==(int)($t['shared_primary']['user_id']??$uid)?fcc_team_outreach_page($uid,$subject):null;
\Altum\Event::add_content('<link rel="stylesheet" href="'.ASSETS_FULL_URL.'css/fcc-team.css?v='.filemtime(ASSETS_PATH.'css/fcc-team.css').'">','head');
?>
<div class="ft-header"><div><span class="fp-eyebrow">LJUDI I ZAJEDNIČKI NAPREDAK</span><h1><?= $p?$h($p['name']):'Moj tim' ?></h1><p class="fp-lead"><?= $p?'Napredak, rezultati i vaš sljedeći dogovor.':'Tvoja linija, podrška i mali uspjesi na jednom mjestu.' ?></p></div><div class="fp-filter-row"><a class="fp-button fp-button-outline" href="<?= url('partner') ?>">Moj današnji korak</a><a class="fp-link" href="<?= url('partner/share?type=webinar') ?>">Pozovi na webinar →</a></div></div>
<?php if(!$t['ready']): ?><section class="fp-panel"><p>Timsko povezivanje još nije uključeno.</p></section><?php return; endif ?>
<?php if($t['shared_primary']): ?><div class="ft-shared-account"><strong>Zajednička struktura</strong><span>Pregled dijeliš s glavnim računom <?= $h($t['shared_primary']['name']) ?>. Suradnicima se prikazuju njegovi kontaktni podaci.</span></div><?php endif ?>
<?php if($p): ?><a class="fp-link" href="<?= url('partner/team') ?>">← Moj tim</a><?php endif ?>
<?php $sponsor=$p?$p['sponsor']:$t['sponsor']; $firstManager=$p?$p['first_manager']:$t['first_manager']; ?>
<div class="ft-intro">
 <section class="ft-sponsor">
  <?php if($p): ?>
   <span class="fp-eyebrow">KONTAKT S TVOJIM SURADNIKOM</span><h2><?= $h($p['name']) ?></h2><p>Jedan osobni razgovor može biti koristan sljedeći korak.</p>
   <?php if($p['phone']): ?><a class="ft-phone" href="tel:<?= $h($p['phone']) ?>"><?= $h($p['phone']) ?></a><div class="fp-filter-row"><a class="fp-button fp-button-light" href="<?= url('partner/team'.($p?'?member='.$subject:'').'#team-work') ?>">Napiši WhatsApp poruku</a><a class="fp-link" aria-label="<?= $h('Nazovi '.$p['name']) ?>" href="tel:<?= $h($p['phone']) ?>">Nazovi</a></div><?php else: ?><p>Poslovni broj još nije dostupan. Poruku možeš pripremiti i kopirati za osobno javljanje.</p><a class="fp-button fp-button-light" href="<?= url('partner/team'.($p?'?member='.$subject:'').'#team-work') ?>">Pripremi poruku</a><?php endif ?>
  <?php elseif($sponsor): ?>
   <?php $supportPeople=[[$sponsor,$sponsor['is_manager']?'IZRAVNI SPONZOR I PRVI MENADŽER':'IZRAVNI SPONZOR']];
   if($firstManager&&$firstManager['user_id']!==$sponsor['user_id']) $supportPeople[]=[$firstManager,'PRVI MENADŽER U LINIJI'];
   foreach($supportPeople as [$person,$role]): ?>
   <div class="ft-support-person">
    <span class="fp-eyebrow"><?= $h($role) ?></span>
    <h2><?= $h($person['name']) ?></h2><p><?= $person['is_manager']?'Podrška za razvoj i zajednički rad':'Podrška za tvoj sljedeći korak' ?></p>
    <?php if($person['phone']): $message='Bok! Trebam pomoć oko svojeg sljedećeg koraka u FCC-u. Možemo li dogovoriti kratak razgovor?'; ?>
    <a class="ft-phone" href="tel:<?= $h($person['phone']) ?>"><?= $h($person['phone']) ?></a>
    <div class="fp-filter-row"><a class="fp-button fp-button-light" target="_blank" rel="noopener" aria-label="<?= $h('Otvori WhatsApp za '.$person['name']) ?>" href="https://wa.me/<?= $h(preg_replace('/\D/','',$person['phone'])) ?>?text=<?= rawurlencode($message) ?>">Otvori WhatsApp</a><a class="fp-link" aria-label="<?= $h('Nazovi '.$person['name']) ?>" href="tel:<?= $h($person['phone']) ?>">Nazovi</a></div>
    <?php else: ?><p>Poslovni telefon još nije dostupan. Pomoć možete dogovoriti u rubrici Zajednički rad.</p><?php endif ?>
   </div>
   <?php endforeach ?>
   <?php if(!$firstManager&&!$sponsor['is_manager']): ?><p class="ft-manager-pending">Prvi menadžer prikazat će se nakon potvrde ostatka tvoje linije.</p><?php endif ?>
   <?php if(!$p): ?><a class="fp-link" href="<?= url('partner/team'.($p?'?member='.$subject:'').'#team-work') ?>">Zatraži pomoć →</a><?php endif ?>
  <?php else: ?><span class="fp-eyebrow">MOJ SPONZOR</span><h2>Povežimo tvoju liniju.</h2><p>Administrator potvrđuje sponzora pri odobravanju ili uređivanju računa.</p><a class="fp-button fp-button-light" href="<?= url('feedback-tickets') ?>">Zatraži povezivanje</a><?php endif ?>
 </section>
 <section class="fp-panel ft-info">
  <?php if($p): ?><span class="fp-eyebrow">INFORMATIVNI PROFIL</span><h2><?= $h($p['name']) ?></h2><p>Forever ID: <?= $h($p['fbo_id']) ?></p><?php if($sponsor): ?><p>Izravni sponzor: <strong><?= $h($sponsor['name']) ?></strong><?php if($firstManager&&$firstManager['user_id']!==$sponsor['user_id']): ?><br>Prvi menadžer: <?= $h($firstManager['name']) ?><?php endif ?></p><?php endif ?><p>Prikaz obuhvaća napredak i zbirne rezultate. Zajednički dogovori dostupni su njihovim sudionicima.</p>
  <?php else: ?><span class="fp-eyebrow">TVOJA LINIJA</span><h2><?= (int)$t['total'] ?> <?= $t['total']===1?'suradnik u pregledu':'suradnika u pregledu' ?></h2><p><?= $t['full_structure']?'Vidiš cijelu povezanu strukturu, uključujući menadžere i njihove grane.':'Vidiš svoju povezanu liniju do prvog menadžera.' ?> Zajednički Forever ID prikazuje se jednom. Obavijesti o uspjesima ostaju vezane uz izravnog sponzora.</p><a class="fp-link" href="<?= url('partner/notifications') ?>">Obavijesti i postavke →</a>
  <?php endif ?>
 </section>
</div>
<?php if($p): $m=$p['metrics']; ?>

<div class="ft-metrics">
 <?php foreach([['Završeni koraci',$m['steps']],['Potvrđena slanja',$m['sent']],['Kvalificirani klikovi',$m['clicks']],['Potvrđene prijave',$m['verified_registrations']]] as [$label,$count]): ?><div><span><?= $h($label) ?></span><strong><?= (int)$count ?></strong><small>Posljednjih <?= (int)$m['days'] ?> dana</small></div><?php endforeach ?>
</div>
<section class="fp-panel"><div class="fp-section-title"><h2>Napredak u programu Moj put</h2><strong><?= (int)$m['progress'] ?> / 90 koraka</strong></div><progress class="ft-progress" value="<?= min(90,(int)$m['progress']) ?>" max="90" aria-label="Završeni koraci"></progress><p><?= $m['cycle_status']==='not_started'?'Program još nije započet.':($m['paused_until']>=fcc_partner_today()?'Pauza do '.$h($m['paused_until']):'Napredak u trenutačnom ciklusu.') ?></p>
 <?php if(count($m['account_progress'])>1): ?><div class="ft-account-progress"><?php foreach($m['account_progress'] as $account): ?><p><?= $h($account['name']) ?>: <?= (int)$account['progress'] ?> / 90 koraka</p><?php endforeach ?></div><small>Koraci programa pripadaju pojedinom računu. Statistike slanja i prijava obuhvaćaju potvrđene zajedničke račune.</small><?php endif ?></section>
<section class="fp-panel ft-cc-panel"><div class="fp-section-title"><h2>Bodovi iz FLP360</h2><?php if($m['cc']): ?><span class="ft-status"><?= $h(substr($m['cc']['period_month'],0,7)) ?></span><?php endif ?></div>
 <?php if($m['cc']): ?><div class="ft-cc-values"><?php foreach(['personal_cc'=>'Osobni CC','total_cc'=>'Ukupni CC','total_active_cc'=>'Aktivni CC'] as $field=>$label): ?><div><span><?= $h($label) ?></span><strong><?= $m['cc'][$field]===null?'Nema podatka':$h(number_format($m['cc'][$field],3,',','.')) ?></strong></div><?php endforeach ?></div><p class="fp-muted">Sinkronizirano <?= $h($m['cc']['updated_at']) ?> UTC. <?= $m['cc']['stale']?'Stariji podatak, provjeri nakon sljedeće sinkronizacije.':'' ?></p><?php else: ?><p>CC podatak još nije dostupan iz sinkronizacije.</p><?php endif ?><small>CC vrijedi za navedeni Forever ID i mjesec. Ne potvrđuje kupnju preko određene FCC poveznice. Ukupni CC različitih dubina mogu se preklapati.</small></section>
<section class="fp-panel"><h2>Poveznice i pozivi</h2><p>Pripremljeno: <?= (int)$m['prepared'] ?>. Slanja koja je potvrdio suradnik: <?= (int)$m['sent'] ?>. Zaprimljene prijave: <?= (int)$m['registrations'] ?>, od toga potvrđen email: <?= (int)$m['verified_registrations'] ?>.</p>
 <?php if(!$p['links']): ?><p class="fp-muted">Još nema zabilježenih poziva za prikaz.</p><?php endif ?>
 <?php foreach($p['links'] as $link): ?><div class="ft-link-row"><div><strong><?= $h($link['title']) ?></strong><small><?= $link['kind']==='business'?'Prezentacija':'Webinar' ?> · <?= $h($link['prepared_at']) ?> UTC · <?= $link['sent_at']?'Slanje je potvrdio suradnik':'Poziv je pripremljen' ?></small></div><span><?= (int)$link['registrations'] ?> <?= $link['kind']==='business'?'upita':'prijava' ?></span></div><?php endforeach ?>
 <small>Prikazano je do 20 najnovijih poziva i prezentacija. Otvaranje WhatsAppa nije potvrda slanja. Prijava ne potvrđuje dolazak na webinar.</small></section>
<?php else: ?>
<section class="fp-panel">
 <div class="fp-section-title"><h2>Suradnici u tvojoj liniji</h2><span><?= (int)$t['total'] ?></span></div>
 <form method="get" class="ft-filters"><label>Pronađi suradnika<input type="search" name="q" value="<?= $h($t['search']) ?>" placeholder="Ime ili Forever ID"></label><label>Dubina<select name="depth" data-is-not-custom-select><option value="0">Cijela dopuštena linija</option><?php for($i=1;$i<=10;$i++): ?><option value="<?= $i ?>" <?= $t['depth']===$i?'selected':'' ?>><?= $i===1?'Izravni suradnici':'Dubina '.$i ?></option><?php endfor ?></select></label><label>Razdoblje<select name="days" data-is-not-custom-select><?php foreach([7,30] as $d): ?><option value="<?= $d ?>" <?= $t['days']===$d?'selected':'' ?>><?= $d ?> dana</option><?php endforeach ?></select></label><button class="fp-button">Prikaži</button></form>
 <?php if(!$t['members']): ?><div class="ft-empty"><h3><?= $t['search']?'Nema rezultata za ovu pretragu.':'Tvoj tim čeka prvo povezivanje.' ?></h3><p>Nakon potvrde sponzora povezani suradnici i njihov napredak pojavit će se ovdje.</p></div><?php endif ?>
 <div class="ft-member-list"><?php foreach($t['members'] as $member): $m=$member['metrics']; ?><a class="ft-member" href="<?= url('partner/team?member='.(int)$member['user_id'].'&days='.$t['days']) ?>"><div class="ft-person"><span class="fp-contact-initial"><?= $h(mb_substr($member['name'],0,1)) ?></span><div><h3><?= $h($member['name']) ?></h3><small><?= $member['depth']===1?'Izravni suradnik':'Dubina '.(int)$member['depth'] ?> · <?= $member['manager']?'Menadžer · ':'' ?>Sponzor: <?= $h($member['sponsor_name']) ?></small><small class="ft-member-identity"><?= $h($member['fbo_id']) ?><?= count($member['account_ids'])>1?' · Zajednički račun':'' ?></small></div></div><div class="ft-member-activity"><div class="ft-member-numbers"><span><b><?= (int)$m['progress'] ?>/90</b> koraka</span><span><b><?= (int)$m['sent'] ?></b> slanja</span><span><b><?= (int)$m['clicks'] ?></b> klikova</span><span><b><?= (int)$m['verified_registrations'] ?></b> prijava</span></div><div class="ft-member-cc"><?php if($m['cc']): ?><span>Osobni CC <b><?= $m['cc']['personal_cc']===null?'Nema podatka':$h(number_format($m['cc']['personal_cc'],3,',','.')) ?></b></span><span>Ukupni CC <b><?= $m['cc']['total_cc']===null?'Nema podatka':$h(number_format($m['cc']['total_cc'],3,',','.')) ?></b></span><small><?= $h(substr($m['cc']['period_month'],0,7)) ?><?= $m['cc']['stale']?' · Stariji podatak':'' ?></small><?php else: ?><small>CC još nije dostupan</small><?php endif ?></div></div><span aria-hidden="true">→</span></a><?php endforeach ?></div>
 <div class="fp-filter-row"><?php if($t['page']>1): ?><a class="fp-link" href="<?= url('partner/team?'.http_build_query(['q'=>$t['search'],'depth'=>$t['depth'],'days'=>$t['days'],'page'=>$t['page']-1])) ?>">← Prethodni</a><?php endif ?><?php if($t['page']*20<$t['total']): ?><a class="fp-link" href="<?= url('partner/team?'.http_build_query(['q'=>$t['search'],'depth'=>$t['depth'],'days'=>$t['days'],'page'=>$t['page']+1])) ?>">Sljedeći →</a><?php endif ?></div>
</section>
<?php endif ?>
<section class="fp-panel" id="team-work"><div class="fp-section-title"><h2><?= $p?'Podrška i osobno javljanje':'Zajednički rad' ?></h2><span class="fp-muted">Razgovor, jedan korak i nastavak</span></div>
 <?php if($outreach)require THEME_PATH.'views/partner/team-outreach.php'; ?>
 <?php if(!$p)require THEME_PATH.'views/partner/team-outreach-due.php'; ?>
 <?php if(!$p&&$t['work_inbox']): ?><div class="ft-work-inbox"><h3>Suradnici čekaju zajednički korak</h3><?php foreach($t['work_inbox'] as $incoming): ?><a class="ft-member" href="<?= url('partner/team?member='.(int)$incoming['member_user_id'].'#team-work') ?>"><div><strong><?= $h($incoming['member_name']) ?></strong><p><?= $h($incoming['title']) ?></p><small><?= $incoming['due_date']?'Sljedeće javljanje: '.$h($incoming['due_date']):'Dogovorite termin' ?></small></div><span aria-hidden="true">→</span></a><?php endforeach ?></div><?php endif ?>
 <?php if($subject!==$uid||$t['upline']): ?>
 <details <?= !$p&&!$t['work']?'open':'' ?>><summary>Novi dogovor ili zahtjev za pomoć</summary><form method="post" class="fp-form ft-work-form"><?= $token ?><input type="hidden" name="action" value="team_work"><input type="hidden" name="team_operation" value="create"><input type="hidden" name="member_id" value="<?= $subject ?>"><?= $request ?>
 <label>Tema<input name="title" maxlength="180" required placeholder="Npr. priprema prvog poziva na webinar"></label>
 <div class="fp-form-grid"><label>Sljedeće javljanje<input name="due_date" type="date"></label>
 <?php if($subject===$uid): ?><label>S kim želiš raditi?<select name="collaborator_id" data-is-not-custom-select><?php foreach($t['upline'] as $person): ?><option value="<?= (int)$person['user_id'] ?>"><?= $h($person['name']) ?></option><?php endforeach ?></select></label><?php else: ?><p>Dogovor između tebe i suradnika <?= $h($p['name']) ?>.</p><?php endif ?></div>
 <input type="hidden" name="assignee_id" value="<?= $subject ?>"><button class="fp-button">Spremi dogovor</button></form></details>
 <?php else: ?><p>Nakon povezivanja sponzora ovdje možeš zatražiti pomoć i dogovoriti sljedeći korak.</p><?php endif ?>
 <?php foreach($t['work'] as $work): ?>
 <article class="ft-work"><div class="fp-section-title"><h3><?= $h($work['title']) ?></h3><span class="ft-status"><?= ['open'=>'Otvoreno','in_progress'=>'U tijeku','done'=>'Dovršeno'][$work['status']] ?></span></div><p><?= $h($work['collaborator_name']) ?> · Odgovorna osoba: <?= $h($work['assignee_name']) ?><?php if($work['due_date']): ?> · <?= $h($work['due_date']) ?><?php endif ?></p>
 <details><summary>Dogovor i bilješke</summary><form method="post" class="ft-filters"><?= $token ?><input type="hidden" name="action" value="team_work"><input type="hidden" name="team_operation" value="update"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><input type="hidden" name="version" value="<?= (int)$work['version'] ?>"><input type="hidden" name="request_key" value="<?= bin2hex(random_bytes(16)) ?>">
 <label>Status<select name="status" data-is-not-custom-select><?php foreach(['open'=>'Otvoreno','in_progress'=>'U tijeku','done'=>'Dovršeno'] as $value=>$label): ?><option value="<?= $value ?>" <?= $value===$work['status']?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label><label>Datum<input type="date" name="due_date" value="<?= $h($work['due_date']??'') ?>"></label><label>Odgovorna osoba<select name="assignee_id" data-is-not-custom-select><option value="<?= (int)$work['member_user_id'] ?>" <?= $work['assignee_user_id']===$work['member_user_id']?'selected':'' ?>>Suradnik</option><option value="<?= (int)$work['collaborator_user_id'] ?>" <?= $work['assignee_user_id']===$work['collaborator_user_id']?'selected':'' ?>><?= $h($work['collaborator_name']) ?></option></select></label><button class="fp-button fp-button-outline">Spremi</button></form>
 <?php if($work['shared_contact']): ?><div class="ft-shared"><strong>Kontakt podijeljen za ovaj dogovor</strong><p><?= $h($work['shared_contact']['name']) ?> · <?= $h($work['shared_contact']['phone']) ?> · <?= $h($work['shared_contact']['email']) ?></p></div><?php endif ?>
 <?php if((int)$work['member_user_id']===$uid): ?><form method="post" class="fp-form"><?= $token ?><input type="hidden" name="action" value="team_work"><input type="hidden" name="team_operation" value="contact"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><input type="hidden" name="version" value="<?= (int)$work['version'] ?>"><input type="hidden" name="request_key" value="<?= bin2hex(random_bytes(16)) ?>"><label>Podijeli ime i kontaktne podatke za ovaj dogovor<select name="contact_id" data-is-not-custom-select><option value="0">Bez podijeljenog kontakta</option><?php foreach(fcc_partner_rows("SELECT id,name FROM fcc_partner_contacts WHERE user_id=? AND contact_permission<>'do_not_contact' ORDER BY name",[$uid]) as $contact): ?><option value="<?= (int)$contact['id'] ?>" <?= (int)$work['shared_contact_id']===(int)$contact['id']?'selected':'' ?>><?= $h($contact['name']) ?></option><?php endforeach ?></select></label><button class="fp-button fp-button-outline">Spremi dijeljenje</button></form><?php endif ?>
 <?php foreach($work['notes'] as $note): ?><div class="ft-note"><small><?= $h($note['name']) ?> · <?= $h($note['created_at']) ?> UTC</small><p><?= nl2br($h($note['body'])) ?></p></div><?php endforeach ?>
 <form method="post" class="fp-form"><?= $token ?><input type="hidden" name="action" value="team_work"><input type="hidden" name="team_operation" value="note"><input type="hidden" name="work_id" value="<?= (int)$work['id'] ?>"><input type="hidden" name="request_key" value="<?= bin2hex(random_bytes(16)) ?>"><label>Zajednička bilješka<textarea name="body" rows="2" maxlength="1500" required placeholder="Što ste dogovorili i koji je sljedeći korak?"></textarea></label><button class="fp-button fp-button-outline">Dodaj bilješku</button></form></details>
 </article><?php endforeach ?>
</section>
<?php if(!$p&&$t['contact']): ?><details class="fp-panel"><summary>Moj poslovni kontakt za suradnike</summary><form method="post" class="fp-form"><?= $token ?><input type="hidden" name="action" value="team_contact"><input type="hidden" name="team_version" value="<?= (int)$t['contact']['version'] ?>"><label>Telefon<input type="tel" name="team_phone" value="<?= $h($t['contact']['phone']) ?>" placeholder="+385…" maxlength="30"></label><label class="fp-check-label"><input type="checkbox" name="team_contact_confirmed" value="1" <?= $t['contact']['contact_confirmed']?'checked':'' ?>> Dopuštam prikaz ovog poslovnog telefona povezanim suradnicima</label><button class="fp-button">Spremi kontakt</button></form></details><?php endif ?>
