<?php defined('ALTUMCODE') || die();
$t='fcc_top_t';$h='fcc_partner_h';$top=$data->top??null;
\Altum\Event::add_content('<link rel="stylesheet" href="'.ASSETS_FULL_URL.'css/fcc-top.css?v='.filemtime(ASSETS_PATH.'css/fcc-top.css').'">','head');
?>
<section class="ft-hero"><div><span class="fp-eyebrow">FCC · PRO</span><h1><?= $h($t('title')) ?></h1><p><?= $h($t('intro')) ?></p></div><a class="fp-button fp-button-light" href="<?= url('partner/settings#fcc-top-settings') ?>"><?= $h($t('settings')) ?></a></section>
<?php if(!$top): ?><p class="fp-message" role="status"><?= $h($t('unavailable')) ?></p><?php return;endif ?>
<form class="ft-filters" method="get"><label><?= $h($t('period')) ?><select name="days" data-is-not-custom-select><?php foreach([7,30,60] as $n): ?><option value="<?= $n ?>" <?= $top['days']===$n?'selected':'' ?>><?= $h($t('days',['{n}'=>$n])) ?></option><?php endforeach ?></select></label><label><?= $h($t('cc_month')) ?><select name="month" data-is-not-custom-select><?php foreach($top['months'] as $m): ?><option value="<?= $h($m) ?>" <?= $top['month']===$m?'selected':'' ?>><?= $h(substr($m,5,2).'/'.substr($m,0,4)) ?></option><?php endforeach ?></select></label><button class="fp-button" type="submit"><?= $h($t('apply')) ?></button></form>
<p class="ft-status"><?= $h($top['sync']?$t('sync',['{at}'=>fcc_cc_time($top['sync'])]):$t('awaiting')) ?><br><?= $h($t('freshness',['{at}'=>fcc_cc_time($top['at'])])) ?></p>
<section class="fp-panel ft-progress"><div class="fp-section-title"><h2><?= $h($t('progress')) ?></h2><span class="ft-private"><?= $h($t('private_label')) ?></span></div><div class="ft-goals"><?php foreach($top['weekly'] as $key=>$value): $goal=(int)$top['profile'][$key.'_goal']; ?><div><span><?= $h($t($key)) ?></span><strong><?= (int)$value ?> <small>/ <?= $goal ?></small></strong><progress value="<?= min($goal,$value) ?>" max="<?= $goal ?>" aria-label="<?= $h($t($key)) ?>"></progress></div><?php endforeach ?></div><a class="fp-link" href="<?= url('partner') ?>"><?= $h($t('start')) ?> →</a></section>
<div class="ft-grid"><?php foreach($top['cards'] as $key=>$card):$cc=in_array($key,['personal_cc','total_cc'],true); ?>
<section class="fp-panel ft-card"><div class="ft-card-head"><span class="ft-icon" aria-hidden="true"><?= fcc_partner_icon($cc?'chart':($key==='education'?'book':'people')) ?></span><div><span class="fp-eyebrow"><?= $cc?$h(substr($top['month'],5,2).'/'.substr($top['month'],0,4)):$h($t('days',['{n}'=>$top['days']])) ?></span><h2><?= $h($t($key)) ?></h2></div></div>
<div class="ft-own"><div><span><?= $h($t('own')) ?></span><strong><?= $card['own']['score']===null?'…':($cc?fcc_cc_number($card['own']['score']).' CC':(int)$card['own']['score']) ?></strong></div><div class="ft-own-rank"><?php if($card['own']['position']!==null): ?><span><?= $h($t('own_rank',['{n}'=>$card['own']['position']])) ?></span><?php else: ?><span><?= $h($t('no_score')) ?></span><?php endif ?><?php if($card['own']['movement']!==null): ?><small><?= $h($t('rank_change',['{date}'=>$card['own']['comparison_day'],'{n}'=>($card['own']['movement']>0?'+':'').$card['own']['movement']])) ?></small><?php endif ?></div></div>
<?php if(!$card['rows']): ?><div class="ft-empty"><span aria-hidden="true">✦</span><p><?= $h($t($card['count']?'empty':'no_activity')) ?></p></div><?php else: ?><ol class="ft-list" aria-label="<?= $h($t($key)) ?>"><?php foreach($card['rows'] as $row): ?><li value="<?= (int)$row['position'] ?>" class="<?= $row['own']?'ft-is-me':'' ?>"><span class="ft-place <?= $row['position']<=3?'ft-medal':'' ?>" aria-hidden="true"><?= (int)$row['position'] ?></span><span class="ft-name"><?= $h($row['name']) ?><?php if($row['own']): ?><small><?= $h($t('you')) ?></small><?php endif ?></span><?php if($cc): ?><span class="ft-hidden" aria-label="<?= $h($t('private_cc')) ?>" title="<?= $h($t('private_cc')) ?>"><span aria-hidden="true">••••</span></span><?php else: ?><strong class="ft-score"><?= (int)$row['score'] ?></strong><?php endif ?></li><?php endforeach ?></ol><?php endif ?>
<details class="ft-rules"><summary><?= $h($t('rules')) ?></summary><p><?= $h($t($key.'_help')) ?></p></details></section><?php endforeach ?></div>
<aside class="fp-panel ft-explanation"><h2><?= $h($t('rules')) ?></h2><p><?= $h($t('privacy')) ?></p><p><?= $h($t('cc_privacy')) ?></p><a class="fp-link" href="<?= url('fcc-results') ?>"><?= $h(fcc_t('FCC Rezultati')) ?> · 15+ / 50+ →</a></aside>
