<?php defined('ALTUMCODE') || die();
$h='fcc_partner_h';$pro=fcc_pro_has_access((int)$this->user->user_id);$local=getenv('FCC_LOCAL')==='1';
$demoAvailable=$local&&in_array($this->user->email,['suradnik@fcc.test','drugi@fcc.test','admin@fcc.test'],true);
$extra=is_string($this->user->extra??null)?json_decode($this->user->extra):($this->user->extra??(object)[]);
$demo=$this->user->preferences->partner_demo_subscription??(object)[];
$cancelled=!empty($extra->billing_cancel_at_period_end)||($local&&!empty($demo->cancel_at_period_end));
$billing=(array)($data->billing_summary??[]);$recovery=(array)($data->billing_recovery??[]);
$ended=in_array((string)($billing['stripe_status']??$extra->billing_stripe_status??''),['canceled','incomplete_expired'],true);
$subscription=!$ended&&trim((string)($this->user->payment_subscription_id??''))!=='';
$attention=in_array((string)($billing['billing_state']??''),['past_due','past_due_critical','access_revoked'],true);
$cancelled=$cancelled||$ended;
$until=(string)($extra->billing_current_period_end??$this->user->plan_expiration_date??'');
$plan=$data->suggested_plan??null;foreach((new \Altum\Models\Plan())->get_plans() as $candidate) if(!$plan&&(int)$candidate->status===1&&!empty($candidate->settings->ai_growth_plan_is_enabled)) {$plan=$candidate;break;}
$monthly=$plan->prices->monthly->{currency()}??null;
$untilLabel='';try{if($until)$untilLabel=(new DateTimeImmutable($until))->format('d. m. Y.');}catch(Throwable $e){}
$featureKey=is_string($_GET['feature']??null)?$_GET['feature']:'';
$requestedFeature=fcc_pro_features()[$featureKey]??null;
?>
<div class="fp-page fp-package">
<?= \Altum\Alerts::output_alerts() ?>
<?php if($requestedFeature&&!$pro): ?><section class="fcc-pro-upgrade-banner" aria-labelledby="pro-feature-heading"><span class="fcc-pro-badge">PRO</span><h2 id="pro-feature-heading"><?= $h($requestedFeature['title']) ?></h2><p><?= $h($requestedFeature['description']) ?></p><p>Za ovu mogućnost potreban je aktivni PRO paket na tvojem računu.</p><a href="#fcc-plan-features">Pogledaj pogodnosti i aktivaciju →</a></section><?php endif ?>
<div class="fp-page-heading"><div><span class="fp-eyebrow">TVOJ PAKET</span><h1><?= $pro?'Više mogućnosti uz PRO.':'Dobar početak. Prostor za rast.' ?></h1><p>Isti paket vrijedi na FCC webu i u aplikaciji.</p></div><span class="fp-status"><?= $h($local?($pro?'PRO · lokalni pregled':'Free'):($this->user->plan->name??($pro?'PRO':'Free'))) ?></span></div>
<section class="fp-panel fp-package-status"><div><h2><?= $ended?'Pretplata je završena':($cancelled?'Obnova je isključena':($subscription?'Pretplata je aktivna':($pro?'PRO pristup je aktivan':'Trenutačno koristiš Free'))) ?></h2><p><?= $ended?'Pretplata se više ne obnavlja. Dostupne mogućnosti ovise o trenutačnom paketu.':($cancelled?'Paket ostaje dostupan do isteka razdoblja. Nakon toga nema nove obnove.':($subscription?'Pretplatom možeš upravljati i otkazati je ovdje.':'Nema aktivne automatske naplate.')) ?></p><?php if($pro&&$untilLabel): ?><small>Pristup do <?= $h($untilLabel) ?></small><?php endif ?></div><div class="fp-actions"><a class="fp-button fp-button-outline" href="<?= url('account-payments') ?>">Uplate i računi</a><?php if(!empty($data->stripe_portal_available)): ?><a class="fp-button fp-button-outline" href="<?= url('account-plan/stripe_portal') ?>">Kartica i Stripe postavke</a><?php endif ?></div></section>
<?php if($attention): ?><section id="billing-recovery" class="fp-panel fp-billing-attention"><h2>Naplata traži tvoju pažnju</h2><p>Posljednja naplata nije potvrđena. Provjeri način plaćanja i postojeći račun. Status pristupa prati se prema potvrdi Stripea.</p><?php if(!empty($billing['grace_until'])): ?><p>Rok za obnovu pristupa: <?= $h($billing['grace_until']) ?></p><?php endif ?><div class="fp-actions"><?php if(!empty($data->stripe_portal_available)): ?><a class="fp-button" href="<?= $h($data->stripe_portal_url??url('account-plan/stripe_portal')) ?>">Ažuriraj način plaćanja</a><?php endif ?><?php if(!empty($recovery['can_retry_now'])): ?><a class="fp-button fp-button-outline" href="<?= $h($data->stripe_retry_payment_url??url('account-plan/retry_stripe_payment'.\Altum\Csrf::get_url_query())) ?>" onclick="return confirm('Želiš li ponovno pokušati naplatiti postojeći račun?')">Ponovi naplatu računa</a><?php endif ?><?php if(!empty($recovery['hosted_invoice_url'])): ?><a class="fp-button fp-button-outline" href="<?= $h($recovery['hosted_invoice_url']) ?>" target="_blank" rel="noopener">Otvori Stripe račun</a><?php endif ?><a href="<?= url('feedback-tickets') ?>">Zatraži pomoć</a></div></section><?php endif ?>
<?php if($subscription&&!$cancelled): ?><section class="fp-panel fp-cancel-panel"><h2>Otkazivanje pretplate</h2><p>Isključi sljedeću obnovu. Otkazivanje se šalje Stripeu, a pristup ostaje do kraja tekućeg razdoblja.</p><details><summary class="fp-button fp-button-outline">Otkaži pretplatu</summary><form method="post" action="<?= url('account-plan/cancel_subscription') ?>"><input type="hidden" name="token" value="<?= $h(\Altum\Csrf::get()) ?>"><p>Potvrdi da želiš isključiti buduće obnove.</p><button class="fp-button">Potvrdi otkazivanje</button></form></details></section><?php endif ?>
<div id="fcc-plan-features" class="fp-package-grid">
<section class="fp-panel"><span class="fp-eyebrow">FREE · ZA POČETAK</span><h2>Tvoja digitalna osnova.</h2><p>Uredi karticu, podijeli preporuku i organiziraj svakodnevni rad.</p><ul><li>Osobna FCC kartica iz gotovog predloška</li><li>Osnovni kontakt i dijeljenje vlastite preporuke</li><li>Kontakti, dogovorena javljanja i osobni zadaci</li><li>Blog i proizvodi za dijeljenje</li><li>Rezultati i transparentan obračun klikova</li><li>Sinkronizacija vlastitih CC bodova i kontakt vlastitog sponzora</li><li>Edukacija prema uvjetima postojećeg programa</li></ul><a class="fp-button fp-button-outline" href="<?= url('partner/cards') ?>">Uredi svoju karticu</a></section>
<section class="fp-panel fp-package-pro"><span class="fp-eyebrow">PRO · ZA AKTIVNO POSLOVANJE</span><h2>Gotov sustav koji radi s tobom.</h2><p>Za suradnike koji redovito dijele sadržaj, prate upite i žele jasan plan rada.</p><ul><li>Osobni PRO Coach uz današnji zadatak, poruke i tjedni osvrt</li><li>Pregled strukture, CC bodova i napretka suradnika</li><li>Timske obavijesti, zajednički rad i preporuke Coacha</li><li>Funnel studio za prezentacije i upite</li><li>Video pozivnice i vlastiti webinari</li><li>Dodatne kartice i napredni blokovi prema PRO paketu</li><li>Aktivacija pogodnosti na postojećem predlošku</li><li>Svi osobni podaci i preporuke ostaju povezani</li><li>Jednostavno otkazivanje buduće obnove</li></ul><?php if($monthly&&!$local): ?><p class="fp-price"><?= $h(number_format((float)$monthly,2,',','.').' '.currency()) ?><small> / mjesec</small></p><?php endif ?><?php if($pro): ?><a class="fp-button" href="<?= url('partner?view=coach') ?>">Otvori PRO Coacha</a><?php elseif(!$local&&$plan&&settings()->payment->is_enabled): ?><a class="fp-button" href="<?= url('pay/'.$plan->plan_id) ?>">Aktiviraj PRO</a><?php elseif(!$local): ?><a class="fp-button" href="<?= url('feedback-tickets') ?>">Informacije o PRO paketu</a><?php endif ?></section>
</div>
<?php if($demoAvailable): ?><section class="fp-panel fp-local-package"><h2>Isprobaj Free i PRO lokalno</h2><p>Testni prikaz bez naplate i bez Stripe transakcije. Možeš isprobati aktivaciju i isključivanje obnove. Produkcijska cijena i pretplata preuzimat će se iz postojećeg FCC paketa.</p><div class="fp-actions"><?php foreach(['pro'=>'Aktiviraj testni PRO','cancel'=>'Isključi testnu obnovu','free'=>'Vrati testni Free'] as $mode=>$label): ?><form method="post" action="<?= url('partner/settings') ?>"><input type="hidden" name="token" value="<?= $h(\Altum\Csrf::get()) ?>"><input type="hidden" name="action" value="local_package"><input type="hidden" name="package" value="<?= $mode ?>"><button class="fp-button fp-button-outline"><?= $label ?></button></form><?php endforeach ?></div></section><?php endif ?>
<details class="fp-panel"><summary>Točne postavke mojeg paketa</summary><p>Prava se čitaju iz istog FCC paketa. Promjena paketa ne briše tvoje kartice, sadržaj ni kontakte.</p><?= (new \Altum\View('partials/plan_features'))->run(['plan_settings'=>$this->user->plan_settings]) ?></details>
</div>
