CREATE TABLE IF NOT EXISTS fcc_team_outreach (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 actor_user_id INT UNSIGNED NOT NULL,
 member_user_id INT UNSIGNED NOT NULL,
 access_signature CHAR(64) NOT NULL,
 request_key CHAR(32) NOT NULL,
 purpose VARCHAR(30) NOT NULL,
 source VARCHAR(16) NOT NULL DEFAULT 'manual',
 ai_status VARCHAR(16) NOT NULL DEFAULT 'ready',
 situation TEXT NOT NULL,
 message TEXT NOT NULL,
 guidance TEXT NOT NULL,
 model VARCHAR(100) NULL,
 opened_at DATETIME NULL,
 sent_self_reported_at DATETIME NULL,
 due_date DATE NULL,
 closed_at DATETIME NULL,
 outcome VARCHAR(1000) NOT NULL DEFAULT '',
 version INT UNSIGNED NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY outreach_request(actor_user_id,request_key),
 KEY outreach_member(actor_user_id,member_user_id,id),
 KEY outreach_due(actor_user_id,closed_at,due_date),
 KEY outreach_rate(actor_user_id,source,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
