<?php defined('ALTUMCODE') || die(); header('Cache-Control: no-store');
$install_url=url('partner/install');
$open_url=url(is_logged_in()?'partner':'login?redirect=partner');
?>
<!doctype html>
<html lang="<?= fcc_language_tag() ?>"><head><?php fcc_i18n_assets(); ?>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#155e51"><meta name="robots" content="noindex,follow"><base href="<?= SITE_URL ?>">
<link rel="manifest" href="<?= SITE_URL ?>partner-assets/manifest.php">
<link rel="apple-touch-icon" href="<?= SITE_URL ?>partner-assets/fcc-app-192.png">
<meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="FCC Partner">
<title><?= htmlspecialchars(fcc_t('Instaliraj FCC Partner'), ENT_QUOTES, 'UTF-8') ?></title>
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-partner.css?v=<?= filemtime(ASSETS_PATH.'css/fcc-partner.css') ?>">
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-partner-premium.css?v=<?= filemtime(ASSETS_PATH.'css/fcc-partner-premium.css') ?>">
<link rel="stylesheet" href="<?= ASSETS_FULL_URL ?>css/fcc-partner-install.css?v=<?= filemtime(ASSETS_PATH.'css/fcc-partner-install.css') ?>">
</head><body class="fcc-partner-mode"><main class="install-shell fp-page" data-install-page>
<a class="install-back" href="<?= $open_url ?>"><?= htmlspecialchars(fcc_t('← Povratak na FCC'), ENT_QUOTES, 'UTF-8') ?></a>
<header class="install-header"><img src="<?= SITE_URL ?>partner-assets/fcc-app-192.png" width="72" height="72" alt="<?= htmlspecialchars(fcc_t('FCC Partner'), ENT_QUOTES, 'UTF-8') ?>"><div><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('FOREVER CARD CLUB'), ENT_QUOTES, 'UTF-8') ?></span><h1><?= htmlspecialchars(fcc_t('FCC na tvojem telefonu.'), ENT_QUOTES, 'UTF-8') ?></h1></div></header>
<p class="fp-lead"><?= htmlspecialchars(fcc_t('Dodaj FCC na početni zaslon i otvaraj svoje kartice, kontakte i zadatke jednim dodirom. Koristiš isti FCC račun, bez preuzimanja iz trgovine aplikacija.'), ENT_QUOTES, 'UTF-8') ?></p>
<p class="fp-message" data-install-status hidden role="status"></p>
<div class="fp-actions install-actions"><button class="fp-button" type="button" data-install hidden><?= htmlspecialchars(fcc_t('Instaliraj FCC Partner'), ENT_QUOTES, 'UTF-8') ?></button><a class="fp-button fp-button-outline" data-install-open href="<?= $open_url ?>"><?= htmlspecialchars(fcc_t('Nastavi u pregledniku'), ENT_QUOTES, 'UTF-8') ?></a></div>
<div data-install-guide>
<section class="fp-panel install-device" data-install-device="ios"><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('IPHONE I IPAD'), ENT_QUOTES, 'UTF-8') ?></span><h2><?= htmlspecialchars(fcc_t('Dodaj ikonu u Safariju'), ENT_QUOTES, 'UTF-8') ?></h2><ol><li><?= htmlspecialchars(fcc_t('Otvori ovu poveznicu u'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Safariju'), ENT_QUOTES, 'UTF-8') ?></strong><?= htmlspecialchars(fcc_t('. Ako si je otvorio u WhatsAppu ili drugoj aplikaciji, odaberi otvaranje u pregledniku.'), ENT_QUOTES, 'UTF-8') ?></li><li><?= htmlspecialchars(fcc_t('Dodirni'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Dijeli'), ENT_QUOTES, 'UTF-8') ?></strong><?= htmlspecialchars(fcc_t(', kvadrat sa strelicom prema gore. Ovisno o izgledu Safarija, prvo otvori izbornik s tri točkice.'), ENT_QUOTES, 'UTF-8') ?></li><li><?= htmlspecialchars(fcc_t('Odaberi'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Dodaj na početni zaslon'), ENT_QUOTES, 'UTF-8') ?></strong><?= htmlspecialchars(fcc_t('. Ako vidiš opciju'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Otvori kao web aplikaciju'), ENT_QUOTES, 'UTF-8') ?></strong><?= htmlspecialchars(fcc_t(', ostavi je uključenu i potvrdi'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Dodaj'), ENT_QUOTES, 'UTF-8') ?></strong>.</li><li><?= htmlspecialchars(fcc_t('Otvori novu ikonu'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('FCC Partner'), ENT_QUOTES, 'UTF-8') ?></strong> <?= htmlspecialchars(fcc_t('i prijavi se svojim FCC računom ako se prijava zatraži.'), ENT_QUOTES, 'UTF-8') ?></li></ol><a class="install-source" href="https://support.apple.com/guide/iphone/iphea86e5236/ios" target="_blank" rel="noopener noreferrer"><?= htmlspecialchars(fcc_t('Appleove upute ↗'), ENT_QUOTES, 'UTF-8') ?></a></section>
<section class="fp-panel install-device" data-install-device="android"><span class="fp-eyebrow"><?= htmlspecialchars(fcc_t('ANDROID'), ENT_QUOTES, 'UTF-8') ?></span><h2><?= htmlspecialchars(fcc_t('Instaliraj iz Chromea'), ENT_QUOTES, 'UTF-8') ?></h2><ol><li><?= htmlspecialchars(fcc_t('Otvori ovu poveznicu u'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Chromeu'), ENT_QUOTES, 'UTF-8') ?></strong>.</li><li><?= htmlspecialchars(fcc_t('Dodirni'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Instaliraj FCC Partner'), ENT_QUOTES, 'UTF-8') ?></strong> <?= htmlspecialchars(fcc_t('ako se pojavi gumb. Možeš i otvoriti izbornik Chromea te odabrati'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Dodaj na početni zaslon'), ENT_QUOTES, 'UTF-8') ?></strong><?= htmlspecialchars(fcc_t(', zatim'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Instaliraj'), ENT_QUOTES, 'UTF-8') ?></strong>.</li><li><?= htmlspecialchars(fcc_t('Potvrdi instalaciju pa otvori FCC Partner i prijavi se svojim FCC računom.'), ENT_QUOTES, 'UTF-8') ?></li></ol><a class="install-source" href="https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DAndroid" target="_blank" rel="noopener noreferrer"><?= htmlspecialchars(fcc_t('Upute za Chrome ↗'), ENT_QUOTES, 'UTF-8') ?></a></section>
<details class="fp-panel install-other" data-install-other hidden><summary><?= htmlspecialchars(fcc_t('Upute za drugi uređaj'), ENT_QUOTES, 'UTF-8') ?></summary><div data-install-other-content></div></details>
<section class="fp-panel install-address"><h2><?= htmlspecialchars(fcc_t('Poveznica za tvoj telefon'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Otvori ovu adresu na telefonu na koji želiš dodati FCC.'), ENT_QUOTES, 'UTF-8') ?></p><a href="<?= e($install_url) ?>"><?= e($install_url) ?></a><button type="button" class="fp-button fp-button-outline" data-copy="<?= e($install_url) ?>"><?= htmlspecialchars(fcc_t('Kopiraj poveznicu'), ENT_QUOTES, 'UTF-8') ?></button></section>
</div>
<section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Prijava i pristup'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Već imaš odobren račun? Koristi isti email i lozinku. Instalacija ne stvara novi račun i tvoji podaci ostaju povezani.'), ENT_QUOTES, 'UTF-8') ?></p><?php if(getenv('FCC_LOCAL')!=='1'&&getenv('FCC_PARTNER_ROLLOUT')!=='all'&&!fcc_rollout_all_enabled()): ?><p><?= htmlspecialchars(fcc_t('Novi FCC trenutačno je dostupan odabranim suradnicima. Ako nakon prijave vidiš prethodni izgled, javi se administratoru radi provjere pristupa.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?><details><summary><?= htmlspecialchars(fcc_t('Još nemam FCC račun'), ENT_QUOTES, 'UTF-8') ?></summary><p><?= htmlspecialchars(fcc_t('Registriraj se na FCC webu i pričekaj odobrenje administratora. Nakon odobrenja koristi isti račun i u aplikaciji.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button fp-button-outline" href="<?= url('register') ?>"><?= htmlspecialchars(fcc_t('Registracija na FCC webu'), ENT_QUOTES, 'UTF-8') ?></a></details></section>
<section class="fp-panel"><h2><?= htmlspecialchars(fcc_t('Uključi obavijesti kad budeš spreman'), ENT_QUOTES, 'UTF-8') ?></h2><p><?= htmlspecialchars(fcc_t('Nakon prijave otvori zvono u aplikaciji, zatim'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Obavijesti na uređaju'), ENT_QUOTES, 'UTF-8') ?></strong> <?= htmlspecialchars(fcc_t('i'), ENT_QUOTES, 'UTF-8') ?> <strong><?= htmlspecialchars(fcc_t('Uključi na ovom uređaju'), ENT_QUOTES, 'UTF-8') ?></strong><?= htmlspecialchars(fcc_t('. Potvrdi dopuštenje telefona. Na iPhoneu to napravi u FCC aplikaciji otvorenoj s početnog zaslona, uz iOS 16.4 ili noviji.'), ENT_QUOTES, 'UTF-8') ?></p><a class="fp-button fp-button-outline" href="<?= url(is_logged_in()?'partner/notifications':'login?redirect=partner/notifications') ?>"><?= htmlspecialchars(fcc_t('Otvori obavijesti'), ENT_QUOTES, 'UTF-8') ?></a><p class="fp-muted"><?= htmlspecialchars(fcc_t('Za provjeru koristi gumb „Pošalji mi probnu obavijest”. Ako je slanje odgođeno zbog mirnog vremena ili ograničenja, aplikacija će to pokazati.'), ENT_QUOTES, 'UTF-8') ?></p></section>
<p class="fp-muted"><?= htmlspecialchars(fcc_t('Za rad treba internet. Podaci su isti na telefonu i računalu. Ažuriranja sadržaja vidiš pri ponovnom otvaranju. Ako imaš staru testnu ikonu s privremene adrese, ovu službenu aplikaciju dodaj zasebno.'), ENT_QUOTES, 'UTF-8') ?></p>
<?php if(getenv('FCC_PHONE_PILOT')==='1'): ?><div class="fp-message"><strong><?= htmlspecialchars(fcc_t('Privatni test na tvojem Macu.'), ENT_QUOTES, 'UTF-8') ?></strong> <?= htmlspecialchars(fcc_t('Mac i Docker moraju ostati uključeni. Ovaj test koristi privremenu adresu i nije produkcijska instalacija.'), ENT_QUOTES, 'UTF-8') ?></div><?php elseif(getenv('FCC_LOCAL')==='1'): ?><div class="fp-message"><?= htmlspecialchars(fcc_t('Ovo je lokalni pregled na računalu. Za iPhone pokreni „Pokreni FCC iPhone pregled.command” i otvori HTTPS adresu iz pripremljenih uputa. Localhost na telefonu ne označava ovo računalo.'), ENT_QUOTES, 'UTF-8') ?></div><?php endif ?>
</main><script defer src="<?= ASSETS_FULL_URL ?>js/fcc-partner-install.js?v=<?= filemtime(ASSETS_PATH.'js/fcc-partner-install.js') ?>"></script><script defer src="<?= ASSETS_FULL_URL ?>js/fcc-partner.js?v=<?= filemtime(ASSETS_PATH.'js/fcc-partner.js') ?>"></script></body></html>
