<?php defined('ALTUMCODE') || die();$h='fcc_partner_h';$base=url('admin/fcc-access');$token='<input type="hidden" name="token" value="'.$h(\Altum\Csrf::get()).'">';$labels=['initial'=>fcc_t('Postavi početni pristup'),'grant'=>fcc_t('Uključi novi FCC'),'revoke'=>fcc_t('Vrati pristup postojećem FCC-u'),'all'=>fcc_rollout_ui('all')]; ?>
<div class="container-fluid px-0">
 <h1 class="h3"><?= htmlspecialchars(fcc_t('Pristup novom FCC-u'), ENT_QUOTES, 'UTF-8') ?></h1><p><?= htmlspecialchars(fcc_rollout_ui('description'), ENT_QUOTES, 'UTF-8') ?></p>
 <?= \Altum\Alerts::output_alerts() ?>
 <?php if($data->error): ?><div class="alert alert-danger" role="alert"><?= $h($data->error) ?></div><?php endif ?>
 <?php if(!$data->ready): ?><div class="alert alert-info"><?= htmlspecialchars(fcc_t('Administracija pristupa bit će dostupna nakon primjene migracije 017.'), ENT_QUOTES, 'UTF-8') ?></div><?php else: ?>
 <div class="card mb-4"><div class="card-body"><strong><?= fcc_rollout_all_enabled()?fcc_rollout_ui('active'):(fcc_rollout_managed()?fcc_t('Pristup određuje administrator.'):fcc_t('Administratorski odabir još nije aktiviran.')) ?></strong><p class="mb-0"><?php if(getenv('FCC_PARTNER_ENABLED')!=='1'): ?><?= htmlspecialchars(fcc_t('Glavni prekidač novog FCC-a je isključen. Možeš unaprijed pripremiti odabir.'), ENT_QUOTES, 'UTF-8') ?><?php elseif(!fcc_rollout_managed()): ?><?= htmlspecialchars(fcc_t('Prva potvrđena promjena aktivirat će ovaj popis. Postojeća konfiguracija vrijedi do tada.'), ENT_QUOTES, 'UTF-8') ?><?php endif ?> <?= htmlspecialchars(fcc_t('Odabrano za novi FCC:'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$data->stats['new'] ?> <?= htmlspecialchars(fcc_t('od'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$data->stats['active'] ?> <?= htmlspecialchars(fcc_t('aktivnih računa. Aktivni administratori imaju pristup prema svojoj ulozi.'), ENT_QUOTES, 'UTF-8') ?></p></div></div>
 <?php if($data->preview): $p=$data->preview; ?>
 <section class="card mb-4 border-primary"><div class="card-body"><h2 class="h4"><?= htmlspecialchars(fcc_t('Pregled prije spremanja'), ENT_QUOTES, 'UTF-8') ?></h2><p><strong><?= $h($labels[$p['action']]) ?></strong><?= htmlspecialchars(fcc_t('. Obuhvaćeno računa:'), ENT_QUOTES, 'UTF-8') ?> <?= count($p['accounts']) ?>.</p>
 <?php if($p['action']==='all'): ?><p><?= htmlspecialchars(fcc_rollout_ui('preview'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
 <?php if($p['action']==='revoke'): ?><p><?= htmlspecialchars(fcc_t('Korisnici se vraćaju na postojeći radni prostor. Njihovi podaci, nova edukacija i već podijeljene javne poveznice ostaju sačuvani. Ponovno uključivanje nastavlja isti novi program.'), ENT_QUOTES, 'UTF-8') ?></p><?php endif ?>
 <div style="max-height:320px;overflow:auto"><ol><?php foreach($p['accounts'] as $u): ?><li><?= $h($u['name']) ?>, <?= $h($u['email']) ?><?= htmlspecialchars(fcc_t(', ID'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$u['user_id'] ?></li><?php endforeach ?></ol></div>
 <form method="post"><?= $token ?><input type="hidden" name="stage" value="confirm"><input type="hidden" name="request_key" value="<?= $h($p['key']) ?>"><div class="custom-control custom-checkbox my-3"><input class="custom-control-input" id="rollout-confirm" type="checkbox" name="confirmation" value="POTVRDI" required><label class="custom-control-label" for="rollout-confirm"><?= htmlspecialchars(fcc_t('Pregledao/la sam račune i želim spremiti ovu promjenu.'), ENT_QUOTES, 'UTF-8') ?></label></div><button class="btn btn-primary"><?= htmlspecialchars(fcc_t('Potvrdi promjenu'), ENT_QUOTES, 'UTF-8') ?></button> <a class="btn btn-outline-secondary" href="<?= $base ?>"><?= htmlspecialchars(fcc_t('Odustani'), ENT_QUOTES, 'UTF-8') ?></a></form></div></section>
 <?php endif ?>
 <?php if(empty(fcc_rollout_control()['managed'])): ?><details class="card mb-4"><summary class="card-header"><?= htmlspecialchars(fcc_t('Početni pristup za obitelj Beloša i administratore'), ENT_QUOTES, 'UTF-8') ?></summary><div class="card-body"><p><?= htmlspecialchars(fcc_t('Početni računi su'), ENT_QUOTES, 'UTF-8') ?> <?= $h(implode(' i ',fcc_rollout_seed_emails())) ?><?= htmlspecialchars(fcc_t(', njihovi aktivni povezani računi s istim Forever ID-em te aktivni administratori. Članovi sponzorske mreže nisu automatski uključeni.'), ENT_QUOTES, 'UTF-8') ?></p>
 <?php foreach(fcc_localize_copy(['missing'=>fcc_t('Nisu pronađeni aktivni računi'),'ambiguous'=>fcc_t('Potrebna je provjera istog emaila')]) as $k=>$title): if($data->plan[$k]): ?><p><?= $h($title) ?>: <?= $h(implode(', ',$data->plan[$k])) ?>.</p><?php endif; endforeach ?>
 <ol><?php foreach($data->plan['accounts'] as $u): ?><li><?= $h($u['name']) ?>, <?= $h($u['email']) ?>, <?= $h($u['reason']) ?></li><?php endforeach ?></ol>
 <form method="post"><?= $token ?><input name="action" value="initial" type="hidden"><label for="extra-emails"><?= htmlspecialchars(fcc_t('Dodatni potvrđeni računi, ako imaju drugi Forever ID'), ENT_QUOTES, 'UTF-8') ?></label><textarea id="extra-emails" name="extra_emails" class="form-control mb-3" rows="2" placeholder="<?= htmlspecialchars(fcc_t('Email svakog dodatnog računa'), ENT_QUOTES, 'UTF-8') ?>"><?= $h($data->extra) ?></textarea><button class="btn btn-outline-primary"><?= htmlspecialchars(fcc_t('Pregledaj početni pristup'), ENT_QUOTES, 'UTF-8') ?></button></form></div></details><?php endif ?>
 <form method="get" class="card mb-3"><div class="card-body"><div class="form-row"><div class="col-md-7"><label for="rollout-search"><?= htmlspecialchars(fcc_t('Pronađi suradnika'), ENT_QUOTES, 'UTF-8') ?></label><input id="rollout-search" name="q" class="form-control" value="<?= $h($data->q) ?>" placeholder="<?= htmlspecialchars(fcc_t('Ime, email ili ID računa'), ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-3"><label for="rollout-filter"><?= htmlspecialchars(fcc_t('Prikaz'), ENT_QUOTES, 'UTF-8') ?></label><select name="filter" id="rollout-filter" class="form-control"><?php foreach(['active'=>fcc_t('Svi aktivni'),'new'=>fcc_t('Novi FCC'),'old'=>fcc_t('Postojeći FCC'),'all'=>fcc_t('Svi računi')] as $k=>$v): ?><option value="<?= $k ?>" <?= $data->filter===$k?'selected':'' ?>><?= $v ?></option><?php endforeach ?></select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-outline-primary mt-3"><?= htmlspecialchars(fcc_t('Pronađi'), ENT_QUOTES, 'UTF-8') ?></button></div></div></div></form>
 <form method="post" class="card mb-4"><?= $token ?><div class="table-responsive"><table class="table mb-0"><thead><tr><th><?= htmlspecialchars(fcc_t('Odabir'), ENT_QUOTES, 'UTF-8') ?></th><th><?= htmlspecialchars(fcc_t('Suradnik'), ENT_QUOTES, 'UTF-8') ?></th><th><?= htmlspecialchars(fcc_t('Pristup'), ENT_QUOTES, 'UTF-8') ?></th><th><?= htmlspecialchars(fcc_t('Prvi ulazak'), ENT_QUOTES, 'UTF-8') ?></th></tr></thead><tbody>
 <?php foreach($data->rows as $u): $admin=(int)$u['type']>0;$active=(int)$u['status']===1;$allowed=$active&&($admin||$u['allowed']); ?><tr><td><?php if($active&&!$admin): ?><input type="checkbox" name="ids[]" value="<?= (int)$u['user_id'] ?>" aria-label="Odaberi <?= $h($u['name']) ?>"><?php endif ?></td><td><a href="<?= url('admin/user-view/'.(int)$u['user_id']) ?>"><?= $h($u['name']) ?></a><br><small><?= $h($u['email']) ?> <?= htmlspecialchars(fcc_t('· ID'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$u['user_id'] ?></small></td><td><span class="badge <?= $allowed?'badge-success':'badge-light' ?>"><?= !$active?fcc_t('Neaktivan račun'):($allowed?fcc_t('Novi FCC'):fcc_t('Postojeći FCC')) ?></span><?php if($admin): ?><br><small><?= htmlspecialchars(fcc_t('Administrator'), ENT_QUOTES, 'UTF-8') ?></small><?php endif ?></td><td><?= $h($u['first_entered_at']?$u['first_entered_at'].fcc_t(' UTC'):fcc_t('Još nije ušao/la')) ?></td></tr><?php endforeach ?>
 <?php if(!$data->rows): ?><tr><td colspan="4"><?= htmlspecialchars(fcc_t('Nema računa za ovaj odabir.'), ENT_QUOTES, 'UTF-8') ?></td></tr><?php endif ?></tbody></table></div><div class="card-body"><button name="action" value="grant" class="btn btn-primary mb-2"><?= htmlspecialchars(fcc_t('Uključi odabrane'), ENT_QUOTES, 'UTF-8') ?></button> <?php if(!fcc_rollout_all_enabled()): ?><button name="action" value="revoke" class="btn btn-outline-secondary mb-2"><?= htmlspecialchars(fcc_t('Vrati odabrane na postojeći FCC'), ENT_QUOTES, 'UTF-8') ?></button><?php endif ?><p class="mb-0"><?= htmlspecialchars(fcc_t('Svaka promjena najprije otvara pregled odabranih računa.'), ENT_QUOTES, 'UTF-8') ?></p></div></form>
 <nav aria-label="<?= htmlspecialchars(fcc_t('Stranice računa'), ENT_QUOTES, 'UTF-8') ?>"><p><?= htmlspecialchars(fcc_t('Pronađeno:'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$data->count ?><?= htmlspecialchars(fcc_t('. Stranica'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$data->page ?>. <?php if($data->page>1): ?><a href="<?= $base.'?'.$h(http_build_query(['q'=>$data->q,'filter'=>$data->filter,'page'=>$data->page-1])) ?>"><?= htmlspecialchars(fcc_t('Prethodna'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?> <?php if($data->count>$data->page*50): ?><a href="<?= $base.'?'.$h(http_build_query(['q'=>$data->q,'filter'=>$data->filter,'page'=>$data->page+1])) ?>"><?= htmlspecialchars(fcc_t('Sljedeća'), ENT_QUOTES, 'UTF-8') ?></a><?php endif ?></p></nav>
 <details class="card mb-4"><summary class="card-header"><?= htmlspecialchars(fcc_rollout_ui('all'), ENT_QUOTES, 'UTF-8') ?></summary><div class="card-body"><p><?= htmlspecialchars(fcc_rollout_ui('prepare'), ENT_QUOTES, 'UTF-8') ?></p><form method="post"><?= $token ?><button name="action" value="all" class="btn btn-outline-primary"><?= htmlspecialchars(fcc_t('Pregledaj sve račune'), ENT_QUOTES, 'UTF-8') ?></button></form></div></details>
 <details class="card"><summary class="card-header"><?= htmlspecialchars(fcc_t('Posljednje promjene pristupa'), ENT_QUOTES, 'UTF-8') ?></summary><div class="card-body"><ol><?php foreach($data->audit as $a): ?><li><?= $h($a['created_at']) ?> <?= htmlspecialchars(fcc_t('UTC,'), ENT_QUOTES, 'UTF-8') ?> <?= $h($a['actor']??'Administrator') ?>: <?= $h($labels[$a['action']]??$a['action']) ?><?= htmlspecialchars(fcc_t(', računa'), ENT_QUOTES, 'UTF-8') ?> <?= (int)$a['affected_count'] ?>.</li><?php endforeach ?></ol></div></details>
 <?php endif ?>
</div>
