<?php defined('ALTUMCODE') || die(); ?>
<div class="fcw-footer-main">
 <div class="fcw-footer-identity"><a class="fcw-brand" href="<?= e(fcc_public_url()) ?>"><img src="<?= e(settings()->main->logo_light_full_url ?: settings()->main->logo_dark_full_url) ?>" width="208" height="64" alt="Forever Card Club" loading="lazy"></a><p><?= e(fcc_public_copy('independent')) ?></p><p><?= e(fcc_public_copy('support')) ?><br><a href="mailto:info@forevercard.club">info@forevercard.club</a></p></div>
 <nav aria-label="<?= e(fcc_public_copy('guides')) ?>"><strong><?= e(fcc_public_copy('discover')) ?></strong><a href="<?= e(fcc_public_url('blog')) ?>"><?= e(fcc_public_copy('products')) ?></a><a href="<?= e(fcc_public_url('blog',['view'=>'articles'])) ?>"><?= e(fcc_public_copy('articles')) ?></a><a href="<?= e(fcc_public_url('pages')) ?>"><?= e(fcc_public_copy('guides')) ?></a><a href="<?= e(fcc_public_url('featured-apps')) ?>"><?= e(fcc_public_copy('all_cards')) ?></a><a href="<?= e(fcc_public_url('recommended-sponsors')) ?>"><?= e(fcc_public_copy('all_sponsors')) ?></a></nav>
 <nav aria-label="<?= e(fcc_public_copy('contact')) ?>"><strong>Forever Card Club</strong><a href="<?= e(fcc_public_url('page/contact')) ?>"><?= e(fcc_public_copy('contact')) ?></a><a href="<?= e(fcc_legal_url('privacy')) ?>"><?= e(fcc_public_copy('privacy')) ?></a><a href="<?= e(fcc_legal_url('terms')) ?>"><?= e(fcc_public_copy('terms')) ?></a><?php if(settings()->cookie_consent->is_enabled): ?><a href="#" data-cc="show-preferencesModal"><?= e(fcc_public_copy('cookies')) ?></a><?php endif ?>
 <?php foreach($data->pages ?? [] as $footer_page): ?><a href="<?= e($footer_page->url) ?>" target="<?= e($footer_page->target) ?>"<?= $footer_page->target==='_blank'?' rel="noopener noreferrer"':'' ?>><?= e($footer_page->title) ?></a><?php endforeach ?>
 </nav>
</div>
<div class="fcw-footer-bottom"><span>© <?= date('Y') ?> Forever Card Club</span><span>BS International · Velika Mlaka, Hrvatska</span></div>
