<?php defined('ALTUMCODE') || die(); ?>
<div class="fcw-home fcw-container" data-fcc-public-home>
 <section class="fcw-home-hero">
  <div class="fcw-hero-copy"><span class="fcw-eyebrow">FOREVER CARD CLUB</span><h1><?= e(fcc_public_copy('title')) ?></h1><p><?= e(fcc_public_copy('intro')) ?></p><div class="fcw-actions"><a class="fcw-button" href="<?= e(url(is_logged_in()?'partner':'login')) ?>"><?= e(fcc_public_copy('enter')) ?> <span aria-hidden="true">↗</span></a><a class="fcw-text-link" href="<?= e(fcc_public_url('blog')) ?>"><?= e(fcc_public_copy('explore')) ?> <span aria-hidden="true">→</span></a></div><div class="fcw-hero-note"><?= e(fcc_public_copy('eyebrow')) ?></div></div>
  <div class="fcw-welcome-panel"><span class="fcw-eyebrow"><?= e(fcc_public_copy('inside')) ?></span><h2><?= e(fcc_public_copy('today')) ?></h2><ol class="fcw-steps"><?php foreach(['step1','step2','step3'] as $step): ?><li><span><?= e(fcc_public_copy($step)) ?></span></li><?php endforeach ?></ol><div class="fcw-welcome-note"><?= e(fcc_public_copy('inside_note')) ?></div><span class="fcw-orbit" aria-hidden="true"></span></div>
 </section>
 <section class="fcw-section" id="fcc-discover"><header class="fcw-section-heading"><span class="fcw-eyebrow"><?= e(fcc_public_copy('discover')) ?></span><h2><?= e(fcc_public_copy('system')) ?></h2><p><?= e(fcc_public_copy('system_intro')) ?></p></header><div class="fcw-feature-grid"><?php foreach(['card'=>'card','contacts'=>'people','learning'=>'book','coach'=>'spark'] as $feature=>$icon): ?><article class="fcw-feature"><span class="fcw-feature-icon" aria-hidden="true"><?= fcc_partner_icon($icon) ?></span><h3><?= e(fcc_public_copy($feature)) ?></h3><p><?= e(fcc_public_copy($feature.'_text')) ?></p></article><?php endforeach ?></div></section>
 <section class="fcw-section"><header class="fcw-section-heading"><span class="fcw-eyebrow"><?= e(fcc_public_copy('library')) ?></span><h2><?= e(fcc_public_copy('library_title')) ?></h2><p><?= e(fcc_public_copy('library_intro')) ?></p></header><div class="fcw-explore-grid"><?php foreach(['products'=>fcc_public_url('blog'),'articles'=>fcc_public_url('blog',['view'=>'articles']),'about'=>fcc_public_url('pages/foreverclub')] as $key=>$href): ?><a class="fcw-explore-card" href="<?= e($href) ?>"><span class="fcw-eyebrow">FCC</span><h3><?= e(fcc_public_copy($key)) ?></h3><p><?= e(fcc_public_copy($key.'_text')) ?></p><span class="fcw-card-arrow" aria-hidden="true">↗</span></a><?php endforeach ?></div></section>
 <?php foreach(['featured_cards'=>['cards','all_cards','featured-apps'],'recommended_sponsors'=>['sponsors','all_sponsors','recommended-sponsors']] as $field=>$labels): if(empty($data->{$field}))continue; ?>
 <section class="fcw-section"><header class="fcw-section-heading"><span class="fcw-eyebrow">Forever Card Club</span><h2><?= e(fcc_public_copy($labels[0])) ?></h2></header><div class="fcw-people-grid"><?php foreach($data->{$field} as $person): ?><article class="fcw-person"><img src="<?= e(fcc_fast_image_url($person['display_image_url']?:$person['default_image_url'])) ?>" alt="" width="72" height="72" loading="lazy"><h3><?= e($person['name']) ?></h3><p><?= e($person['public_summary']) ?></p><a class="fcw-text-link" href="<?= e($person['app_url']) ?>"><?= e(fcc_public_copy('read')) ?> →</a></article><?php endforeach ?></div><a class="fcw-text-link" href="<?= e(fcc_public_url($labels[2])) ?>"><?= e(fcc_public_copy($labels[1])) ?> →</a></section>
 <?php endforeach ?>
 <section class="fcw-section fcw-guide-section"><header class="fcw-section-heading"><span class="fcw-eyebrow"><?= e(fcc_public_copy('guides')) ?></span><h2><?= e($data->homepage_semantics['hero_heading']) ?></h2><p><?= e($data->homepage_semantics['hero_summary']) ?></p></header><nav class="fcw-guide-links" aria-label="<?= e(fcc_public_copy('guides')) ?>"><?php foreach($data->homepage_semantics['hub_pages'] as $guide): ?><a href="<?= e($guide['url']) ?>"><?= e($guide['name']) ?> <span aria-hidden="true">↗</span></a><?php endforeach ?></nav></section>
 <?php if(settings()->main->display_index_faq): $faq_keys=[];foreach(array_merge(\Altum\Language::get(\Altum\Language::$main_name),\Altum\Language::get(\Altum\Language::$name)) as $key=>$value)if(preg_match('/^index\.faq\.(\w+)\.question$/',$key,$match))$faq_keys[]=$match[1];if($faq_keys): ?>
 <section class="fcw-section fcw-faq"><header class="fcw-section-heading"><h2><?= l('index.faq.header') ?></h2></header><?php foreach($faq_keys as $key): ?><details><summary><?= l('index.faq.'.$key.'.question') ?></summary><div><?= l('index.faq.'.$key.'.answer') ?></div></details><?php endforeach ?></section>
 <?php endif;endif ?>
 <section class="fcw-closing"><div><span class="fcw-eyebrow">Forever Card Club</span><h2><?= e(fcc_public_copy('next')) ?></h2><p><?= e(fcc_public_copy('next_text')) ?></p></div><div class="fcw-actions"><a class="fcw-button" href="<?= e(url(is_logged_in()?'partner':'login')) ?>"><?= e(fcc_public_copy('enter')) ?> ↗</a><?php if(settings()->users->register_is_enabled): ?><a class="fcw-text-link" href="<?= e(fcc_public_url('register')) ?>"><?= e(fcc_public_copy('register')) ?></a><?php endif ?></div></section>
</div>
<?php ob_start(); ?>
<script type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@graph'=>[
 ['@type'=>'Organization','@id'=>SITE_URL.'#organization','name'=>'Forever Card Club','url'=>SITE_URL,'description'=>fcc_public_copy('independent'),'email'=>'info@forevercard.club'],
 ['@type'=>'WebSite','@id'=>SITE_URL.'#website','name'=>'Forever Card Club','url'=>SITE_URL,'publisher'=>['@id'=>SITE_URL.'#organization']],
 ['@type'=>'WebPage','@id'=>url().'#webpage','name'=>$data->homepage_semantics['title'],'description'=>$data->homepage_semantics['description'],'url'=>url(),'isPartOf'=>['@id'=>SITE_URL.'#website'],'inLanguage'=>fcc_language_tag()],
]],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP) ?></script>
<?php if(!empty($faq_keys)): ?>
<script type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>array_map(static fn($key)=>['@type'=>'Question','name'=>strip_tags(l('index.faq.'.$key.'.question')),'acceptedAnswer'=>['@type'=>'Answer','text'=>strip_tags(l('index.faq.'.$key.'.answer'))]],$faq_keys)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP) ?></script>
<?php endif ?>
<?php \Altum\Event::add_content(ob_get_clean(),'javascript'); ?>
